### ISSUE TITLE
magiskd cpu7 usage rate is over 90%

### ISSUE THREAD

**Issue by sekaiacg** [topjohnwu/Magisk#1238]
magisk ver: Magisk v18.2-2f2108e4e(18122) 
device：mi9 miui10 Android P
description:
1. Boot up after the first installation. 
2. Start the device for the first time after the update.

```
03-24 03:46:17.536   632  1103 I Magisk  : apk_install: /data/magisk.apk
03-24 03:46:17.692  1188  1188 I Magisk  : apk_install: cmd: Can't find service: package
03-24 03:46:22.819  2065  2065 I Magisk  : apk_install: 
03-24 03:46:22.819  2065  2065 I Magisk  : Exception occurred while executing:
03-24 03:46:22.819  2065  2065 I Magisk  : java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.os.storage.StorageManager.getVolumes()' on a null object reference
03-24 03:46:22.819  2065  2065 I Magisk  : 	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:184)
03-24 03:46:22.819  2065  2065 I Magisk  : 	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:148)
03-24 03:46:22.819  2065  2065 I Magisk  : 	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:163)
03-24 03:46:22.819  2065  2065 I Magisk  : 	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:502)
03-24 03:46:22.819  2065  2065 I Magisk  : 	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:404)
03-24 03:46:22.819  2065  2065 I Magisk  : 	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:2418)
03-24 03:46:22.819  2065  2065 I Magisk  : 	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:907)
03-24 03:46:22.819  2065  2065 I Magisk  : 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158)
03-24 03:46:22.819  2065  2065 I Magisk  : 	at android.os.ShellCommand.ex
--------- beginning of crash
```
log: [magisk.log](https://github.com/topjohnwu/Magisk/files/2999761/magisk.log)

**Comment by topjohnwu** [comment]
Install Magisk Manager and reboot should fix your issue
