### ISSUE TITLE
Magisk manager 7.1.1 crashes when trying to install Magisk 18.1

### ISSUE THREAD

**Issue by Fabian42** [topjohnwu/Magisk#1329]
It might be this stacktrace, I'm not sure, since I can't get a new one without Scoop:

java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{f73c01c 7554:com.topjohnwu.magisk/u0a93} (pid=7554, uid=10093) that is not exported from UID 10099
	at android.os.Parcel.readException(Parcel.java:2013)
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4758)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:5836)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2526)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1394)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:967)
	at a.Eq$f.e(:1)
	at a.iu.d(Unknown Source:0)
	at a.bu.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by Fabian42** [comment]
Installation via Recovery worked, but now all my modules were gone. XPosed installer for example was also gone before I installed Magisk via Recovery again.

**Comment by Fabian42** [comment]
@topjohnwu Why did you close this?

**Comment by martyfender** [comment]
Because you are supposed to be reporting bugs here on the Canary debug builds only.

**Comment by Fabian42** [comment]
And where am I supposed to report bugs in the main releases then?

**Comment by bafforosso** [comment]
You are not.
You are supposed to check if your bug has already been fixed in the canary channel, if it is then you can use the canary debug to report it here (debug log is more verbose)

**Comment by Fabian42** [comment]
You can't expect everyone to update to unstable versions of something that modifies the system. There is no guarantee that it wouldn't mess anything up and force me to redo my phone setup for weeks or months.
I just wanted to make you aware of this but, can't a developer check if it's still in the beta? In 99% of cases bugs don't just fix themselves without being reported.

**Comment by bafforosso** [comment]
Firstly if it is guarantees you want you may want to stay away from Magisk and rooting in general.

In 99% of cases, general bugs have already been reported, if one has not then there is a large chance that it is a specific combination of things in your setup that are triggering the problem. Circumstances which the devs may not be able to reproduce, or, in your case, not capable of reproducing because there is not even mention of basics such as your device or android version.

So if you want to return the favor of the devs putting their time for free for you to have tools like Magisk and, at the same time, help fix your issue you're gladly welcome to do so but please follow the rules and take the time to go all the way to provide a clean bug report as requested.
In the other hand, if it is just one-sided help you want to find a workaround or such, then Magisk help or XDA forums may be a better place to look.
