### ISSUE TITLE
Random BadTokenExceptions

### ISSUE THREAD

**Issue by binarynoise** [topjohnwu/Magisk#1518]
I recently get this Exceptions, seemingly random (nothing in the magisk logs) 
```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@19b999e is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at android.widget.Toast$TN.handleShow(Toast.java:459)
	at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```
I captured this Exception with scoop

**Comment by topjohnwu** [comment]
I don't see anything related to Magisk here

**Comment by binarynoise** [comment]
I do, because it's the magisk manager that crashes. About 10 times in the past 4 days. And I don't think, that this is normal

**Comment by Didgeridoohan** [comment]
No it's not, but you did not mention anything about the Manager crashing in your original message, and the log has nothing to do with Magisk.

If there's really a bug with the Manager you'll have to show what it is...
