### ISSUE TITLE
Magisk Manager crashes when opening corrupt or non-existing README

### ISSUE THREAD

**Issue by Henrocker** [topjohnwu/Magisk#1628]
When opening a README of a mod (e.g. V2ray in my example), Magisk Manager crashes the second time I tap on the Mod. First tapping returns pop up saying: Unable to download file, second time, Manager crashes.

My Device: Mi MiX 3 perseus with MIUI 10.3.1.0 Android 9 Pie and Kernel 4.9.112-perf-gf165f5d.

Most likely no README was provided for V2ray or it is corrupted.

Screenshot and Logcat attached.

Have a great day to all of you :-)

![Screenshot_2019-06-23-14-06-32-324_com MiOK Ow0r8kbexBA](https://user-images.githubusercontent.com/15855905/59976103-45dece80-95c0-11e9-937c-fd546aff5ff4.png)
![Screenshot_2019-06-23-14-05-43-846_launcher pie launcher](https://user-images.githubusercontent.com/15855905/59976104-45dece80-95c0-11e9-93eb-81807cd15d0b.png)
![Screenshot_2019-06-23-13-56-16-045_com MiOK Ow0r8kbexBA](https://user-images.githubusercontent.com/15855905/59976105-46776500-95c0-11e9-982f-6c4dc74dbc90.png)

```
---- 23.06.2019 14:09:56 ----

06-23 14:09:24.223  1391  3471 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.MiOK.Ow0r8kbexBA/a.c} from uid 10200

06-23 14:09:24.228  1391  3471 E ActivityTrigger: activityStartTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.c/224

06-23 14:09:24.231  1391  3471 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.c/224

06-23 14:09:24.249  1391  3471 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.c/224

06-23 14:09:24.272  1391  3471 I ActivityManager: Start proc 25269:com.MiOK.Ow0r8kbexBA/u0a200 for activity com.MiOK.Ow0r8kbexBA/a.c caller=com.MiOK.Ow0r8kbexBA

06-23 14:09:24.345   754   851 W SurfaceFlinger: Attempting to set client state on removed layer: thumbnail anim: AppWindowToken{e4b331e token=Token{cbd5b59 ActivityRecord{75863a0 u0 com.MiOK.Ow0r8kbexBA/a.c t635}}}#0

06-23 14:09:24.345   754   851 W SurfaceFlinger: Attempting to destroy on removed layer: thumbnail anim: AppWindowToken{e4b331e token=Token{cbd5b59 ActivityRecord{75863a0 u0 com.MiOK.Ow0r8kbexBA/a.c t635}}}#0

06-23 14:09:24.475  1391  1502 I ActivityManager: Displayed com.MiOK.Ow0r8kbexBA/a.c: +216ms

06-23 14:09:24.476  1391  1502 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{75863a0 u0 com.MiOK.Ow0r8kbexBA/a.c t635} time:6643313

06-23 14:09:24.489   754  2558 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.MiOK.Ow0r8kbexBA#0

06-23 14:09:24.489   754  2558 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.MiOK.Ow0r8kbexBA#0

06-23 14:09:24.870 25269 25269 I Timeline: Timeline: Activity_launch_request time:6643708 intent:Intent { cmp=com.MiOK.Ow0r8kbexBA/a.b (has extras) }

06-23 14:09:24.872  1391  3471 I ActivityManager: START u0 {cmp=com.MiOK.Ow0r8kbexBA/a.b (has extras)} from uid 10200

06-23 14:09:24.884  1391  3471 E ActivityTrigger: activityStartTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.b/224

06-23 14:09:24.886  1391  3471 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.b/224

06-23 14:09:24.896  1391  3027 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.b/224

06-23 14:09:24.976 25269 25269 I Timeline: Timeline: Activity_launch_request time:6643814 intent:Intent { cmp=com.MiOK.Ow0r8kbexBA/a.b (has extras) }

06-23 14:09:24.977  1391  1453 I ActivityManager: START u0 {cmp=com.MiOK.Ow0r8kbexBA/a.b (has extras)} from uid 10200

06-23 14:09:24.977  1391  1453 W ActivityManager: startActivity called from finishing ActivityRecord{75863a0 u0 com.MiOK.Ow0r8kbexBA/a.c t635 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.MiOK.Ow0r8kbexBA/a.b (has extras) }

06-23 14:09:24.980  1391  1453 E ActivityTrigger: activityStartTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.b/224

06-23 14:09:24.981  1391  1453 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.b/224

06-23 14:09:24.984  1391  1453 W ActivityManager: Duplicate finish request for ActivityRecord{75863a0 u0 com.MiOK.Ow0r8kbexBA/a.c t635 f}

06-23 14:09:25.015  1391  1453 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.b/224

06-23 14:09:25.120  1391  1502 I ActivityManager: Displayed com.MiOK.Ow0r8kbexBA/a.b: +101ms (total +220ms)

06-23 14:09:25.123   754  2558 W SurfaceFlinger: Attempting to set client state on removed layer: com.MiOK.Ow0r8kbexBA/a.c#0

06-23 14:09:25.123   754  2558 W SurfaceFlinger: Attempting to destroy on removed layer: com.MiOK.Ow0r8kbexBA/a.c#0

06-23 14:09:25.126  1391  1502 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{6409165 u0 com.MiOK.Ow0r8kbexBA/a.b t635} time:6643963

06-23 14:09:35.418   754   851 W SurfaceFlinger: Attempting to set client state on removed layer: com.MiOK.Ow0r8kbexBA/a.b#0

06-23 14:09:35.419   754   851 W SurfaceFlinger: Attempting to destroy on removed layer: com.MiOK.Ow0r8kbexBA/a.b#0

06-23 14:09:36.417 25269 25269 E AndroidRuntime: Process: com.MiOK.Ow0r8kbexBA, PID: 25269

06-23 14:09:36.425  1391  3027 W ActivityManager:   Force finishing activity com.MiOK.Ow0r8kbexBA/a.b

06-23 14:09:36.930  1391  1474 W ActivityManager: Activity pause timeout for ActivityRecord{6409165 u0 com.MiOK.Ow0r8kbexBA/a.b t635 f}

06-23 14:09:36.934  1391  1474 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.MiOK.Ow0r8kbexBA/a.b/224

06-23 14:09:38.425  1391  3027 W ActivityManager:   Force finishing activity com.MiOK.Ow0r8kbexBA/a.b

06-23 14:09:38.432  1391  3027 W ActivityManager:   Force finishing activity com.MiOK.Ow0r8kbexBA/a.b

06-23 14:09:38.464   754  2558 W SurfaceFlinger: Attempting to destroy on removed layer: 5edf7e4 Application Error: com.MiOK.Ow0r8kbexBA#0

06-23 14:09:38.482  1391  3027 I ActivityManager: Killing 25269:com.MiOK.Ow0r8kbexBA/u0a200 (adj 900): crash

06-23 14:09:38.525  1391  1779 W InputDispatcher: channel '165ba5c com.MiOK.Ow0r8kbexBA/a.b (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

06-23 14:09:38.525  1391  1779 E InputDispatcher: channel '165ba5c com.MiOK.Ow0r8kbexBA/a.b (server)' ~ Channel is unrecoverably broken and will be disposed!

06-23 14:09:38.525  1391  1779 W InputDispatcher: channel 'a21dac7 com.MiOK.Ow0r8kbexBA/a.b (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

06-23 14:09:38.525  1391  1779 E InputDispatcher: channel 'a21dac7 com.MiOK.Ow0r8kbexBA/a.b (server)' ~ Channel is unrecoverably broken and will be disposed!

06-23 14:09:38.544  1391  1756 W InputDispatcher: Attempted to unregister already unregistered input channel 'a21dac7 com.MiOK.Ow0r8kbexBA/a.b (server)'

06-23 14:09:38.544  1391  1756 W InputDispatcher: Attempted to unregister already unregistered input channel '165ba5c com.MiOK.Ow0r8kbexBA/a.b (server)'

06-23 14:09:38.546   754  2558 W SurfaceFlinger: Attempting to destroy on removed layer: a21dac7 com.MiOK.Ow0r8kbexBA/a.b#0

06-23 14:09:38.546   754  2558 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{7b87aeb token=Token{ee8de3a ActivityRecord{6409165 u0 com.MiOK.Ow0r8kbexBA/a.b t635}}}#0

06-23 14:09:38.546   754  2558 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{3317073 token=Token{e4d94e2 ActivityRecord{c10d9ad u0 com.MiOK.Ow0r8kbexBA/a.b t635}}}#0

06-23 14:09:38.546   754  2558 W SurfaceFlinger: Attempting to destroy on removed layer: 165ba5c com.MiOK.Ow0r8kbexBA/a.b#0

---- 23.06.2019 14:09:56 ----
```

**Comment by neoblackxt** [comment]
I got the same problem.

```
06-30 00:57:57.231 12271 12271 I opjohnwu.magis: Rejecting re-init on previously-failed class java.lang.Class<a.kx1>: java.lang.ExceptionInInitializerError: 
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at java.lang.String a.kx1.a(java.lang.String) (SourceFile:-1)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void a.tw1.a(java.lang.String, a.dy1) (SourceFile:47)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void a.zw1.a(a.ky1) (SourceFile:-1)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void a.s32.a(android.widget.TextView, java.lang.String) (SourceFile:8)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void a.nx0.a(java.lang.String) (SourceFile:36)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void a.nx0.a(java.lang.Object) (SourceFile:-1)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void a.dz0.a(a.ez0, java.lang.Object) (SourceFile:-1)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void a.qy0.run() (lambda:-1)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void android.os.Looper.loop() (Looper.java:207)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6867)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:876)
06-30 00:57:57.231 12271 12271 I opjohnwu.magis: 
06-30 00:57:57.231 12271 12271 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-30 00:57:57.232 12271 12271 E AndroidRuntime: FATAL EXCEPTION: main
06-30 00:57:57.232 12271 12271 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 12271
06-30 00:57:57.232 12271 12271 E AndroidRuntime: java.lang.NoClassDefFoundError: a.kx1
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at a.tw1.a(SourceFile:47)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at a.zw1.a(Unknown Source:12)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at a.s32.a(SourceFile:8)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at a.nx0.a(SourceFile:36)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at a.nx0.a(Unknown Source:2)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at a.dz0.a(Unknown Source:0)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at a.qy0.run(Unknown Source:4)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6867)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: Caused by: java.lang.ExceptionInInitializerError
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at a.kx1.a(Unknown Source:0)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	... 14 more
06-30 00:57:57.232 12271 12271 E AndroidRuntime: Caused by: java.lang.NullPointerException
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at java.io.Reader.<init>(Reader.java:78)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	at a.kx1.<clinit>(SourceFile:1)
06-30 00:57:57.232 12271 12271 E AndroidRuntime: 	... 15 more
06-30 00:57:57.235 12271 12271 E MQSEventManagerDelegate: failed to get MQSService.
06-30 00:57:57.260 12271 12271 I Process : Sending signal. PID: 12271 SIG: 9
```
