### ISSUE TITLE
Magisk isn't building fully on Windows 10 Home 32-bit

### ISSUE THREAD

**Issue by TheComputerGuy96** [topjohnwu/Magisk#176]
The cause is the zipadjust.exe file, which doesn't work on Windows 10 32-bit, as you see in this log snippet:
```
************************
* Adjusting Magisk-v14.0.zip
************************
This version of C:\Users\Namai\Documents\GitHub\Magisk\ziptools\win_bin\zipadjust.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
************************
* Final sign Magisk-v14.0.zip
************************
java.io.FileNotFoundException: Magisk-v14.0-adjusted.zip (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at eu.chainfire.minsignapk.MinSignAPK.main(MinSignAPK.java:154)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
The system cannot find the file specified.
```
Can you fix this issue, @topjohnwu?

**Comment by topjohnwu** [comment]
are you using a 32 bit machine?

**Comment by TheComputerGuy96** [comment]
@topjohnwu I'm using 32-bit Windows on a 64-bit machine

**Comment by topjohnwu** [comment]
@TheComputerGuy96  
For Unix systems, I will build it in the build scripts if `zip_adjust` does not exits, however I pre-built the exe for Windows because there is no C compiler in Windows by default, and the setup may vary (Visual C / mingw etc.)
The source code is under `ziptools/src`, you can compile them by yourself

**Comment by TheComputerGuy96** [comment]
@topjohnwu How can I compile zipadjust.exe (because I get build errors when building with MinGW)?
