### ISSUE TITLE
Magisk 7.3.3-f383d11d ACCESS_NETWORK_STATE

### ISSUE THREAD

**Issue by grant-h** [topjohnwu/Magisk#1851]
Following the tutorial at https://highonandroid.com/android-root/how-to-root-galaxy-s10-s10e-s10-plus-or-a50-exynos-only/ I attempted to root my device. It appears that it is rooted successfully as when I boot with VolUp+Bixby+Power, Magisk is automatically injected into the installed apps (it takes a second). Trying to run Magisk though leads to this exception.

Model: SM-G973F/DS
Android version: 9.0
Magisk Manager version: 7.3.3-f383d11d

```
09-18 16:35:43.918 14666 14666 E AndroidRuntime: FATAL EXCEPTION: main
09-18 16:35:43.918 14666 14666 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 14666
09-18 16:35:43.918 14666 14666 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.MainActivity}: java.lang.SecurityException: ConnectivityService: Neither user 10201 nor current process has android.permission.ACCESS_NETWORK_STATE.
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3113)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3256)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7037)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: Caused by: java.lang.SecurityException: ConnectivityService: Neither user 10201 nor current process has android.permission.ACCESS_NETWORK_STATE.
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1966)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1934)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1884)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1549)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1039)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at com.topjohnwu.magisk.MainActivity.onCreate(:1)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7327)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7318)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3093)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	... 11 more
09-18 16:35:43.918 14666 14666 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.ContextImpl.enforce(ContextImpl.java:1924)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1952)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at com.android.server.ConnectivityService.enforceAccessPermission(ConnectivityService.java:2231)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at com.android.server.ConnectivityService.getActiveNetworkInfo(ConnectivityService.java:1638)
09-18 16:35:43.918 14666 14666 E AndroidRuntime: 	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:86)
09-18 16:35:43.918 14666 14666 E AndroidRuntime:
```

I attempted to manually grant this permission using ADB, but it also errored. This makes sense as I don't see the permission requested anywhere in Magisk's AndroidManifest.xml.

```$ adb shell pm grant  com.topjohnwu.magisk ```
```android.permission.ACCESS_NETWORK_STATE
Security exception: Package com.topjohnwu.magisk has not requested permission android.permission.ACCESS_NETWORK_STATE

java.lang.SecurityException: Package com.topjohnwu.magisk has not requested permission android.permission.ACCESS_NETWORK_STATE
	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:389)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2374)
	at com.android.server.pm.permission.PermissionManagerService.access$1100(PermissionManagerService.java:131)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:3240)
	at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6433)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25949)
	at android.os.Binder.shellCommand(Binder.java:642)
	at android.os.Binder.onTransact(Binder.java:540)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3329)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4763)
	at android.os.Binder.execTransact(Binder.java:739)```

**Comment by grant-h** [comment]
If I uninstalled the bundled Magisk Manager and install an older version, the new version makes it to the splash screen (which the bundled version did not), but a new, worse error occurs.

```
09-18 17:45:11.993  5637  6731 I Pageboost: vramdisk miss com.topjohnwu.magisk
09-18 17:45:11.993  5637  6731 E Pageboost: vramdisk add : com.topjohnwu.magisk size : 90112
09-18 17:45:11.993  5637  6731 I Pageboost: send string to vramdisk : a,com.topjohnwu.magisk,/data/app/com.topjohnwu.magisk-3xeChcTYWT-9vi5X4v-9JQ==/base.apk,2,0,4096,12288,24576,
09-18 17:45:11.993  6729  6729 E vramdiskd: received : a,com.topjohnwu.magisk,/data/app/com.topjohnwu.magisk-3xeChcTYWT-9vi5X4v-9JQ==/base.apk,2,0,4096,12288,24576,
09-18 17:45:11.993  6729  6729 E vramdiskd: verify_and_update_package_path, /data/app/com.topjohnwu.magisk-3xeChcTYWT-9vi5X4v-9JQ==/base.apk, stat failed:No such file or directory
09-18 17:45:11.993  6729  6729 E vramdiskd: get_path_from_packagelist , com.topjohnwu.magisk
09-18 17:45:11.994  6729  6729 E vramdiskd: get_path_from_packagelist, fgets error /system/bin/pm list package -f com.topjohnwu.magisk Too many symbolic links encountered
09-18 17:45:11.994  6729  6729 E vramdiskd: verify_and_update_package_path, get_path failed:com.topjohnwu.magisk
09-18 17:45:11.994  6729  6729 E vramdiskd: add_package_to_vramdisk, get_path failed:com.topjohnwu.magisk
```

The process hangs and the phone's performance starts to degrade. Eventually the UI starts stuttering. Uninstalling the app will fix this, but it leaves me without the ability to get root. I will try to install an older version of Magisk/Magisk Manager to see if that fixes the issue.

**Comment by topjohnwu** [comment]
Please check the official instructions for installing Magisk on S10 devices. The process is done by many people (me included), and it works fine.
