### ISSUE TITLE
Hide Magisk Manager failed on Oneplus 7T, latest canary (20003 - 248)

### ISSUE THREAD

**Issue by Caydenz** [topjohnwu/Magisk#1973]
"Hide Magisk Manager" option always fails on my 7T with the error "Hide Magisk Manager failed". It worked once, the first time I tried it, however I restored the original package using the option from settings and hiding no longer works. (I tried reinstalling the app multiple times)

There are no related lines in the log file... so let me know what information I can provide to get this solved.

I saw multiple crashes in my android log, not sure if related:

`android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:930)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:910)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:774)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:763)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:352)
	at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:135)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:79)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)`

Recorded logs when I opened magisk manager and tried to hide it: https://gist.github.com/Caydenz/ddfdf58476150986c5871cf7d3ed6eb5

**Comment by topjohnwu** [comment]
I understand the frustration, but with the current setup I am unable to debug (not your fault).
I will release a new build soon, which allows proper bug reporting.
