### ISSUE TITLE
MagiskHide: Bad JNI version returned from JNI_OnLoad

### ISSUE THREAD

**Issue by phedoreanu** [topjohnwu/Magisk#1996]
My banking app works fine w/o root. As soon as I hide it, it crashes with this exception:
```
824   835 I Magisk  : proc_monitor: [ch.postfinance.android] PID=[22293] UID=[10218]
824 22339 I Magisk  : hide_list rm: [ch.postfinance.android]
1361  1885 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=ch.postfinance.android/.ui.home.SplashScreenActivity bnds=[856,1449][1128,1867]} from uid 10152
 874   874 D Zygote  : Forked child process 22348
1361  1415 I ActivityManager: Start proc 22348:ch.postfinance.android/u0a218 for activity {ch.postfinance.android/ch.postfinance.android.ui.home.SplashScreenActivity}
22348 22348 E finance.androi: Not starting debugger since process cannot load the jdwp agent.
 649   649 E Layer   : [Surface(name=AppWindowToken{e8ee314 token=Token{6be9967 ActivityRecord{9eab926 u0 ch.postfinance.android/.ui.home.SplashScreenActivity t136}}})/@0xae9b7d6 - animation-leash#0] No local sync point found
 649   649 E Layer   : [Surface(name=AppWindowToken{d2b01ab token=Token{5c28a25 ActivityRecord{1c51e1c u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t85}}})/@0xd8ca290 - animation-leash#0] No local sync point found
22348 22348 W finance.android: type=1400 audit(0.0:2508): avc: denied { read } for name="/" dev="tmpfs" ino=20436 scontext=u:r:untrusted_app:s0:c218,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
22348 22348 W finance.android: type=1400 audit(0.0:2509): avc: denied { getattr } for path="/apex/com.android.runtime/bin/dexoptanalyzer" dev="loop7" ino=24 scontext=u:r:untrusted_app:s0:c218,c256,c512,c768 tcontext=u:object_r:dexoptanalyzer_exec:s0 tclass=file permissive=0
22348 22348 W finance.android: type=1400 audit(0.0:2510): avc: denied { getattr } for path="/apex/com.android.runtime/bin/dex2oat" dev="loop7" ino=21 scontext=u:r:untrusted_app:s0:c218,c256,c512,c768 tcontext=u:object_r:dex2oat_exec:s0 tclass=file permissive=0
22348 22348 W finance.android: type=1400 audit(0.0:2511): avc: denied { getattr } for path="/apex/com.android.runtime/bin/profman" dev="loop7" ino=30 scontext=u:r:untrusted_app:s0:c218,c256,c512,c768 tcontext=u:object_r:profman_exec:s0 tclass=file permissive=0
22348 22348 W finance.android: type=1400 audit(0.0:2512): avc: denied { getattr } for path="/vendor/bin/ATFWD-daemon" dev="dm-1" ino=28 scontext=u:r:untrusted_app:s0:c218,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0
22348 22348 W finance.android: type=1400 audit(0.0:2513): avc: denied { getattr } for path="/vendor/bin/KmInstallKeybox" dev="dm-1" ino=29 scontext=u:r:untrusted_app:s0:c218,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0
22348 22348 W finance.android: type=1400 audit(0.0:2514): avc: denied { getattr } for path="/vendor/bin/PktRspTest" dev="dm-1" ino=30 scontext=u:r:untrusted_app:s0:c218,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0
22348 22348 W finance.android: type=1400 audit(0.0:2515): avc: denied { getattr } for path="/vendor/bin/StoreKeybox" dev="dm-1" ino=31 scontext=u:r:untrusted_app:s0:c218,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0
22348 22348 W finance.android: type=1400 audit(0.0:2516): avc: denied { getattr } for path="/vendor/bin/toybox_vendor" dev="dm-1" ino=313 scontext=u:r:untrusted_app:s0:c218,c256,c512,c768 tcontext=u:object_r:vendor_toolbox_exec:s0 tclass=file permissive=0
22348 22348 D AndroidRuntime: Shutting down VM
22348 22348 E AndroidRuntime: FATAL EXCEPTION: main
22348 22348 E AndroidRuntime: Process: ch.postfinance.android, PID: 22348
22348 22348 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/ch.postfinance.android-fMBmSqX72vnp-2Gjh9PkbQ==/lib/arm64/libmfjava.so": -110
22348 22348 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
22348 22348 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
22348 22348 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1667)
22348 22348 E AndroidRuntime: 	at ch.postfinance.core.CurrentActivityHandlingApp.<clinit>(Unknown Source:2)
22348 22348 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
22348 22348 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
22348 22348 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1155)
22348 22348 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1218)
22348 22348 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
22348 22348 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
22348 22348 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
22348 22348 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
22348 22348 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
22348 22348 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
22348 22348 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
22348 22348 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
22348 22348 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
1361  1885 W ActivityTaskManager:   Force finishing activity ch.postfinance.android/.ui.home.SplashScreenActivity
1361  1388 I ActivityManager: Showing crash dialog for package ch.postfinance.android u0
1361  8026 E libc    : Access denied finding property "vendor.debug.egl.changepixelformat"
1361  8026 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
1361  1390 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{9eab926 u0 ch.postfinance.android/.ui.home.SplashScreenActivity t136 f}
1361  1390 W ActivityTaskManager: Activity pause timeout for ActivityRecord{9eab926 u0 ch.postfinance.android/.ui.home.SplashScreenActivity t136 f}
1361  8026 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
 903  1124 D Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CALIBRATION_SIZE
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CALIBRATION
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CALIBRATION_SIZE
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CALIBRATION
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CONNECTION_SIZE
 886   886 E         : gcs_get_sg_mod_conn_and_update_pld: subgraph mod conn size 0. Exiting
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CONNECTION_SIZE
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CONNECTION
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_CONNECTIONS_SIZE
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPHS_CONNECTION
 886   886 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_CONNECTIONS_SIZE
 886   886 E         : __gcs_get_sg_conn_and_update_pld: subgraph conn size 0. Exiting
 886   886 D         : pktzr_send_cmd: opcode = 0x3, size = 452, token = 2670
 886  1381 D         : ipc_resp_thread: opcode: 0x2, payload_size: 4, resp_buf size: 16
 886  1381 D         : pktzr_resp_cb: opcode = 0x2 size = 4 token = 2670
 886  1381 D         : pktzr_resp_cb: token 2670 matched
2904  3059 I AiAiReflection: Filtering unlaunchable event /deleted_app/0
^C
```

Any ideas @topjohnwu ? 😃

**Comment by topjohnwu** [comment]
#1152
