### ISSUE TITLE
App not starting on Miu 9

### ISSUE THREAD

**Issue by deniscuculic** [topjohnwu/Magisk#2050]
2019-11-06 21:34:35.586 6885-6885/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.topjohnwu.magisk, PID: 6885
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at a.w3.i(:9)
        at a.w3.b(Unknown Source:0)
        at a.y3.setContentView(Unknown Source:4)
        at a.z2.onCreate(:2)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:403)
        at android.app.Dialog.show(Dialog.java:302)
        at a.z2$a.b(Unknown Source:4)
        at a.v11.a(:6)
        at a.oa1.b(Unknown Source:0)
        at a.t91.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by topjohnwu** [comment]
Use debug builds for logs, this does not provide anything useful
