### ISSUE TITLE
Bootsigner cannot run on anything lower than Android 9.0

### ISSUE THREAD

**Issue by null4n** [topjohnwu/Magisk#2053]
``/system/bin/dalvikvm -Xnodex2oat -Xnoimage-dex2oat -cp stub.apk a.a`` can't run, return ``java.lang.ClassNotFoundException``. neither the full apk

full logcat
```
Unable to locate class 'a/a'
java.lang.ClassNotFoundException: a.a
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: La/xd;
Caused by: java.lang.ClassNotFoundException: a.xd
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.AppComponentFactory" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-OR9ShmX07LUV2unooaHwjQ==/base.apk"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Exception in thread "main" java.lang.ClassNotFoundException: a.a
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: La/xd;
Caused by: java.lang.ClassNotFoundException: a.xd
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.AppComponentFactory" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-OR9ShmX07LUV2unooaHwjQ==/base.apk"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by osm0sis** [comment]
It's a stub, of course it's not in there. Don't run it directly.

Call `. /data/adb/magisk/util_functions.sh` and then use `find_manager_apk` and `eval $BOOTSIGNER` to find and run it from the actual APK.

**Comment by null4n** [comment]
> It's a stub, of course it's not in there. Once installed it's still a stub, the actual full APK is elsewhere.
> 
> Don't run it directly. Call `. /data/adb/magisk/util_functions.sh` and then use `find_manager_apk` and `eval $BOOTSIGNER` to find and run it from the actual full Manager APK. I updated the functions in [6dd34ae](https://github.com/topjohnwu/Magisk/commit/6dd34aec479c5538de8acd9aade9c06b83b9e7e7) for a reason.
> 
> Please close this issue, since it's not one. +1

after use ``find_manager_apk`` still ClassNotFound error. didn't hide the manager ever. The ``DexPathList`` has changed from ``stub.apk`` to ``/data/app/com.topjohnwu.magask*****/base.apk``
```
Unable to locate class 'a/a'
java.lang.ClassNotFoundException: a.a
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException: androidx.core.app.AppComponentFactory
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.AppComponentFactory" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-Ve4E0_ZbD6yOpsSyF7ccJA==/base.apk"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Exception in thread "main" java.lang.ClassNotFoundException: a.a
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException: androidx.core.app.AppComponentFactory
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.AppComponentFactory" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-Ve4E0_ZbD6yOpsSyF7ccJA==/base.apk"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by osm0sis** [comment]
You still aren't following the procedure I described.

**Comment by null4n** [comment]
> You still aren't following the procedure I described.

Nope, here is my step
```
. /data/adb/magisk/utils_functions.sh
setup_flashable
mount_partitions
check_data
get_flags
find_boot_image
find_manager_apk
eval $BOOTSIGNER -verify < $BOOTIMAGE
```

**Comment by osm0sis** [comment]
Are you running booted or not booted? Point is it's something wrong with your method, not Magisk.

**Comment by null4n** [comment]
already boot completed. run it in adb shell with root prompt

**Comment by osm0sis** [comment]
Run what I wrote and it will work.

**Comment by osm0sis** [comment]
Since you want to use `$BOOTIMAGE` as well, you only need the following:

```
. /data/adb/magisk/util_functions.sh
get_flags
find_boot_image
find_manager_apk
eval $BOOTSIGNER -verify < $BOOTIMAGE
```

It's verified working. There is an "unexpected end-of-contents marker" error it'll show, but that just actually means "unsigned" (I've fixed this in https://github.com/topjohnwu/Magisk/commit/95395432de1ffa74e260122ed51bc2533a9dad2d)

**Comment by null4n** [comment]
still the same 😢

```
NB1:/ # . /data/adb/magisk/util_functions.sh
NB1:/ # get_flags
1|NB1:/ # find_boot_image
NB1:/ # find_manager_apk
NB1:/ # eval $BOOTSIGNER -verify < $BOOTIMAGE
Unable to locate class 'a/a'
java.lang.ClassNotFoundException: a.a
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of:
Landroidx/core/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException:
androidx.core.app.AppComponentFactory
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of:
Landroid/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException: Didn't find class
"android.app.AppComponentFactory" on path: DexPathList[[zip file
"/data/app/com.topjohnwu.magisk-Ve4E0_ZbD6yOpsSyF7ccJA==/base.apk"],nativeLibraryDirectories=[/system/lib64,
/system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
        at
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Exception in thread "main" java.lang.ClassNotFoundException: a.a
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of:
Landroidx/core/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException:
androidx.core.app.AppComponentFactory
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of:
Landroid/app/AppComponentFactory;
Caused by: java.lang.ClassNotFoundException: Didn't find class
"android.app.AppComponentFactory" on path: DexPathList[[zip file
"/data/app/com.topjohnwu.magisk-Ve4E0_ZbD6yOpsSyF7ccJA==/base.apk"],nativeLibraryDirectories=[/system/lib64,
/system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
        at
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by osm0sis** [comment]
Huh, that's weird. Here it works both with Manager unhidden and hidden.

Try the following and give me the output:
```
:/ $ su
:/ # . /data/adb/magisk/util_functions.sh
:/ # get_flags
1|:/ # find_boot_image
:/ # find_manager_apk
:/ # echo $BOOTSIGNER
/system/bin/dalvikvm -Xnodex2oat -Xnoimage-dex2oat -cp $APK $BOOTSIGNERCLASS
:/ # echo $APK
/data/app/com.topjohnwu.magisk-vMcWQUvpqVIA8W3SlJMOOg==/base.apk
```

After that this is what I get with the full command:
```
:/ # eval $BOOTSIGNER -verify < $BOOTIMAGE
java.io.IOException: unexpected end-of-contents marker
        at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source:14)
        at com.topjohnwu.signing.SignBoot$BootSignature.<init>(SignBoot.java:235)
        at com.topjohnwu.signing.SignBoot.verifySignature(SignBoot.java:144)
        at com.topjohnwu.signing.BootSigner.main(BootSigner.java:15)
        at a.a.main(a.java:20)
1|:/ #
```

**Comment by osm0sis** [comment]
Maybe you installed the stub.apk by mistake? Uninstall it and install the latest Canary APK from here: https://github.com/topjohnwu/magisk_files/blob/canary/app-debug.apk

**Comment by null4n** [comment]
I have no stub apk installed, $BOOTSIGNER and $APK looks OK, but only flash magisk in manager can use bootsigner function.
```
NB1:/ # echo $BOOTSIGNER
/system/bin/dalvikvm -Xnodex2oat -Xnoimage-dex2oat -cp $APK $BOOTSIGNERCLASS
NB1:/ # echo $APK
/data/app/com.topjohnwu.magisk-Ve4E0_ZbD6yOpsSyF7ccJA==/base.apk
NB1:/ # 
```

**Comment by osm0sis** [comment]
Not sure what to tell you, it very much seems like an environment issue on your side.

**Comment by null4n** [comment]
I use apktool decompile the release version 7.4.0 and found there is no androidx/core/app/AppComponentFactory.smali in smali directory. but this version can use bootsigner function while flashing magisk

**Comment by null4n** [comment]
I decompile the debug apk and found that AppComponentFactory.smali in it. but call ``android.app.AppComponentFactory`` which is not incloud in the apk

**Comment by null4n** [comment]
I also decompile the debug apk and found ``androidx.core.app.AppComponentFactory``. but it will call ``android.app.AppComponentFactory`` which is not included in the apk

**Comment by osm0sis** [comment]
Well yeah, not to mention how it works completely fine for me on all my devices..
