### ISSUE TITLE
Magisk manager crashes

### ISSUE THREAD

**Issue by HinataKato** [topjohnwu/Magisk#2121]
Android 10 MIUI11 MIX2S Use hidden package names

#######RuntimeEnvironmentInformation#######
crash time=2019-12-02 23:46:23.500
model=MIX 2S
android version=10(29)
brand=Xiaomi
manufacturer=Xiaomi
board=sdm845
hardware=qcom
device=polaris
version name=1.0
supported ABIs=arm64-v8a & armeabi-v7a & armeabi
display=QKQ1.190828.002 test-keys
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: com.VuFGmh.XgE.o.GNh, PID: 28910
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.VuFGmh.XgE.o.GNh/a.m}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: a.lm
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: a.lm
	at android.os.Parcel.readParcelableCreator(Parcel.java:3050)
	at android.os.Parcel.readParcelable(Parcel.java:2967)
	at android.os.Parcel.readValue(Parcel.java:2869)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3252)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.BaseBundle.getBoolean(BaseBundle.java:908)
	at android.app.Activity.restoreHasCurrentPermissionRequest(Activity.java:8234)
	at android.app.Activity.performCreate(Activity.java:7887)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
	... 11 more

**Comment by topjohnwu** [comment]
Report Magisk Manager related bugs with debug builds
