### ISSUE TITLE
Magisk Manager Canary 0dc9f5c3 crash on modules tab

### ISSUE THREAD

**Issue by norbertc** [topjohnwu/Magisk#2300]
The latest Magisk Manager canary (0dc9f5c3) crashes when going to the modules tab.

From the logcat:
```
01-23 06:52:39.200  4913  4913 I ls      : type=1400 audit(0.0:22280): avc: denied { ioctl } for path="pipe:[1562758]" dev="pipefs" ino=1562758 ioctlcmd=0x5413 scontext=u:r:magisk:s0 tcontext=u:object_r:magisk_file:s0 tclass=fifo_file permissive=1
01-23 06:52:39.268  2918  2918 D AndroidRuntime: Shutting down VM
01-23 06:52:39.269  2918  2918 E AndroidRuntime: FATAL EXCEPTION: main
01-23 06:52:39.269  2918  2918 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 2918
01-23 06:52:39.269  2918  2918 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 12
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at java.util.Arrays.rangeCheck(Arrays.java:123)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at java.util.Arrays.fill(Arrays.java:2828)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at androidx.recyclerview.widget.StaggeredGridLayoutManager$d.d(:2)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at androidx.recyclerview.widget.StaggeredGridLayoutManager.c(Unknown Source:31)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at androidx.recyclerview.widget.StaggeredGridLayoutManager.b(Unknown Source:1)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$f.a(Unknown Source:50)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at a.ks.a(:1)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at a.ks.b(Unknown Source:0)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:14)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:37)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.b(:52)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:2)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:726)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-23 06:52:39.269  2918  2918 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-23 06:52:39.270  2918  2918 E ThreadGroup: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 12
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at java.util.Arrays.rangeCheck(Arrays.java:123)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at java.util.Arrays.fill(Arrays.java:2828)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at androidx.recyclerview.widget.StaggeredGridLayoutManager$d.d(:2)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at androidx.recyclerview.widget.StaggeredGridLayoutManager.c(Unknown Source:31)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at androidx.recyclerview.widget.StaggeredGridLayoutManager.b(Unknown Source:1)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at androidx.recyclerview.widget.RecyclerView$f.a(Unknown Source:50)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at a.ks.a(:1)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at a.ks.b(Unknown Source:0)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:14)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:37)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.View.layout(View.java:22466)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.View.layout(View.java:22466)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.View.layout(View.java:22466)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at androidx.coordinatorlayout.widget.CoordinatorLayout.b(:52)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:2)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.View.layout(View.java:22466)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.View.layout(View.java:22466)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.View.layout(View.java:22466)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.View.layout(View.java:22466)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.View.layout(View.java:22466)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.View.layout(View.java:22466)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.Choreographer.doCallbacks(Choreographer.java:791)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.Choreographer.doFrame(Choreographer.java:726)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.os.Handler.handleCallback(Handler.java:883)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.os.Handler.dispatchMessage(Handler.java:100)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.os.Looper.loop(Looper.java:214)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at android.app.ActivityThread.main(ActivityThread.java:7356)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at java.lang.reflect.Method.invoke(Native Method)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-23 06:52:39.270  2918  2918 E ThreadGroup:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-23 06:52:39.273  2918  2918 I opjohnwu.magis: System.exit called, status: 1
01-23 06:52:39.273  2918  2918 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
01-23 06:52:39.287  1296  1494 W InputDispatcher: channel 'ee7a0ca com.topjohnwu.magisk/a.b (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-23 06:52:39.287  1296  1494 E InputDispatcher: channel 'ee7a0ca com.topjohnwu.magisk/a.b (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by linuxandria** [comment]
Please use del.dog or similar for logs. That's a pain to read on any screen but especially on mobile :)

**Comment by linuxandria** [comment]
I don't personally have the issue but I know a couple of people who do however

**Comment by 2220209876** [comment]
Same flashback

**Comment by realkot** [comment]
+1 the same issue

**Comment by lssong99** [comment]
Yes, my Pixel 4XL has same issue.... Other thing works as intended.....

**Comment by Fox2Code** [comment]
I put my version of the logs since the logs provided by norbertc don't come from the canary debug build
https://del.dog/mekisorfuf.log
Since the names are not obfuscated here it should be easier to fix
And please @norbertc use the `Canary (Debug)` if you want to upload your logs and not just the `Canary` channel

**Comment by wangdaning** [comment]
I have the same issue, it seems to be one of my modules causing it. If I reboot to safe mode (core only) all my installed modules are then visible.

**Comment by BilliTheKid** [comment]
Has anyone found a resolution for this? It crashes still when i press the tab. Even putting it into Core mode still crashes when i press the new modules UI tab

**Comment by kam821** [comment]
> Has anyone found a resolution for this? It crashes still when i press the tab. Even putting it into Core mode still crashes when i press the new modules UI tab

Yup, uninstall Manager (only Manager), install latest stable/beta Manager v7.5.1, cause Canary channel keeps only latest buils ;)
https://github.com/topjohnwu/Magisk/releases/download/manager-v7.5.1/MagiskManager-v7.5.1.apk

**Comment by BilliTheKid** [comment]
Done that but I cannot see my modules now

**Comment by BilliTheKid** [comment]
> > Has anyone found a resolution for this? It crashes still when i press the tab. Even putting it into Core mode still crashes when i press the new modules UI tab
> 
> Yup, uninstall Manager (only Manager), install latest stable/beta Manager v7.5.1, cause Canary channel keeps only latest build ;)
> https://github.com/topjohnwu/Magisk/releases/download/manager-v7.5.1/MagiskManager-v7.5.1.apk
> 
> Make sure that update channel is set to stable / beta before if want to hide Manager

Can't see my modules now
![Screenshot_20200124-183115](https://user-images.githubusercontent.com/56843472/73094169-f3f48300-3ed7-11ea-8ec2-a27d0df47858.png)

**Comment by topjohnwu** [comment]
Fix here 851ee81486cae0286ed021b5c808d81817540062

**Comment by BilliTheKid** [comment]
It seems some modules are crashing the module tab still. Like Viper and Dolby. Also Selinux is not working or loading into modules either @topjohnwu

**Comment by norbertc** [comment]
@BilliTheKid the new canary build with commit 851ee81 are not yet up as of the writing of this comment.

**Comment by BilliTheKid** [comment]
What does that mean?

**Comment by skittles9823** [comment]
@BilliTheKid it means wait for a magisk update.

**Comment by diareuse** [comment]
Actually, the fix is rather here https://github.com/topjohnwu/Magisk/commit/2b41f31d32dd5d54104ddad8bef8bed8d8b874bc as the previous fix didn't help in all circumstances of the aforementioned crash.
