### ISSUE TITLE
calling pm set-installer as root results in java.lang.SecurityException: Unknown calling UID: 0

### ISSUE THREAD

**Issue by darylrobert** [topjohnwu/Magisk#2539]
```
ginkgo:/ $ whoami
shell
ginkgo:/ $ pm set-installer jp.naver.line.android com.android.vending
Success
ginkgo:/ $ su
ginkgo:/ # whoami
root
ginkgo:/ # pm set-installer jp.naver.line.android com.android.vending
Security exception: Unknown calling UID: 0

java.lang.SecurityException: Unknown calling UID: 0
        at com.android.server.pm.PackageManagerService.setInstallerPackageName(Unknown Source:272)
        at com.android.server.pm.PackageManagerShellCommand.runSetInstaller(Unknown Source:15)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(Unknown Source:766)
        at android.os.ShellCommand.exec(Unknown Source:41)
        at com.android.server.pm.PackageManagerService.onShellCommand(Unknown Source:12)
        at android.os.Binder.shellCommand(Unknown Source:0)
        at android.os.Binder.onTransact(Unknown Source:144)
        at android.content.pm.IPackageManager$Stub.onTransact(Unknown Source:21)
        at com.android.server.pm.PackageManagerService.onTransact(Unknown Source:0)
        at android.os.Binder.execTransact(Unknown Source:65)
ginkgo:/ #
```

**Comment by topjohnwu** [comment]
This is a check in the framework of your device, there is nothing I can do

**Comment by darylrobert** [comment]
Thank you for the confirmation.
