### ISSUE TITLE
[BUG] Amazon FireHD10 > zygotez > framework@edxp.jar@classes.dex > Cause: null pointer dereference

### ISSUE THREAD

**Issue by betterversion** [topjohnwu/Magisk#2664]
**What happened?**
Installed Magisk 20.4 & MagiskManager 7.5 . 
Have a temporary root with mtk-su based on this topic https://forum.xda-developers.com/showpost.php?p=82081703&postcount=1001

After adding Riru-Core & riru_edxposed_sandooh modules on magisk boot it freezes. Only reboot helps

**Xposed Module List**
none

**Magisk/Magisk Module List**

Riru Core
Riru EdXposed SandHook
CloudFlare
ainur_narsil
font_Changer
adb_ndk
terminal_mods
single_user
nano_ndk
busybox
systemizer

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
EdXposed: 0.4.6.2
EdXposedApi 91.0
RiruCore 19.7

**相关Logcat/Logcat**

attached magisk logs [magisk.log](https://github.com/topjohnwu/Magisk/files/4454068/magisk.log)

```
--------- beginning of crash
04-08 22:48:51.602  1661  1661 E AndroidRuntime: FATAL EXCEPTION: main
04-08 22:48:51.602  1661  1661 E AndroidRuntime: Process: com.mgoogle.android.gms, PID: 1661
04-08 22:48:51.602  1661  1661 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver org.microg.gms.gcm.TriggerReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=org.microg.gms.gcm.mcs.CONNECT cmp=com.mgoogle.android.gms/org.microg.gms.gcm.McsService (has extras) }: app is in background uid UidRecord{bec17a8 u0a185 RCVR idle change:uncached procs:1 seq(0,0,0)}
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3409)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.app.ActivityThread.access$1200(ActivityThread.java:207)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6734)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=org.microg.gms.gcm.mcs.CONNECT cmp=com.mgoogle.android.gms/org.microg.gms.gcm.McsService (has extras) }: app is in background uid UidRecord{bec17a8 u0a185 RCVR idle change:uncached procs:1 seq(0,0,0)}
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1613)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1568)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:102)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at org.microg.gms.gcm.TriggerReceiver.onReceive(TriggerReceiver.java:88)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3400)
04-08 22:48:51.602  1661  1661 E AndroidRuntime: 	... 8 more
04-08 22:48:52.030   639   666 W Looper  : Slow dispatch took 270ms android.ui h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver@97ce8f5 m=0
04-08 22:48:52.030   639   666 W Looper  : Slow delivery took 271ms android.ui h=android.view.ViewRootImpl$ViewRootHandler c=android.widget.Editor$1@ba8068a m=0
04-08 22:48:52.032   639   666 W Looper  : Drained
04-08 22:48:54.531  4619  4619 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 4619 (main), pid 4619 (main)
04-08 22:48:54.596  4619  4619 F libc    : crash_dump helper failed to exec
04-08 22:48:58.434  4678  4678 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 4678 (main), pid 4678 (main)
04-08 22:48:58.510  4740  4740 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-08 22:48:58.511  4740  4740 F DEBUG   : Build fingerprint: 'Amazon/maverick/maverick:7.0/PS7310/940N:user/amz-p,release-keys'
04-08 22:48:58.511  4740  4740 F DEBUG   : Revision: '0'
04-08 22:48:58.511  4740  4740 F DEBUG   : ABI: 'arm'
04-08 22:48:58.511  4740  4740 F DEBUG   : pid: 4678, tid: 4678, name: main  >>> zygote <<<
04-08 22:48:58.511  4740  4740 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-08 22:48:58.511  4740  4740 F DEBUG   : Cause: null pointer dereference
04-08 22:48:58.511  4740  4740 F DEBUG   :     r0  00000000  r1  00000000  r2  6fc973f4  r3  f28d7d80
04-08 22:48:58.511  4740  4740 F DEBUG   :     r4  f5cedd8c  r5  f286b46c  r6  00000000  r7  fff44ce8
04-08 22:48:58.511  4740  4740 F DEBUG   :     r8  00000000  r9  f28da000  r10 00000000  r11 fff44d84
04-08 22:48:58.511  4740  4740 F DEBUG   :     ip  f281dded  sp  fff44cd8  lr  f281de13  pc  f281de1e
04-08 22:48:58.513  4740  4740 F DEBUG   : 
04-08 22:48:58.513  4740  4740 F DEBUG   : backtrace:
04-08 22:48:58.513  4740  4740 F DEBUG   :     #00 pc 00034e1e  /system/lib/libriru_edxp.so
04-08 22:48:58.513  4740  4740 F DEBUG   :     #01 pc 00003831  /data/dalvik-cache/arm/system@framework@edxp.jar@classes.dex (offset 0x3000)
04-08 22:49:03.476  4744  4744 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 4744 (main), pid 4744 (main)
04-08 22:49:03.565  4799  4799 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-08 22:49:03.565  4799  4799 F DEBUG   : Build fingerprint: 'Amazon/maverick/maverick:7.0/PS7310/940N:user/amz-p,release-keys'
04-08 22:49:03.565  4799  4799 F DEBUG   : Revision: '0'
04-08 22:49:03.565  4799  4799 F DEBUG   : ABI: 'arm'
04-08 22:49:03.565  4799  4799 F DEBUG   : pid: 4744, tid: 4744, name: main  >>> zygote <<<
04-08 22:49:03.565  4799  4799 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-08 22:49:03.565  4799  4799 F DEBUG   : Cause: null pointer dereference
04-08 22:49:03.565  4799  4799 F DEBUG   :     r0  00000000  r1  00000000  r2  6fc973f4  r3  e47d7d80
04-08 22:49:03.565  4799  4799 F DEBUG   :     r4  e4a6ed8c  r5  e474f46c  r6  00000000  r7  ffd5ab18
04-08 22:49:03.565  4799  4799 F DEBUG   :     r8  00000000  r9  e47da000  r10 00000000  r11 ffd5abb4
04-08 22:49:03.565  4799  4799 F DEBUG   :     ip  e4701ded  sp  ffd5ab08  lr  e4701e13  pc  e4701e1e
04-08 22:49:03.566  4799  4799 F DEBUG   : 
04-08 22:49:03.566  4799  4799 F DEBUG   : backtrace:
04-08 22:49:03.566  4799  4799 F DEBUG   :     #00 pc 00034e1e  /system/lib/libriru_edxp.so
04-08 22:49:03.566  4799  4799 F DEBUG   :     #01 pc 00003831  /data/dalvik-cache/arm/system@framework@edxp.jar@classes.dex (offset 0x3000)
04-08 22:49:08.453  4803  4803 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 4803 (main), pid 4803 (main)
04-08 22:49:08.540  4861  4861 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

**Comment by betterversion** [comment]
[magisk.log](https://github.com/topjohnwu/Magisk/files/4454068/magisk.log)

**Comment by topjohnwu** [comment]
Why are you asking module specific bugs here?
