### ISSUE TITLE
Requires Additional Setup

### ISSUE THREAD

**Issue by atarek1** [topjohnwu/Magisk#2900]
Hello,
Magisk canary release: 20416
Magisk manager: 285
Device: samsung galaxy note 3 "hlte" 
Rom: resurrection remix
Android version: 9.0
TWRP: 3.3.1
After updated magisk from version 20401 to 20416 through magisk manager and reboot device ,then uncheck/check magisk hide a pop message attached is shown and magisk manager log is cleared , i tried to patch boot image and flash from recovery same behavior happens, when i click setup in additional setup dialogue an alert is shown "setup failed" 
This behavior happen also in magisk version: 20415
Last known working version magisk: 20401
I can provide any required info or troubleshooting.
![Screenshot_20200620-164804_Magisk_Manager](https://user-images.githubusercontent.com/29482903/85205118-68addb00-b319-11ea-8277-323350a102af.png)

**Comment by Fox2Code** [comment]
Please provide `logcat` with `adb logcat` because the information you gave us doesn't allow us to know where the problem came from.

**Comment by atarek1** [comment]
Attached installation and after reboot screenshot ,
Magisk manager log before enable magisk hide & logcat 
[magisk_log_20200620_184905.log](https://github.com/topjohnwu/Magisk/files/4808258/magisk_log_20200620_184905.log)
[logcat.txt](https://github.com/topjohnwu/Magisk/files/4808259/logcat.txt)
![Screenshot_20200620-184020_Magisk_Manager](https://user-images.githubusercontent.com/29482903/85207500-871bd280-b329-11ea-92b2-caf2500fd11f.png)
![Screenshot_20200620-184857_Magisk_Manager](https://user-images.githubusercontent.com/29482903/85207511-8f740d80-b329-11ea-9cf3-3da452975305.png)

**Comment by Fox2Code** [comment]
I read your logs and extracted the most important for others Magisk devs to read
I found Magisk Manager throw this stacktrace
```
java.io.FileNotFoundException: No such file or directory
	at com.topjohnwu.superuser.internal.ShellIO.<clinit>(ShellIO.java:37)
	at com.topjohnwu.superuser.internal.ShellIO.get(ShellIO.java:73)
	at com.topjohnwu.superuser.internal.ShellOutputStream.<init>(ShellOutputStream.java:32)
	at com.topjohnwu.superuser.internal.IOFactory.createShellOutputStream(IOFactory.java:55)
	at com.topjohnwu.superuser.io.SuFileOutputStream.getOut(SuFileOutputStream.java:62)
	at com.topjohnwu.superuser.io.SuFileOutputStream.<init>(SuFileOutputStream.java:79)
	at com.topjohnwu.superuser.io.SuFileOutputStream.<init>(SuFileOutputStream.java:57)
	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.extractZip(MagiskInstallImpl.kt:127)
	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.fixEnv(MagiskInstallImpl.kt:367)
	at com.topjohnwu.magisk.core.tasks.EnvFixTask.operations(MagiskInstaller.kt:66)
	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$1.call(MagiskInstallImpl.kt:374)
	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$1.call(MagiskInstallImpl.kt:35)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```
And I found that `magiskd` crash here
```
06-20 18:49:17.525  6194  6194 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-20 18:49:17.525  6194  6194 F DEBUG   : LineageOS Version: 'unknown'
06-20 18:49:17.525  6194  6194 F DEBUG   : Build fingerprint: 'samsung/hltexx/hlte:5.0/LRX21V/N9005XXSGBRI2:user/release-keys'
06-20 18:49:17.526  6194  6194 F DEBUG   : Revision: '0'
06-20 18:49:17.526  6194  6194 F DEBUG   : ABI: 'arm'
06-20 18:49:17.526  6194  6194 F DEBUG   : pid: 446, tid: 6191, name: magiskd  >>> magiskd <<<
06-20 18:49:17.526  6194  6194 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-20 18:49:17.526  6194  6194 F DEBUG   : Abort message: 'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0xa8bfbf28)'
06-20 18:49:17.526  6194  6194 F DEBUG   :     r0  00000000  r1  0000182f  r2  00000006  r3  00000008
06-20 18:49:17.526  6194  6194 F DEBUG   :     r4  000001be  r5  0000182f  r6  a7bff6ec  r7  0000010c
06-20 18:49:17.526  6194  6194 F DEBUG   :     r8  a88eee0c  r9  a8bfbf30  r10 a7c00890  r11 0000182e
06-20 18:49:17.526  6194  6194 F DEBUG   :     ip  a8bfbef4  sp  a7bff6d8  lr  a8868125  pc  a885fe4a
06-20 18:49:17.534  6194  6194 F DEBUG   : 
06-20 18:49:17.534  6194  6194 F DEBUG   : backtrace:
06-20 18:49:17.534  6194  6194 F DEBUG   :     #00 pc 0001ce4a  /system/lib/libc.so (abort+58)
06-20 18:49:17.534  6194  6194 F DEBUG   :     #01 pc 00065e17  /system/lib/libc.so (__fortify_fatal(char const*, ...)+26)
06-20 18:49:17.534  6194  6194 F DEBUG   :     #02 pc 00065489  /system/lib/libc.so (pthread_mutex_lock+144)
06-20 18:49:17.534  6194  6194 F DEBUG   :     #03 pc 0000bbd3  /sbin/magisk
06-20 18:49:17.534  6194  6194 F DEBUG   :     #04 pc 0000cc0b  /sbin/magisk
06-20 18:49:17.534  6194  6194 F DEBUG   :     #05 pc 00006167  /sbin/magisk
06-20 18:49:17.534  6194  6194 F DEBUG   :     #06 pc 00007cfd  /sbin/magisk
06-20 18:49:17.534  6194  6194 F DEBUG   :     #07 pc 00012de1  /sbin/magisk
06-20 18:49:17.534  6194  6194 F DEBUG   :     #08 pc 00064ac3  /system/lib/libc.so (__pthread_start(void*)+22)
06-20 18:49:17.534  6194  6194 F DEBUG   :     #09 pc 0001e061  /system/lib/libc.so (__start_thread+32)
```

**Comment by atarek1** [comment]
@topjohnwu could you advise what file or directory magisk manager looking for and thrown above exception when it's not found!
Or there is a condition if not exist then create ?
So issue cause is something else.

**Comment by Didgeridoohan** [comment]
It's likely a bug in MagiskHide (and as you say it's been around for a few releases now). All you should need to do is to reboot and everything will be back to normal.

**Comment by osm0sis** [comment]
Looks like it's fixed upstream. 20418 will have it included. :+1:
