### ISSUE TITLE
SuRequestHandler: java.io.IOException: Connection refused

### ISSUE THREAD

**Issue by huwenkai26** [topjohnwu/Magisk#2955]
```
2020-07-08 16:43:52.220 4545-4792/com.topjohnwu.magisk E/SuRequestHandler: java.io.IOException: Connection refused
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
        at android.net.LocalSocket.connect(LocalSocket.java:145)
        at com.topjohnwu.magisk.core.su.SuRequestHandler.start(SuRequestHandler.kt:53)
        at com.topjohnwu.magisk.ui.surequest.SuRequestViewModel.handleRequest(SuRequestViewModel.kt:76)
        at com.topjohnwu.magisk.ui.surequest.SuRequestActivity$onCreate$1$1.call(SuRequestActivity.kt:43)
        at com.topjohnwu.magisk.ui.surequest.SuRequestActivity$onCreate$1$1.call(SuRequestActivity.kt:23)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by topjohnwu** [comment]
Upgrade to the latest canary build
