### ISSUE TITLE
Segmentation fault during install of magisk 

### ISSUE THREAD

**Issue by ChaosEmpire** [topjohnwu/Magisk#3044]
I m trying to install magisk on my Samsung Galaxy Note Pro 12 SM-P905

I tried 18.1, 20.3 and 20.4
last i tried canary build as adviced 

the original img is 10mb
the new build one always 10.4mb so it cant fit into partition

here is the log

```
__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
Starting TWRP 3.0.2-0 on Thu Jan  1 18:03:07 1970
 (pid 201)
BOARD_HAS_NO_REAL_SDCARD := true
TW_NO_REBOOT_BOOTLOADER := true
RECOVERY_SDCARD_ON_DATA := true
I:Lun file '/sys/class/android_usb/android0/f_mass_storage/lun0/file' does not exist, USB storage mode disabled
TW_HAS_DOWNLOAD_MODE := true
I:TW_BRIGHTNESS_PATH := /sys/devices/mdp.0/qcom,mdss_fb_primary.171/leds/lcd-backlight/brightness
I:Found brightness file at '/sys/devices/mdp.0/qcom,mdss_fb_primary.171/leds/lcd-backlight/brightness'
I:TWFunc::Set_Brightness: Setting brightness control to 255
I:LANG: en
Starting the UI...Overlay graphics may work (mdssfb_c0000), but not enabled. Use TW_TARGET_USES_QCOM_BSP := true to enable.
Skipping adf graphics -- not present in build tree
Skipping drm graphics -- not present in build tree
fb0 reports (possibly inaccurate):
  vi.bits_per_pixel = 32
  vi.red.offset   =  24   .length =   8
  vi.green.offset =  16   .length =   8
  vi.blue.offset  =   8   .length =   8
setting GGL_PIXEL_FORMAT_RGBX_8888
double buffered
framebuffer: 3 (2560 x 1600)
Using fbdev graphics.
I:TWFunc::Set_Brightness: Setting brightness control to 255
I:Loading package: splash (/twres/splash.xml)
I:Load XML directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/splash.xml' directly
I:Checking resolution...
I:Scaling theme width 1.333333x and height 1.333333x, offsets x: 0 y: 0
I:Loading resources...
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page splash
I:Switching packages (splash)
=> Linking mtab
Moving /etc/twrp.fstab -> /etc/recovery.fstab
=> Processing recovery.fstab
I:Processing '/boot'
I:Processing '/cache'
I:Processing '/data'
I:Setting up '/data' as data/media emulated storage.
I:Created '/sdcard' folder.
I:mount -o bind '/data/media' '/sdcard' process ended with RC=0
I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
I:Processing '/recovery'
I:Processing '/system'
I:Processing '/external_sd'
I:Created '/external_sd' folder.
I:Processing '/efs'
I:Processing '/modem'
I:Processing '/modemst1'
I:Processing '/modemst2'
I:Backup folder set to '/data/media/0/TWRP/BACKUPS/0f3a4f61'
I:Settings storage is '/data/media/0'
Updating partition details...
I:Data backup size is 6274MB, free: 11008MB.
...done
I:Unmounting main partitions...


Partition Logs:
/boot | /dev/block/mmcblk0p14 | Size: 10MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p14
   Display_Name: Boot
   Storage_Name: boot
   Backup_Path: /boot
   Backup_Name: boot
   Backup_Display_Name: Boot
   Storage_Path: /boot
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/cache | /dev/block/mmcblk0p24 | Size: 196MB Used: 4MB Free: 192MB Backup Size: 4MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p24
   Display_Name: Cache
   Storage_Name: Cache
   Backup_Path: /cache
   Backup_Name: cache
   Backup_Display_Name: Cache
   Storage_Path: /cache
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/data | /dev/block/mmcblk0p26 | Size: 26642MB Used: 6274MB Free: 11008MB Backup Size: 6274MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent Has_Data_Media Can_Encrypt_Backup Use_Userdata_Encryption Is_Storage Is_Settings_Storage 
   Symlink_Path: /data/media/0
   Symlink_Mount_Point: /sdcard
   Primary_Block_Device: /dev/block/mmcblk0p26
   Length: -16384
   Display_Name: Data
   Storage_Name: Internal Storage
   Backup_Path: /data
   Backup_Name: data
   Backup_Display_Name: Data
   Storage_Path: /data/media/0
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files
   MTP_Storage_ID: 65537

/recovery | /dev/block/mmcblk0p15 | Size: 13MB
   Flags: IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p15
   Display_Name: Recovery
   Storage_Name: recovery
   Backup_Path: /recovery
   Backup_Name: recovery
   Backup_Display_Name: Recovery
   Storage_Path: /recovery
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/system | /dev/block/mmcblk0p23 | Size: 2372MB Used: 2302MB Free: 69MB Backup Size: 2302MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_Available_in_GUI IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p23
   Display_Name: System
   Storage_Name: System
   Backup_Path: /system
   Backup_Name: system
   Backup_Display_Name: System
   Storage_Path: /system
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/external_sd | /dev/block/mmcblk1p1 | Size: 15246MB Used: 7774MB Free: 7471MB Backup Size: 7774MB
   Flags: Can_Be_Mounted Can_Be_Wiped Wipe_Available_in_GUI Removable IsPresent Is_Storage 
   Primary_Block_Device: /dev/block/mmcblk1p1
   Alternate_Block_Device: /dev/block/mmcblk1
   Display_Name: external_sd
   Storage_Name: external_sd
   Backup_Path: /external_sd
   Backup_Name: external_sd
   Backup_Display_Name: external_sd
   Storage_Path: /external_sd
   Current_File_System: vfat
   Fstab_File_System: vfat
   Backup_Method: files
   MTP_Storage_ID: 65538

/efs | /dev/block/mmcblk0p11 | Size: 14MB
   Flags: Can_Be_Backed_Up IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p11
   Display_Name: EFS
   Storage_Name: EFS
   Backup_Path: /efs
   Backup_Name: efs
   Backup_Display_Name: EFS
   Storage_Path: /efs
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/modem | /dev/block/mmcblk0p2 | Size: 57MB
   Flags: Can_Be_Backed_Up Has_SubPartition IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p2
   Display_Name: MODEM
   Storage_Name: MODEM
   Backup_Path: /modem
   Backup_Name: modem
   Backup_Display_Name: MODEM
   Storage_Path: /modem
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/modemst1 | /dev/block/mmcblk0p12 | Size: 3MB
   Flags: Can_Be_Backed_Up Is_SubPartition IsPresent 
   SubPartition_Of: /modem
   Primary_Block_Device: /dev/block/mmcblk0p12
   Display_Name: modemst1
   Storage_Name: modemst1
   Backup_Path: /modemst1
   Backup_Name: modemst1
   Backup_Display_Name: modemst1
   Storage_Path: /modemst1
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/modemst2 | /dev/block/mmcblk0p13 | Size: 3MB
   Flags: Can_Be_Backed_Up Is_SubPartition IsPresent 
   SubPartition_Of: /modem
   Primary_Block_Device: /dev/block/mmcblk0p13
   Display_Name: modemst2
   Storage_Name: modemst2
   Backup_Path: /modemst2
   Backup_Name: modemst2
   Backup_Display_Name: modemst2
   Storage_Path: /modemst2
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

I:Loading package: TWRP (/data/media/0/TWRP/theme/ui.zip)
I:Loading zip theme
I:Loading package: TWRP (/twres/ui.xml)
I:Load XML directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/uk.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/tr.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sv.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sk.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/ru.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pt_BR.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/nl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/it.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/hu.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/fr.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/es.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/el.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/de.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/cz.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
parsing languageFile
parsing languageFile done
I:PageManager::LoadFileToBuffer loading filename: '/twres/ui.xml' directly
I:Checking resolution...
I:Scaling theme width 1.333333x and height 1.333333x, offsets x: 0 y: 0
I:Loading resources...
I:Failed to load image from indeterminate013, error -1
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Including file: /twres/landscape.xml...
I:PageManager::LoadFileToBuffer loading filename: '/twres/landscape.xml' directly
I:Loading resources...
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page main
I:Loading page main2
I:Loading page install
I:Loading page flash_confirm
I:Loading page flash_zip
I:Loading page flash_done
I:Loading page flashimage_confirm
I:Loading page clear_vars
I:Loading page confirm_action
I:Loading page action_page
I:Loading page singleaction_page
I:Loading page action_complete
I:Loading page filecheck
I:Loading page rebootcheck
I:Loading page wipe
I:Loading page advancedwipe
I:Loading page formatdata
I:Loading page formatdata_confirm
I:Loading page checkpartitionlist
I:Loading page partitionoptions
I:Loading page refreshfilesystem
I:Loading page selectfilesystem
I:Loading page backup
I:Loading page backupname1
I:Loading page backupname2
I:Loading page backupencryption
I:Loading page backupencryption2
I:Loading page checkbackuppassword
I:Loading page backup_run
I:Loading page restore
I:Unable to open '/data/media/0/TWRP/BACKUPS/0f3a4f61'
I:Loading page restore_read
I:Loading page restore_decrypt
I:Loading page try_restore_decrypt
I:Loading page restore_select
I:Loading page renamebackup
I:Loading page restore_run
I:Loading page mount
I:Loading page usb_mount
I:Loading page usb_umount
I:Loading page system_readonly_check
I:Loading page reboot
I:Loading page system_readonly
I:Loading page settings
I:Loading page settings_timezone
I:Loading page settings_screen
I:Loading page settings_vibration
I:Loading page settings_language
I:Loading page advanced
I:Loading page partsdcardsel
I:Loading page partsdcardcheck
I:Loading page partsdcard
I:Loading page htcdumlock
I:Loading page lock
I:Loading page filemanagerlist
I:Loading page filemanageroptions
I:Loading page choosedestinationfolder
I:Loading page filemanagerrenamefile
I:Loading page filemanagerrenamefolder
I:Loading page filemanagerchmod
I:Loading page filemanagerconfirm
I:Loading page filemanageraction
I:Loading page decrypt
I:Loading page decrypt_pattern
I:Loading page trydecrypt
I:Loading page terminalcommand
I:Loading page sideload
I:Loading page fixcontexts
I:Loading page installsu
I:Loading page slideout
I:Loading page select_storage
I:Loading page select_language
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Switching packages (TWRP)
Renaming regular /file_contexts -> /file_contexts.bak
Moving /prebuilt_file_contexts -> /file_contexts
SELinux contexts loaded from /file_contexts
Full SELinux support is present.
I:Not using /misc, not defined in fstab.
I:Not using /misc, not defined in fstab.
Startup Commands: 
ro.qc.sdk.izat.service_mask=0x0
ro.qc.sdk.izat.premium_enabled=0
ro.qc.sdk.audio.ssr=false
ro.qc.sdk.audio.fluencetype=none
ro.qc.sdk.camera.facialproc=false
ro.qc.sdk.sensors.gestures=true
ro.sf.lcd_density=320
ro.adb.qemud=1
ro.com.google.gmsversion=4.4.2_r1
ro.com.google.clientidbase=android-samsung
ro.com.android.dateformat=MM-dd-yyyy
ro.com.android.dataroaming=true
ro.gps.agps_provider=1
ro.ril.hsxpa=1
ro.ril.gprsclass=10
ro.sec.fle.encryption=true
ro.boot.emmc=true
ro.boot.sec_atd.tty=/dev/ttyHSL0
ro.boot.baseband=msm
ro.boot.hardware=qcom
ro.boot.serialno=0f3a4f61
ro.boot.bootloader=P905XXUABOG1
ro.boot.uart_debug=0
ro.boot.debug_level=0x4f4c
ro.boot.warranty_bit=1
ro.boot.boot_recovery=1
ro.boot.emmc_checksum=3
ro.boot.nvdata_backup=0
ro.boot.cp_debug_level=0x55FF
ro.emmc=0
ro.hdmi.enable=true
ro.hwui.path_cache_size=8
ro.hwui.layer_cache_size=32
ro.hwui.shape_cache_size=2
ro.hwui.texture_cache_size=48
ro.hwui.gradient_cache_size=1
ro.hwui.drop_shadow_cache_size=4
ro.hwui.text_large_cache_width=2048
ro.hwui.text_small_cache_width=1024
ro.hwui.text_large_cache_height=1024
ro.hwui.text_small_cache_height=512
ro.omni.device=viennaltexx
ro.twrp.boot=1
ro.twrp.version=3.0.2-0
ro.wifi.channels=
ro.allow.mock.location=1
ro.board.platform=msm8974
ro.build.id=KTU84P
ro.build.PDA=P905XXUANAE
ro.build.date=Tue Apr  5 06:22:53 EDT 2016
ro.build.date.utc=0
ro.build.host=build
ro.build.knox.container=
ro.build.tags=test-keys
ro.build.type=eng
ro.build.user=jenkins
ro.build.scafe=latte
ro.build.scafe.shot=double
ro.build.scafe.size=grande
ro.build.display.id=omni_viennaltexx-eng 4.4.4 KTU84P 4 test-keys
ro.build.product=viennaltexx
ro.build.selinux=1
ro.build.version.sdk=19
ro.build.version.release=4.4.4
ro.build.version.codename=REL
ro.build.version.incremental=4
ro.build.changelist=433750
ro.build.hidden_ver=P905XXUANAE
ro.build.description=omni_viennaltexx-eng 4.4.4 KTU84P 4 test-keys
ro.build.fingerprint=Samsung/omni_viennaltexx/viennaltexx:4.4.4/KTU84P/4:eng/test-keys
ro.build.characteristics=default
ro.error.receiver.default=com.samsung.receiver.error
ro.hdcp2.rx=tz
ro.slook.ver=1
ro.config.knox=1
ro.config.tima=1
ro.config.ringtone=Over_the_horizon.ogg
ro.config.alarm_alert=Alarm_Morning_flower.ogg
ro.config.media_sound=Media_preview_Touch_the_light.ogg
ro.config.timaversion=2.0
ro.config.notification_sound=S_Whistle.ogg
ro.kernel.qemu=0
ro.kernel.android.checkjni=1
ro.secure=0
ro.secwvk=144
ro.vendor.extension_library=/vendor/lib/libqc-opt.so
ro.carrier=unknown
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.name=omni_viennaltexx
ro.product.board=viennaltexx
ro.product.brand=Samsung
ro.product.model=viennaltexx
ro.product.device=viennaltexx
ro.product.locale.region=US
ro.product.locale.language=en
ro.product.manufacturer=unknown
ro.baseband=msm
ro.bootmode=unknown
ro.chipname=MSM8974
ro.hardware=qcom
ro.opengles.version=196608
ro.qualcomm.cabl=1
ro.revision=12
ro.security.mdpp.ux=Enabled
ro.security.mdpp.ver=1.0
ro.security.mdpp.release=2
ro.serialno=0f3a4f61
ro.bootloader=P905XXUABOG1
ro.debuggable=1
ro.factorytest=0
ro.setupwizard.mode=DISABLED
ro.product_ship=true
ro.securestorage.support=true
ro.use_data_netmgrd=false
dev.pm.dyn_samplingrate=1
lpa.decode=false
lpa.use-stagefright=false
mmp.enable.3g2=true
net.bt.name=Android
net.change=net.bt.name
ril.subscription.types=NV,RUIM
init.svc.adbd=running
init.svc.healthd=running
init.svc.ueventd=running
init.svc.recovery=running
init.svc.set_permissive=stopped
rild.libargs=-d /dev/smd0
rild.libpath=/system/lib/libsec-ril.so
twrp.crash_counter=0
twrp.action_complete=0
debug.sf.hw=1
debug.egl.hw=1
debug.disable.bwc=1
debug.mdpcomp.logs=0
debug.composition.type=gpu
media.stagefright.enable-aac=true
media.stagefright.enable-qcp=true
media.stagefright.enable-http=true
media.stagefright.enable-scan=true
media.stagefright.enable-fma2dp=true
media.stagefright.enable-player=true
media.enable-commonsource=true
media.aac_51_output_enabled=true
dalvik.vm.heapsize=512m
dalvik.vm.heapmaxfree=8m
dalvik.vm.heapminfree=2m
dalvik.vm.heapstartsize=16m
dalvik.vm.heapgrowthlimit=192m
dalvik.vm.stack-trace-file=/data/anr/traces.txt
dalvik.vm.heaptargetutilization=0.75
tunnel.decode=false
tunnel.audiovideo.decode=false
persist.cne.feature=0
persist.gps.qc_nlp_in_use=0
persist.hwc.mdpcomp.enable=true
persist.sys.usb.config=mtp
persist.sys.wfd.virtual=0
persist.sys.dalvik.vm.lib=libdvm.so
persist.sys.logkit.ctrlcode=0
persist.sys.whitelist=/system/etc/whitelist_appops.xml
persist.sys.storage_preload=1
persist.sys.strict_op_enable=false
persist.data.netmgrd.qos.enable=false
persist.demo.hdmirotationlock=false
persist.rild.nitz_plmn=
persist.rild.nitz_long_ons_0=
persist.rild.nitz_long_ons_1=
persist.rild.nitz_long_ons_2=
persist.rild.nitz_long_ons_3=
persist.rild.nitz_short_ons_0=
persist.rild.nitz_short_ons_1=
persist.rild.nitz_short_ons_2=
persist.rild.nitz_short_ons_3=
persist.debug.wfd.enable=1
persist.radio.add_power_save=1
persist.radio.apm_sim_not_pwdn=1
persist.timed.enable=true
persist.speaker.prot.enable=false
persist.fuse_sdcard=true
service.adb.root=1
keyguard.no_require_sim=true
security.mdpp=None
security.mdpp.result=None
telephony.lteOnCdmaDevice=0
DEVICE_PROVISIONED=1

I:Copying file /cache/recovery/log to /cache/recovery/last_log
tw_get_context got selinux context: u:object_r:media_rw_data_file:s0
I:Got default contexts and file mode for storage files.
I:Attempt to load settings from settings file...
I:InfoManager loading from '/data/media/0/TWRP/.twrps'.
I:Backup folder set to '/external_sd/TWRP/BACKUPS/0f3a4f61'
I:Copying file /etc/recovery.fstab to /cache/recovery/recovery.fstab
I:Version number saved to '/cache/recovery/.version'
__bionic_open_tzdata: couldn't find any tzdata when looking for CST6CDT,M3.2.0,M11.1.0!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
I:TWFunc::Set_Brightness: Setting brightness control to 255
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/de.xml' directly
parsing languageFile
parsing languageFile done
I:Translating partition display names
I:Backup folder set to '/external_sd/TWRP/BACKUPS/0f3a4f61'
I:TWFunc::Fixup_Time: Pre-fix date and time: 1970-01-01--13-03-12
I:TWFunc::Fixup_Time: Setting time offset from file /sys/class/rtc/rtc0/since_epoch
I:TWFunc::Fixup_Time: will attempt to use the ats files now.
I:TWFunc::Fixup_Time: Setting time offset from file /data/time/ats_2, offset 1595927698738
I:TWFunc::Fixup_Time: Date and time corrected: 2020-07-28--22-18-10
I:Enabling MTP during startup
I:Starting MTP
I:sending message to add 65537 '/data/media/0' 'Interner Speicher'
Starting MTP
I:Message sent, add storage ID: 65537
I:sending message to add 65538 '/external_sd' 'Micro SD-Karte'
I:Message sent, add storage ID: 65538
MTP aktiviert
I:Check_Lifetime_Writes result: '306704'
I:Switching packages (TWRP)
I:Skipping screen timeout: TW_NO_SCREEN_TIMEOUT is set
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
E:could not open MTP driver, errno: 2
I:Set page: 'install'
I:Set overlay: 'select_storage'
I:Backup folder set to '/data/media/0/TWRP/BACKUPS/0f3a4f61'
I:DataManager::SetBackupFolder zip path was /external_sd/Download changing to /sdcard, /external_sd
I:Set overlay: ''
I:Set page: 'clear_vars'
I:Set page: 'install'
I:Set page: 'flash_confirm'
I:Set page: 'flash_zip'
I:operation_start: 'Flashing'
Installiere Zip '/sdcard/Download/magisk-debug.zip'
Suche nach MD5-Datei...
MD5-Prüfung übersprungen: keine MD5-Datei gefunden
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment initialized.
2026+0 records in
2026+0 records out
2074624 bytes (2.0MB) copied, 0.027658 seconds, 71.5MB/s
1381+1 records in
1381+1 records out
1415016 bytes (1.3MB) copied, 0.019415 seconds, 69.5MB/s
Archive:  /sdcard/Download/magisk-debug.zip
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script
  inflating: arm/magiskinit
  inflating: arm/magiskinit64
  inflating: arm/magiskboot
  inflating: x86/magiskinit
  inflating: x86/magiskinit64
  inflating: x86/magiskboot
  inflating: common/magisk.apk
  inflating: common/boot_patch.sh
  inflating: common/util_functions.sh
  inflating: common/addon.d.sh
  inflating: chromeos/futility
  inflating: chromeos/kernel_data_key.vbprivk
  inflating: chromeos/kernel.keyblock
**********************************
 Magisk 97b72a59(20419) Installer 
**********************************
- Mounting /system
- Target image: /dev/block/mmcblk0p14
- Device platform: arm
- Removing system installed root
- Constructing environment
java.io.IOException: ioctl failed: EINVAL (Invalid argument)
	at libcore.io.IoBridge.available(IoBridge.java:74)
	at java.io.FileInputStream.available(FileInputStream.java:108)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:274)
	at com.topjohnwu.signing.SignBoot.verifySignature(SignBoot.java:132)
	at com.topjohnwu.signing.BootSigner.main(BootSigner.java:15)
	at a.a.main(stubs.kt:14)
Caused by: android.system.ErrnoException: ioctl failed: EINVAL (Invalid argument)
	at libcore.io.Posix.ioctlInt(Native Method)
	at libcore.io.ForwardingOs.ioctlInt(ForwardingOs.java:99)
	at libcore.io.IoBridge.available(IoBridge.java:58)
	... 5 more
- Unpacking boot image
Parsing boot image: [/dev/block/mmcblk0p14]
HEADER_VER      [0]
KERNEL_SZ       [7803096]
RAMDISK_SZ      [1663861]
SECOND_SZ       [0]
EXTRA_SZ        [786432]
PAGESIZE        [2048]
NAME            [SERPCGUV001]
CMDLINE         [console=null androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x37 ehci-hcd.park=3]
CHECKSUM        [662a857976fa665431ce4557dadc6765b945ea1a000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
EXTRA_FMT       [raw]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Patch with flag KEEPVERITY=[false] KEEPFORCEENCRYPT=[false]
Found fstab file [fstab.qcom]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [extra]
Loading dtb.0000
Loading dtb.0001
Loading dtb.0002

- Repacking boot image
Parsing boot image: [/dev/block/mmcblk0p14]
HEADER_VER      [0]
KERNEL_SZ       [7803096]
RAMDISK_SZ      [1663861]
SECOND_SZ       [0]
EXTRA_SZ        [786432]
PAGESIZE        [2048]
NAME            [SERPCGUV001]
CMDLINE         [console=null androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x37 ehci-hcd.park=3]
CHECKSUM        [662a857976fa665431ce4557dadc6765b945ea1a000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
EXTRA_FMT       [raw]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [7803096]
RAMDISK_SZ      [1928845]
SECOND_SZ       [0]
EXTRA_SZ        [786432]
PAGESIZE        [2048]
NAME            [SERPCGUV001]
CMDLINE         [console=null androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x37 ehci-hcd.park=3]
CHECKSUM        [58b1fd5a6f3d62bf152b540f9b33f63ee6f680eb000000000000000000000000]
- Flashing new boot image
- Compressing ramdisk to fit in partition
Loading cpio: [ramdisk.cpio]
Compressing cpio -> [ramdisk.cpio.xz]
Segmentation fault
Parsing boot image: [/dev/block/mmcblk0p14]
HEADER_VER      [0]
KERNEL_SZ       [7803096]
RAMDISK_SZ      [1663861]
SECOND_SZ       [0]
EXTRA_SZ        [786432]
PAGESIZE        [2048]
NAME            [SERPCGUV001]
CMDLINE         [console=null androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x37 ehci-hcd.park=3]
CHECKSUM        [662a857976fa665431ce4557dadc6765b945ea1a000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
EXTRA_FMT       [raw]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [7803096]
RAMDISK_SZ      [1928845]
SECOND_SZ       [0]
EXTRA_SZ        [786432]
PAGESIZE        [2048]
NAME            [SERPCGUV001]
CMDLINE         [console=null androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x37 ehci-hcd.park=3]
CHECKSUM        [58b1fd5a6f3d62bf152b540f9b33f63ee6f680eb000000000000000000000000]
! Insufficient partition size
- Unmounting partitions
Prozess Updater endete mit FEHLER: 1
I:Legacy property environment disabled.
Fehler beim Installieren von ZIP '/sdcard/Download/magisk-debug.zip'
Partitions-Informationen werden aktualisiert...
I:Data backup size is 6274MB, free: 11008MB.
...Fertig
I:Set page: 'flash_done'
I:operation_end - status=1
I:Set page: 'clear_vars'
I:Set page: 'install'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'advanced'
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:operation_start: 'Copy Log'
I:Copying file /tmp/recovery.log to /data/media/0/recovery.log
```

**Comment by techIndia-hacker** [comment]
Tick encryption and verity and repatch AP

**Comment by techIndia-hacker** [comment]
In Samsung u don't patch boot partition only while AP is required

**Comment by mu198** [comment]
@techIndia-hacker The method that topjohnwu, then in the operating system, wrote has not been used since Knox 3.5. now you have to extract the boot.img and flash this as .tar file to get root

**Comment by mu198** [comment]
Otherwise, you only solve a vbmeta error see error #2272 This problem occurs with almost all new Samsung devices from the end of 2019 and 2020

**Comment by mu198** [comment]
@ChaosEmpire Try this method, so I could root my sm-p610

https://forum.xda-developers.com/showpost.php?p=79902328&postcount=29

**Comment by unixandria-xda** [comment]
First off, don't post logs directly attach as file or use a pastebin, I recommend del.dog.

Secondly, you aren't following the install guide at all anyway.

Third, I believe this issue was raised previously but was found to not actually cause any adverse behavior.

**Comment by techIndia-hacker** [comment]
Well in my samsung android 10 I do it the way i said it

**Comment by topjohnwu** [comment]
Unfortunately if Magisk is not gonna fit in the boot image, there is really not much I can do :(
