### ISSUE TITLE
Magisk Manager (20420) Force close when Trying to update Magisk zip 

### ISSUE THREAD

**Issue by edzamber** [topjohnwu/Magisk#3074]
```
FATAL EXCEPTION: main
Process: com.topjohnwu.magisk, PID: 10180
java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.Consider using setTextMetricsParams(precomputedText.getParams()) to override the settings of this TextView: PrecomputedText: {textSize=48.0, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR,en_GB,es_ES,it_IT,nl_NL,pl_PL,pt_PT,de_DE], typeface=android.graphics.Typeface@9abe8493, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@44bef7b, breakStrategy=1, hyphenationFrequency=0}TextView: {textSize=48.0, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR,en_GB,es_ES,it_IT,nl_NL,pl_PL,pt_PT,de_DE], typeface=android.graphics.Typeface@9abe8493, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@44bef7b, breakStrategy=1, hyphenationFrequency=0}
	at android.widget.TextView.setText(TextView.java:6712)
	at android.widget.TextView.setText(TextView.java:6630)
	at android.widget.TextView.setText(TextView.java:6582)
	at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:887)
	at com.topjohnwu.magisk.view.PrecomputedTextSetter$setText$1$1.run(MarkDownWindow.kt:25)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8125)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by topjohnwu** [comment]
How often does this happen?
What device/Android version?

**Comment by edzamber** [comment]
Anytime i try to update zip.

My device :Samsung S9 G960f.

But i think device model is not related, same issue with Samsung S20

**Comment by diareuse** [comment]
The crash will be fixed in the next release, I can promise you that.

**Comment by edzamber** [comment]
Great, thanks a lot @diareuse 👍
