### ISSUE TITLE
BM (bank app) stopped running with magisk

### ISSUE THREAD

**Issue by midozalouk** [topjohnwu/Magisk#3194]
Hello sir
This app
[Google play link ](https://play.google.com/store/apps/details?id=com.BanqueMisr.MobileBanking)
Stopped working recently with magisk 20.4 with Android 10 security patch September 2020 running on oneplus 7 open beta 18

Although i am activating magisk hide, renamed magisk manager, can pass safety test and removed all modules 
This is the logcat for the app by PID

`--------- beginning of system
09-21 20:26:52.245 15902 15902 E ActivityThread: Failed to find provider info for akhil.alltrans.sharedPrefProvider
--------- beginning of main
09-21 21:25:46.561 15902 15902 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6428c46
09-21 21:25:46.597 15902 15902 I AllTrans: AllTrans: AllTrans: in attachBaseContext of ContextWrapper for package com.BanqueMisr.MobileBanking
09-21 21:25:46.597 15902 15902 I AllTrans: AllTrans: AllTrans: returning because context already not null for package com.BanqueMisr.MobileBanking
09-21 21:25:46.597 15902 15902 I AllTrans: AllTrans: AllTrans: in attachBaseContext of ContextWrapper for package com.BanqueMisr.MobileBanking
09-21 21:25:46.597 15902 15902 I AllTrans: AllTrans: AllTrans: returning because context already not null for package com.BanqueMisr.MobileBanking
09-21 21:25:46.628 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:25:46.630 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:25:46.630 15902 15902 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
09-21 21:25:46.658 15902 15914 W r.MobileBankin: Reducing the number of considered missed Gc histogram windows from 352 to 100
09-21 21:25:46.662 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:25:46.665 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:25:46.665 15902 15902 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
09-21 21:25:46.672 15902 16096 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@e0b59b8[FinacleMobileApp]
09-21 21:25:46.674 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:25:46.772 15902 16096 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@e0b59b8[FinacleMobileApp]
09-21 21:25:47.109 15902 19539 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@e0b59b8[FinacleMobileApp]
09-21 21:25:50.074 15902 23467 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
09-21 21:25:50.075 15902 23482 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
09-21 21:25:50.189 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:25:50.290 15902 16067 I System.out: JSONCredInitializer called
09-21 21:25:51.188 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:25:51.374 15902 16067 I System.out: BGColorUpdater === file : true >> Color :true
09-21 21:25:51.498 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:25:53.247 15902 15916 W System  : A resource failed to call end. 
09-21 21:26:51.832 15902 19539 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@b127684[FinacleMobileApp]
09-21 21:26:53.220 15902 15902 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.
09-21 21:26:53.235 15902 15902 W cr_AwContents: Application attempted to call on a destroyed WebView
09-21 21:26:53.235 15902 15902 W cr_AwContents: java.lang.Throwable
09-21 21:26:53.235 15902 15902 W cr_AwContents: 	at org.chromium.android_webview.AwContents.p(chromium-TrichromeWebViewGoogle.aab-stable-1:2)
09-21 21:26:53.235 15902 15902 W cr_AwContents: 	at vB.loadingStateChanged(chromium-TrichromeWebViewGoogle.aab-stable-1:2)
09-21 21:26:53.235 15902 15902 W cr_AwContents: 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-21 21:26:53.235 15902 15902 W cr_AwContents: 	at android.os.MessageQueue.next(MessageQueue.java:336)
09-21 21:26:53.235 15902 15902 W cr_AwContents: 	at android.os.Looper.loop(Looper.java:174)
09-21 21:26:53.235 15902 15902 W cr_AwContents: 	at android.app.ActivityThread.main(ActivityThread.java:7709)
09-21 21:26:53.235 15902 15902 W cr_AwContents: 	at java.lang.reflect.Method.invoke(Native Method)
09-21 21:26:53.235 15902 15902 W cr_AwContents: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
09-21 21:26:53.235 15902 15902 W cr_AwContents: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-21 21:26:53.623 15902 15902 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@769f469
09-21 21:26:53.659 15902 15902 I AllTrans: AllTrans: AllTrans: in attachBaseContext of ContextWrapper for package com.BanqueMisr.MobileBanking
09-21 21:26:53.659 15902 15902 I AllTrans: AllTrans: AllTrans: returning because context already not null for package com.BanqueMisr.MobileBanking
09-21 21:26:53.659 15902 15902 I AllTrans: AllTrans: AllTrans: in attachBaseContext of ContextWrapper for package com.BanqueMisr.MobileBanking
09-21 21:26:53.659 15902 15902 I AllTrans: AllTrans: AllTrans: returning because context already not null for package com.BanqueMisr.MobileBanking
09-21 21:26:53.694 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:26:53.694 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:26:53.695 15902 15902 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
09-21 21:26:53.729 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:26:53.730 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:26:53.730 15902 15902 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
09-21 21:26:53.738 15902 19539 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@d6ff23[FinacleMobileApp]
09-21 21:26:53.738 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:26:53.838 15902 19539 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@d6ff23[FinacleMobileApp]
09-21 21:26:53.858 15902 15902 W Activity: Can request only one set of permissions at a time
09-21 21:26:54.429 15902 19539 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@fc2aa9d[FinacleMobileApp]
09-21 21:26:54.582 15902 23848 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
09-21 21:26:54.582 15902 23839 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
09-21 21:26:54.600 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:26:54.625 15902 16067 I System.out: JSONCredInitializer called
09-21 21:26:54.982 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:26:55.014 15902 16067 I System.out: BGColorUpdater === file : true >> Color :true
09-21 21:26:55.026 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:26:55.725 15902 15916 W System  : A resource failed to call end. 
09-21 21:26:56.947 15902 15902 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.
09-21 21:26:56.964 15902 15902 W cr_AwContents: Application attempted to call on a destroyed WebView
09-21 21:26:56.964 15902 15902 W cr_AwContents: java.lang.Throwable
09-21 21:26:56.964 15902 15902 W cr_AwContents: 	at org.chromium.android_webview.AwContents.p(chromium-TrichromeWebViewGoogle.aab-stable-1:2)
09-21 21:26:56.964 15902 15902 W cr_AwContents: 	at vB.loadingStateChanged(chromium-TrichromeWebViewGoogle.aab-stable-1:2)
09-21 21:26:56.964 15902 15902 W cr_AwContents: 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-21 21:26:56.964 15902 15902 W cr_AwContents: 	at android.os.MessageQueue.next(MessageQueue.java:336)
09-21 21:26:56.964 15902 15902 W cr_AwContents: 	at android.os.Looper.loop(Looper.java:174)
09-21 21:26:56.964 15902 15902 W cr_AwContents: 	at android.app.ActivityThread.main(ActivityThread.java:7709)
09-21 21:26:56.964 15902 15902 W cr_AwContents: 	at java.lang.reflect.Method.invoke(Native Method)
09-21 21:26:56.964 15902 15902 W cr_AwContents: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
09-21 21:26:56.964 15902 15902 W cr_AwContents: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-21 21:27:18.152 15902 15902 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5a438c5
09-21 21:27:18.171 15902 15902 I AllTrans: AllTrans: AllTrans: in attachBaseContext of ContextWrapper for package com.BanqueMisr.MobileBanking
09-21 21:27:18.171 15902 15902 I AllTrans: AllTrans: AllTrans: returning because context already not null for package com.BanqueMisr.MobileBanking
09-21 21:27:18.172 15902 15902 I AllTrans: AllTrans: AllTrans: in attachBaseContext of ContextWrapper for package com.BanqueMisr.MobileBanking
09-21 21:27:18.172 15902 15902 I AllTrans: AllTrans: AllTrans: returning because context already not null for package com.BanqueMisr.MobileBanking
09-21 21:27:18.206 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:27:18.207 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:27:18.207 15902 15902 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
09-21 21:27:18.235 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:27:18.236 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:27:18.236 15902 15902 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
09-21 21:27:18.243 15902 16096 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@45df41f[FinacleMobileApp]
09-21 21:27:18.244 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:27:18.344 15902 16096 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@45df41f[FinacleMobileApp]
09-21 21:27:18.374 15902 15902 W Activity: Can request only one set of permissions at a time
09-21 21:27:19.017 15902 16096 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@c0d5283[FinacleMobileApp]
09-21 21:27:19.174 15902 23991 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
09-21 21:27:19.174 15902 24000 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
09-21 21:27:19.195 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:27:19.224 15902 16067 I System.out: JSONCredInitializer called
09-21 21:27:19.760 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:27:19.840 15902 16067 I System.out: BGColorUpdater === file : true >> Color :true
09-21 21:27:19.861 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:27:21.651 15902 15902 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.
09-21 21:27:21.664 15902 15902 W cr_AwContents: Application attempted to call on a destroyed WebView
09-21 21:27:21.664 15902 15902 W cr_AwContents: java.lang.Throwable
09-21 21:27:21.664 15902 15902 W cr_AwContents: 	at org.chromium.android_webview.AwContents.p(chromium-TrichromeWebViewGoogle.aab-stable-1:2)
09-21 21:27:21.664 15902 15902 W cr_AwContents: 	at vB.loadingStateChanged(chromium-TrichromeWebViewGoogle.aab-stable-1:2)
09-21 21:27:21.664 15902 15902 W cr_AwContents: 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-21 21:27:21.664 15902 15902 W cr_AwContents: 	at android.os.MessageQueue.next(MessageQueue.java:336)
09-21 21:27:21.664 15902 15902 W cr_AwContents: 	at android.os.Looper.loop(Looper.java:174)
09-21 21:27:21.664 15902 15902 W cr_AwContents: 	at android.app.ActivityThread.main(ActivityThread.java:7709)
09-21 21:27:21.664 15902 15902 W cr_AwContents: 	at java.lang.reflect.Method.invoke(Native Method)
09-21 21:27:21.664 15902 15902 W cr_AwContents: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
09-21 21:27:21.664 15902 15902 W cr_AwContents: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-21 21:27:26.780 15902 15916 W System  : A resource failed to call end. 
09-21 21:28:31.521 15902 15902 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@55b2ceb
09-21 21:28:31.544 15902 15902 I AllTrans: AllTrans: AllTrans: in attachBaseContext of ContextWrapper for package com.BanqueMisr.MobileBanking
09-21 21:28:31.544 15902 15902 I AllTrans: AllTrans: AllTrans: returning because context already not null for package com.BanqueMisr.MobileBanking
09-21 21:28:31.544 15902 15902 I AllTrans: AllTrans: AllTrans: in attachBaseContext of ContextWrapper for package com.BanqueMisr.MobileBanking
09-21 21:28:31.544 15902 15902 I AllTrans: AllTrans: AllTrans: returning because context already not null for package com.BanqueMisr.MobileBanking
09-21 21:28:31.583 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:28:31.584 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:28:31.584 15902 15902 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
09-21 21:28:31.614 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:28:31.615 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:28:31.615 15902 15902 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
09-21 21:28:31.622 15902 24114 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@a10ffd5[FinacleMobileApp]
09-21 21:28:31.622 15902 15902 I OPFD_Manager: Follow AOSP false
09-21 21:28:31.719 15902 15919 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@a10ffd5[FinacleMobileApp]
09-21 21:28:31.755 15902 15902 W Activity: Can request only one set of permissions at a time
09-21 21:28:32.384 15902 15919 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@b54ad7f[FinacleMobileApp]
09-21 21:28:32.551 15902 24658 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
09-21 21:28:32.551 15902 24664 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
09-21 21:28:32.576 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:28:32.610 15902 16067 I System.out: JSONCredInitializer called
09-21 21:28:33.126 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:28:33.176 15902 16067 I System.out: BGColorUpdater === file : true >> Color :true
09-21 21:28:33.197 15902 16067 I System.out: fingerPrintAvailable@@
09-21 21:28:34.971 15902 15902 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.
09-21 21:28:34.992 15902 15902 W cr_AwContents: Application attempted to call on a destroyed WebView
09-21 21:28:34.992 15902 15902 W cr_AwContents: java.lang.Throwable
09-21 21:28:34.992 15902 15902 W cr_AwContents: 	at org.chromium.android_webview.AwContents.p(chromium-TrichromeWebViewGoogle.aab-stable-1:2)
09-21 21:28:34.992 15902 15902 W cr_AwContents: 	at vB.loadingStateChanged(chromium-TrichromeWebViewGoogle.aab-stable-1:2)
09-21 21:28:34.992 15902 15902 W cr_AwContents: 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-21 21:28:34.992 15902 15902 W cr_AwContents: 	at android.os.MessageQueue.next(MessageQueue.java:336)
09-21 21:28:34.992 15902 15902 W cr_AwContents: 	at android.os.Looper.loop(Looper.java:174)
09-21 21:28:34.992 15902 15902 W cr_AwContents: 	at android.app.ActivityThread.main(ActivityThread.java:7709)
09-21 21:28:34.992 15902 15902 W cr_AwContents: 	at java.lang.reflect.Method.invoke(Native Method)
09-21 21:28:34.992 15902 15902 W cr_AwContents: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
09-21 21:28:34.992 15902 15902 W cr_AwContents: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-21 21:28:35.073 15902 15916 W System  : A resource failed to call end. 
`

What could be the problem 
?

**Comment by SEAL300** [comment]
i have the same problem did you manage to fix it
