### ISSUE TITLE
Magisk Fails to boot with latest canary on Pixel 3 XL

### ISSUE THREAD

**Issue by bylaws** [topjohnwu/Magisk#3266]
This has been happening to me for a while now, on every magisk build since I updated the R DPs (now on release build), after flashing magisk my phone will fail to boot and restart after a minute or two.

[logcat](https://github.com/topjohnwu/Magisk/files/5329920/log.txt)  and boot image can be found [here](https://anonfiles.com/Lf2cD1c2p3/patches_zip).
The fatal error is:
```10-05 21:15:54.425  4997  4997 E System  : ******************************************
10-05 21:15:54.426  4997  4997 E System  : ************ Failure starting system services
10-05 21:15:54.426  4997  4997 E System  : java.lang.IllegalStateException: Missing required shared library:android.ext.shared
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.pm.PackageManagerService.getRequiredSharedLibraryLPr(PackageManagerService.java:3993)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:3549)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2598)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:851)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.SystemServer.run(SystemServer.java:590)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.SystemServer.main(SystemServer.java:408)
10-05 21:15:54.426  4997  4997 E System  :      at java.lang.reflect.Method.invoke(Native Method)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
10-05 21:15:54.426  4997  4997 E Zygote  : System zygote died with exception
10-05 21:15:54.426  4997  4997 E Zygote  : java.lang.IllegalStateException: Missing required shared library:android.ext.shared
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.pm.PackageManagerService.getRequiredSharedLibraryLPr(PackageManagerService.java:3993)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:3549)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2598)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:851)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.SystemServer.run(SystemServer.java:590)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.SystemServer.main(SystemServer.java:408)
10-05 21:15:54.426  4997  4997 E Zygote  :      at java.lang.reflect.Method.invoke(Native Method)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
10-05 21:15:54.426  4997  4997 D AndroidRuntime: Shutting down V```

**Comment by topjohnwu** [comment]
Pixel devices are always supported...
This is either caused by some modules or boot scripts

**Comment by bylaws** [comment]
@topjohnwu I have no nodules nor boot scripts installed, this is a fresh install
