### ISSUE TITLE
What is wrong when su in the termux?

### ISSUE THREAD

**Issue by cecini** [topjohnwu/Magisk#3285]
```
D/Magisk  : su: request from pid=[4960], client=[14]
D/Magisk  : su: request from uid=[10067]
D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
W/WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@f3663c2
W//system/bin/app_process: Unexpected CPU variant for X86 using defaults: x86
I//system/bin/app_process: The ClassLoaderContext is a special shared library.
W/nativebridge: Failed to bind-mount /system/lib/x86/cpuinfo as /proc/cpuinfo: No such file or directory
W//system/bin/app_process: CheckJNI: method to register "write" not in the given class. This is slow, consider changing your RegisterNatives calls.
W//system/bin/app_process: CheckJNI: method to register "write" not in the given class. This is slow, consider changing your RegisterNatives calls.
W//system/bin/app_process: CheckJNI: method to register "write_non_chained" not in the given class. This is slow, consider changing your RegisterNatives calls.
W//system/bin/app_process: CheckJNI: method to register "write_non_chained" not in the given class. This is slow, consider changing your RegisterNatives calls.
D/AndroidRuntime: Calling main entry com.android.commands.am.Am
I/ActivityManager: START u0 {act=android.intent.action.VIEW flg=0x18000020 pkg=com.topjohnwu.magisk cmp=com.topjohnwu.magisk/a.m (has extras)} from uid 0
D/AndroidRuntime: Shutting down VM
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f2108ce
I/opjohnwu.magis: Waiting for a blocking GC ProfileSaver
E/SuRequestHandler$init: com.topjohnwu.magisk.core.su.SuRequestHandler$SuRequestError
E/SuRequestHandler$init: 	at com.topjohnwu.magisk.core.su.SuRequestHandler$init$2.invokeSuspend(SuRequestHandler.kt:75)
E/SuRequestHandler$init: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/SuRequestHandler$init: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/SuRequestHandler$init: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
E/SuRequestHandler$init: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
E/SuRequestHandler$init: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
E/SuRequestHandler$init: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by cecini** [comment]
But if in adb shell, su ok!

**Comment by zgfg** [comment]
CPU variant for X86?
![Screenshot_2020-10-07-15-12-57-451_com termux](https://user-images.githubusercontent.com/51943147/95335667-f7863980-08af-11eb-8fcd-3f97c9a127c1.jpg)

**Comment by cecini** [comment]
> You have some error: CPU variant for X86?
> ![Screenshot_2020-10-07-15-12-57-451_com termux](https://user-images.githubusercontent.com/51943147/95335667-f7863980-08af-11eb-8fcd-3f97c9a127c1.jpg)

This should not be the error. I am in the x86 android 9 emulator.

**Comment by cecini** [comment]
found the issue.
change the config.prop 
# The version name and version code of Magisk
version=20.5
versionCode=21200

# The version name and version code of Magisk Manager
appVersion=7.5.2
appVersionCode=21200

to use the fifo. 
[Use FIFO for su request communication](https://github.com/topjohnwu/Magisk/commit/434efec8607103d4b85390d72b2b56d5b523729e)
