### ISSUE TITLE
MM crash when try open "modules" without internet connection (310)

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#3344]
```
10-14 20:52:16.014  3248  3248 I NavController: Ignoring popBackStack to destination com.topjohnwu.magisk:id/modulesFragment as it was not found on the current back stack
10-14 20:52:16.376  3248 12819 D OkHttp  : --> GET https://magisk-modules-repo.github.io/submission/modules.json
10-14 20:52:16.380  3248 12819 D OkHttp  : <-- HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "magisk-modules-repo.github.io": No address associated with hostname
10-14 20:52:16.577  3248  3248 E App     : java.net.UnknownHostException: Unable to resolve host "magisk-modules-repo.github.io": No address associated with hostname
10-14 20:52:16.577  3248  3248 E App     : 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
10-14 20:52:16.577  3248  3248 E App     : 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
10-14 20:52:16.577  3248  3248 E App     : 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.Dns$1.lookup(Dns.java:40)
10-14 20:52:16.577  3248  3248 E App     : 	at com.topjohnwu.magisk.di.DnsResolver.lookup(NetworkingModule.kt:68)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
10-14 20:52:16.577  3248  3248 E App     : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
10-14 20:52:16.577  3248  3248 E App     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-14 20:52:16.577  3248  3248 E App     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-14 20:52:16.577  3248  3248 E App     : 	at java.lang.Thread.run(Thread.java:919)
10-14 20:52:16.577  3248  3248 E App     : Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
10-14 20:52:16.577  3248  3248 E App     : 	at libcore.io.Linux.android_getaddrinfo(Native Method)
10-14 20:52:16.577  3248  3248 E App     : 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
10-14 20:52:16.577  3248  3248 E App     : 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
10-14 20:52:16.577  3248  3248 E App     : 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
10-14 20:52:16.577  3248  3248 E App     : 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
10-14 20:52:16.577  3248  3248 E App     : 	... 30 more
10-14 20:52:16.579  3248  3248 I mwszfy.p.i.u.b: System.exit called, status: 1
```
Full log here: [log.txt](https://github.com/topjohnwu/Magisk/files/5379998/log.txt)

**Comment by zgfg** [comment]
Also: Close Manager, long tap to the icon and take Modules.
You can shortly see Online on the screen before it crashes

The app is still in the background, bring it to foreground, you can again shortly see Online on the screen before crashing

It wrongly thinks it's online and it tries to resolve the repo URL (as in the log above), it can't and it crashes

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/pull/3351/commits/16d9b85d8544ded439e7f5dda1d46c07eb722d28
