### ISSUE TITLE
Magisk Fails to boot with latest canary on my specific Pixel 3 XL

### ISSUE THREAD

**Issue by bylaws** [topjohnwu/Magisk#3355]
- recreating as I have no modules nor bootscripts installed - i have run `magisk --remove-modules` in the shell  
This has been happening to me for a while now, on every magisk build since I updated the R DPs (now on release build), after flashing magisk my phone will fail to boot and restart after a minute or two.

[logcat](https://github.com/topjohnwu/Magisk/files/5329920/log.txt)  and boot image can be found [here](https://anonfiles.com/Lf2cD1c2p3/patches_zip).
The fatal error is:
```10-05 21:15:54.425  4997  4997 E System  : ******************************************
10-05 21:15:54.426  4997  4997 E System  : ************ Failure starting system services
10-05 21:15:54.426  4997  4997 E System  : java.lang.IllegalStateException: Missing required shared library:android.ext.shared
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.pm.PackageManagerService.getRequiredSharedLibraryLPr(PackageManagerService.java:3993)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:3549)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2598)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:851)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.SystemServer.run(SystemServer.java:590)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.server.SystemServer.main(SystemServer.java:408)
10-05 21:15:54.426  4997  4997 E System  :      at java.lang.reflect.Method.invoke(Native Method)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-05 21:15:54.426  4997  4997 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
10-05 21:15:54.426  4997  4997 E Zygote  : System zygote died with exception
10-05 21:15:54.426  4997  4997 E Zygote  : java.lang.IllegalStateException: Missing required shared library:android.ext.shared
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.pm.PackageManagerService.getRequiredSharedLibraryLPr(PackageManagerService.java:3993)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:3549)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2598)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:851)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.SystemServer.run(SystemServer.java:590)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.server.SystemServer.main(SystemServer.java:408)
10-05 21:15:54.426  4997  4997 E Zygote  :      at java.lang.reflect.Method.invoke(Native Method)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-05 21:15:54.426  4997  4997 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
10-05 21:15:54.426  4997  4997 D AndroidRuntime: Shutting down V```

**Comment by bylaws** [comment]
Looking further into it it seems to just forget about several packages

```
10-15 19:12:43.060  1452  1452 W PackageManager: Destroying /data/user_de/0/com.google.android.ext.shared due to: com.android.server.pm.PackageManagerException: Package com.google.android.ext.shared is unknown
10-15 19:12:43.062  1132  1132 I ServiceManager: Waiting for service 'package_native' on '/dev/binder'...
10-15 19:12:43.068   646  1390 D libnos_transport: App 0 poll=64 status=0x00000000 reply_len=0 flags=0x0001
10-15 19:12:43.071  1452  1452 W PackageManager: Destroying /data/user_de/0/com.qualcomm.qti.uceShimService due to: com.android.server.pm.PackageManagerException: Package com.qualcomm.qti.uceShimService is unknown
10-15 19:12:43.071  1149  1149 I ServiceManager: Waiting for service 'package_native' on '/dev/binder'...
10-15 19:12:43.072  1452  1452 W PackageManager: Destroying /data/user_de/0/com.qualcomm.qti.telephonyservice due to: com.android.server.pm.PackageManagerException: Package com.qualcomm.qti.telephonyservice is unknown
10-15 19:12:43.073  1452  1452 W PackageManager: Destroying /data/user_de/0/org.codeaurora.ims due to: com.android.server.pm.PackageManagerException: Package org.codeaurora.ims is unknown
10-15 19:12:43.074  1452  1452 W PackageManager: Destroying /data/user_de/0/com.android.service.ims due to: com.android.server.pm.PackageManagerException: Package com.android.service.ims is unknown
10-15 19:12:43.076  1452  1452 W PackageManager: Destroying /data/user_de/0/com.android.service.ims.presence due to: com.android.server.pm.PackageManagerException: Package com.android.service.ims.presence is unknown
10-15 19:12:43.077  1452  1452 W PackageManager: Destroying /data/user_de/0/com.vzw.apnlib due to: com.android.server.pm.PackageManagerException: Package com.vzw.apnlib is unknown
10-15 19:12:43.079  1452  1452 W PackageManager: Destroying /data/user_de/0/com.google.android.apps.diagnosticstool due to: com.android.server.pm.PackageManagerException: Package com.google.android.apps.diagnosticstool is unknown
10-15 19:12:43.080  1452  1452 W PackageManager: Destroying /data/user_de/0/com.android.htmlviewer due to: com.android.server.pm.PackageManagerException: Package com.android.htmlviewer is unknown
10-15 19:12:43.082  1452  1452 W PackageManager: Destroying /data/user_de/0/com.google.android.apps.enterprise.dmagent due to: com.android.server.pm.PackageManagerException: Package com.google.android.apps.enterprise.dmagent is unknown
10-15 19:12:43.083  1452  1452 W PackageManager: Destroying /data/user_de/0/com.android.companiondevicemanager due to: com.android.server.pm.PackageManagerException: Package com.android.companiondevicemanager is unknown
10-15 19:12:43.084  1452  1452 W PackageManager: Destroying /data/user_de/0/com.breel.wallpapers18 due to: com.android.server.pm.PackageManagerException: Package com.breel.wallpapers18 is unknown
10-15 19:12:43.086  1452  1452 W PackageManager: Destroying /data/user_de/0/com.android.pacprocessor due to: com.android.server.pm.PackageManagerException: Package com.android.pacprocessor is unknown
10-15 19:12:43.087   646  1390 D libnos_transport: App 0 polled=73 status=0x80000000 reply_len=0 flags=0x0000
10-15 19:12:43.088  1452  1452 W PackageManager: Destroying /data/user_de/0/com.android.simappdialog due to: com.android.server.pm.PackageManagerException: Package com.android.simappdialog is unknown
10-15 19:12:43.088   646  1390 D libnos_transport: App 0 returning 0x0
10-15 19:12:43.088   646  1390 D libnos_transport: Calling app 0 with params 0x0001
10-15 19:12:43.089  1452  1452 W PackageManager: Destroying /data/user_de/0/android.autoinstalls.config.google.nexus due to: com.android.server.pm.PackageManagerException: Package andr```

**Comment by topjohnwu** [comment]
This means some incompatible modules has polluted the data partition or there is still incompatible module installed

**Comment by bylaws** [comment]
How would I uninstall them modules?
