### ISSUE TITLE
[Bug] Can't install certain apps (app bundles?) on Android 11 Pixel 4 with Magisk (Beta 21.0 & Latest Canary)

### ISSUE THREAD

**Issue by Jolanrensen** [topjohnwu/Magisk#3397]
Like the title says. Using both the latest Canary (can't remember the version but it is the latest as of today, 22-9) and beta 21.0 I can't install certain apps including Chrome, Chrome beta, KTweak and some others. Apps like Firefox install fine, which is way I suspect app bundles are the culprit. It might also be that Magisk is corrupting/hiding a certain library which those apps need though. What's even more curious is that Chrome (a system app) even disappeared from the phone altogether and it took uninstalling Magisk for it to appear again.

**Comment by yukosky** [comment]
Try install with `pm install` command (with su) and send the output

**Comment by Jolanrensen** [comment]
The result using adb install: 
```
adb install '/mnt/SSD/Downloads/ktweak.apk' 
Performing Streamed Install
adb: failed to install /mnt/SSD/Downloads/ktweak.apk: Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]
```

and the result using su pm install (is similar without su btw):
```
coral:/mnt/sdcard/Download # pm install ./ktweak.apk                                                   
avc:  denied  { read } for  scontext=u:r:system_server:s0 tcontext=u:object_r:fuse:s0 tclass=file permissive=0
System server has no access to read file context u:object_r:fuse:s0 (from path /storage/emulated/0/Download/./ktweak.apk, context u:r:system_server:s0)
Error: Unable to open file: ./ktweak.apk
Consider using a file under /data/local/tmp/
Error: Can't open file: ./ktweak.apk

Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Can't open file: ./ktweak.apk
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:519)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1282)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1248)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:184)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21605)
	at android.os.Binder.shellCommand(Binder.java:929)
	at android.os.Binder.onTransact(Binder.java:813)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4603)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4306)
	at android.os.Binder.execTransactInternal(Binder.java:1159)
	at android.os.Binder.execTransact(Binder.java:1123)
```

**Comment by Jolanrensen** [comment]
Actually, I've narrowed down the issue to a [specific module](https://forum.xda-developers.com/pixel-4-xl/themes/magisk-ambient-eq-tweak-flame-t4113833) and it's even a known issue in that thread, so I'm closing the issue!
