### ISSUE TITLE
hide magisk manager crashes with 400 bad request

### ISSUE THREAD

**Issue by joske** [topjohnwu/Magisk#3440]
I'm trying to hide magisk manager canary 311 on android 11 ROM (need it because my banking apps don't work otherwise - apparently it's looking for magisk in the apps list). It's crashing everytime when I try that:

```11-01 20:55:15.509 19698 20022 D OkHttp  : --> GET https://raw.githubusercontent.com/stub-release.apk
11-01 20:55:15.511 19698 19721 D OpenGLRenderer: endAllActiveAnimators on 0x6f58c5b2b0 (RippleDrawable) with handle 0x6e78bde8a0
11-01 20:55:15.560  2932  2932 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.wallet.service.BIND pkg=com.google.android.gms }
11-01 20:55:15.629 19698 20022 D OkHttp  : <-- 400 Bad Request https://raw.githubusercontent.com/stub-release.apk (119ms, 20-byte body)
11-01 20:55:15.664 19698 19724 E App     : retrofit2.HttpException: HTTP 400 Bad Request
11-01 20:55:15.664 19698 19724 E App     : 	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
11-01 20:55:15.664 19698 19724 E App     : 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
11-01 20:55:15.664 19698 19724 E App     : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
11-01 20:55:15.664 19698 19724 E App     : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
11-01 20:55:15.664 19698 19724 E App     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-01 20:55:15.664 19698 19724 E App     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-01 20:55:15.664 19698 19724 E App     : 	at java.lang.Thread.run(Thread.java:923)
11-01 20:55:15.665 19698 19724 I opjohnwu.magis: System.exit called, status: 1
11-01 20:55:15.665 19698 19724 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
11-01 20:55:15.675   779   779 I Zygote  : Process 19698 exited cleanly (1)
```

**Comment by joske** [comment]
[logcat.txt](https://github.com/topjohnwu/Magisk/files/5477849/logcat.txt)

**Comment by joske** [comment]
I found the following workaround, cloned the repo, build the apk, with that version I was able to hide the manager, then upgrade to latest canary and still hidden. :-)
