### ISSUE TITLE
Hide manager failed - unsupported signature algorithm (?)

### ISSUE THREAD

**Issue by Arkq** [topjohnwu/Magisk#3513]
Logcat shows something like this:

```
11-22 21:02:56.586  3100  3818 I SendBroadcastPermission: action:android.intent.action.SIG_STR, mPermissionType:0
11-22 21:02:56.590  3446  3501 I HwCustMobileSignalControllerImpl: subId:0 phoneType:1 networktype:13 targetClass:3 masterLevel:3 slaveLevel:-1
11-22 21:02:57.885 15870 15889 I art     : Note: end time exceeds epoch: 
11-22 21:02:57.933 15870 15889 E tr0     : java.lang.IllegalArgumentException: unsupported signature algorithm "SHA1WITHRSAENCRYPTION" in cert [CN=Android, OU=Android, O=Google Inc., L=Mountain View, ST=California, C=US
11-22 21:02:57.933 15870 15889 E tr0     : 	at id1.a(Unknown Source)
11-22 21:02:57.933 15870 15889 E tr0     : 	at id1.c(Unknown Source)
11-22 21:02:57.933 15870 15889 E tr0     : 	at tr0.b(Unknown Source)
11-22 21:02:57.933 15870 15889 E tr0     : 	at tr0.c(Unknown Source)
11-22 21:02:57.933 15870 15889 E tr0     : 	at or0.k(Unknown Source)
11-22 21:02:57.933 15870 15889 E tr0     : 	at kp1.e(Unknown Source)
11-22 21:02:57.933 15870 15889 E tr0     : 	at su1.run(Unknown Source)
11-22 21:02:57.933 15870 15889 E tr0     : 	at zx1.N(Unknown Source)
11-22 21:02:57.933 15870 15889 E tr0     : 	at xx1.run(Unknown Source)
11-22 21:02:57.981  2490  3067 I [Gralloc]: alloc w[420] h[82] format[1] usage[3842]
11-22 21:02:57.982  2490  3067 I [Gralloc]: alloc succ handle[0x558af31c70] stride[420]
11-22 21:02:57.984  2490  4023 I [Gralloc]: alloc w[420] h[82] format[1] usage[3842]
```

Running stock firmware for Huawei P8:
```
$ getprop ro.build.version.release                             
6.0
$ getprop ro.build.version.sdk                                 
23
```

Magisk - 20.4
Magisk Manager - 8.0.3

**Comment by vvb2060** [comment]
> end time exceeds epoch

**Comment by Arkq** [comment]
It has turned out the the problem was with a too old version of Google Play Services in the stock firmware - 8.3.01 (2385995-440). After upgrading it, Magisk Manager is able to repack itself (also SafetyNet attestation works as expected; with stock Play Services I've got SafetyNet API error). For the record, for me it works with Google Play Services version 16.0.91. With the newest Google Play Services it works as well. I haven't checked which is the earliest version possible, though.
