### ISSUE TITLE
UnsatisfiedLinkError couldn't find native library which by magic mount

### ISSUE THREAD

**Issue by gam2046** [topjohnwu/Magisk#3558]
#### Magisk Module

```
│  module.prop
│
├─META-INF
│  └─com
│      └─google
│          └─android
│                  update-binary
│                  updater-script
│
└─system
    └─etc
            public.libraries.txt < -- contains 'libtest.so'
    └─lib
            libtest.so
```

I tried to load the native library(`System.loadLibrary("test");`) in the application and got this error message
```
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader couldn't find "libtest.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
```

I tried this code again:

```java
        File[] fs = new File[]{
                new File("/system/lib/libtest.so"),
                new File("/system/lib/libshell.so"),
                new File("/system/lib/libc.so")

        };

        for (File f : fs) {
            Log.d(TAG, f.getName() + " >>JNI Exists:" + f.exists());
            Log.d(TAG, f.getName() + " >>JNI Readable:" + f.canRead());
            Log.d(TAG, f.getName() + " >>JNI Executable:" + f.canExecute());
        }
```

Outputs:

```
2020-12-08 16:55:24.288 6941-7193/? D/ABABC: librtmp-jni.so >>JNI Exists:false
2020-12-08 16:55:24.288 6941-7193/? D/ABABC: librtmp-jni.so >>JNI Readable:false
2020-12-08 16:55:24.288 6941-7193/? D/ABABC: librtmp-jni.so >>JNI Executable:false
2020-12-08 16:55:24.289 6941-7193/? D/ABABC: libshell.so >>JNI Exists:true
2020-12-08 16:55:24.289 6941-7193/? D/ABABC: libshell.so >>JNI Readable:true
2020-12-08 16:55:24.289 6941-7193/? D/ABABC: libshell.so >>JNI Executable:false
2020-12-08 16:55:24.289 6941-7193/? D/ABABC: libc.so >>JNI Exists:true
2020-12-08 16:55:24.289 6941-7193/? D/ABABC: libc.so >>JNI Readable:true
2020-12-08 16:55:24.289 6941-7193/? D/ABABC: libc.so >>JNI Executable:false
```

Amazingly, it seems that the file mounted by MagickMount does not exist. Then I confirmed again through adb shell that the file does exist and that there is no problem with permissions. At the same time, SELinux related logs are not output in Logcat.

```
$ ls -Zl /system/lib/libshell.so
-rw-r--r-- 1 root root u:object_r:system_file:s0 37220 2009-01-01 00:00 /system/lib/libshell.so
$ ls -Zl /system/lib/libtest.so
-rw-r--r-- 1 root root u:object_r:system_file:s0 9764 2020-12-08 16:53 /system/lib/libtest.so
```

So what could be the cause?

- ro.build.version.sdk: 28
- Magisk: 21.1 (21100)
- Magisk Manager: 8.0.3(314)

**Comment by unixandria-xda** [comment]
Have you made sure the library is correctly in `$LD_LIBRARY_PATH`?

**Comment by unixandria-xda** [comment]
Also the correct selinux context should be `u:object_r:system_lib_file:s0`

**Comment by topjohnwu** [comment]
@gam2046 what the issue actually is should be what @unixandria-xda said here
