### ISSUE TITLE
Youtube crashes after update to 21.4

### ISSUE THREAD

**Issue by vasyl91** [topjohnwu/Magisk#3793]
After updating Magisk, Youtube crashes right after I try to open video or few seconds after sliding down/switching tabs.

```
time: 1611909819469
msg: java.lang.IllegalArgumentException: Remote stack trace:
	at com.android.server.media.MediaSessionService.enforcePackageName(MediaSessionService.java:490)
	at com.android.server.media.MediaSessionService.access$2100(MediaSessionService.java:104)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.createSession(MediaSessionService.java:1012)
	at android.media.session.ISessionManager$Stub.onTransact(ISessionManager.java:239)
	at android.os.Binder.execTransactInternal(Binder.java:1021)

stacktrace: java.lang.IllegalArgumentException: packageName is not owned by the calling process
	at android.os.Parcel.createException(Parcel.java:2075)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.media.session.ISessionManager$Stub$Proxy.createSession(ISessionManager.java:558)
	at android.media.session.MediaSessionManager.createSession(MediaSessionManager.java:114)
	at android.media.session.MediaSession.<init>(MediaSession.java:194)
	at kj.<init>(PG:8)
	at aoxs.get(Unknown Source:1)
	at aoxu.g(PG:1)
	at aoxu.f(PG:2)
	at amkw.b(PG:1)
	at dnk.f(PG:32)
	at dnk.get(PG:276)
	at poe.kj(PG:3)
	at acea.a(PG:4)
	at acds.run(PG:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.media.MediaSessionService.enforcePackageName(MediaSessionService.java:490)
	at com.android.server.media.MediaSessionService.access$2100(MediaSessionService.java:104)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.createSession(MediaSessionService.java:1012)
	at android.media.session.ISessionManager$Stub.onTransact(ISessionManager.java:239)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
```

Similar issue was with browser after an update month ago (found workaround that doesn't seem to work with youtube)

**Comment by topjohnwu** [comment]
This has 100% nothing to do with Magisk. Please see if any modules has caused this
