### ISSUE TITLE
Magisk Manager won't load after hiding with different package name

### ISSUE THREAD

**Issue by mew1033** [topjohnwu/Magisk#3863]
I'm having the exact same issue described in #3822. I think I got a logcat of the crash, here's what I have:

```
PS C:\Users\Chandler\Desktop> adb logcat -e "magisk"
--------- beginning of main
--------- beginning of system
02-16 15:09:19.663  2303  2303 E ActivityThread: Failed to find provider info for com.topjohnwu.magisk.provider
02-16 15:09:19.664  2303  2303 E j       : java.io.FileNotFoundException: No content provider: content://com.topjohnwu.magisk.provider/apk_file
02-16 15:09:19.664  2303  2303 E j       :      at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1969)
02-16 15:09:19.664  2303  2303 E j       :      at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
02-16 15:09:19.664  2303  2303 E j       :      at android.content.ContentResolver.openInputStream(ContentResolver.java:1475)
02-16 15:09:19.664  2303  2303 E j       :      at j.E(Unknown Source:3)
02-16 15:09:19.664  2303  2303 E j       :      at r.attachBaseContext(Unknown Source:3)
02-16 15:09:19.664  2303  2303 E j       :      at android.app.Application.attach(Application.java:351)
02-16 15:09:19.664  2303  2303 E j       :      at android.app.Instrumentation.newApplication(Instrumentation.java:1159)
02-16 15:09:19.664  2303  2303 E j       :      at android.app.LoadedApk.makeApplication(LoadedApk.java:1260)
02-16 15:09:19.664  2303  2303 E j       :      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6686)
02-16 15:09:19.664  2303  2303 E j       :      at android.app.ActivityThread.access$1300(ActivityThread.java:237)
02-16 15:09:19.664  2303  2303 E j       :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
02-16 15:09:19.664  2303  2303 E j       :      at android.os.Handler.dispatchMessage(Handler.java:106)
02-16 15:09:19.664  2303  2303 E j       :      at android.os.Looper.loop(Looper.java:223)
02-16 15:09:19.664  2303  2303 E j       :      at android.app.ActivityThread.main(ActivityThread.java:7660)
02-16 15:09:19.664  2303  2303 E j       :      at java.lang.reflect.Method.invoke(Native Method)
02-16 15:09:19.664  2303  2303 E j       :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-16 15:09:19.664  2303  2303 E j       :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
Let me know if you need different logs.

**Comment by Haus3master** [comment]
I'm quite sure that this was fixed in the latest canary update, I wasn't able to recreate this issue on any of my devices running canary, I even downgraded my canary manager and updated it again, and still wasn't able to recreate this issue...
