### ISSUE TITLE
Magisk Manager crashes with OutOfMemoryError while patching boot.img

### ISSUE THREAD

**Issue by emanuele-f** [topjohnwu/Magisk#3876]
Magisk Manager crashes while trying to patch boot.img of SM-G531F. The crash occurs after the `Copying image to cache` message is displayed in the gui.

Magisk version: canary b76c80e2 (21410), also tried with v21.4

Logcat:
```
2021-02-20 18:39:00.801 16261-16261/com.topjohnwu.magisk E/App: java.lang.OutOfMemoryError: Failed to allocate a 452984848 byte allocation with 12582912 free bytes and 379MB until OOM, max allowed footprint 17288384, growth limit 402653184
        at java.util.Arrays.copyOf(Arrays.java:3164)
        at com.topjohnwu.signing.SignBoot.verifySignature(SignBoot.java:153)
        at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchBoot(MagiskInstaller.kt:329)
        at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:286)
        at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.doPatchFile(MagiskInstaller.kt:404)
        at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:442)
        at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$2.invokeSuspend(MagiskInstaller.kt:418)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-02-20 18:39:00.872 1285-1421/? E/InputDispatcher: channel '765872 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-02-20 18:39:00.993 1738-11409/? E/DollieAdapterService: notifyActivityState pkg:com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity state:18 fg:false mUid:10256
```

boot.img: [boot.img.zip](https://github.com/topjohnwu/Magisk/files/6015917/boot.img.zip)

**Comment by osm0sis** [comment]
Looks like normal AOSP-PXA format boot.img, must just be the new signboot implementation doesn't like it.

**Comment by emanuele-f** [comment]
Which old version properly supports it?

**Comment by osm0sis** [comment]
The one before the APK and zip got merged.

**Comment by emanuele-f** [comment]
I'm not involved in the development, do you know the version number?

**Comment by pndwal** [comment]
That would be 21401 (synced w/ public 21.4).
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-84311777

21402 was first w/ Magisk and Magisk Manager merged.
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-84354959

PW

**Comment by osm0sis** [comment]
Looks like the signing changes were made on Dec. 26, so the last build before that was actually 21102. That might not actually be the breaking change though, since lots of things have happened with the apk between then and now.

If you could work your way back in the canaries and tell us the last which works for your device that would be very helpful to try and fix it.

**Comment by emanuele-f** [comment]
Thanks for the info, however the issue is older. I took the time to go back in revisions by inspecting the SignBoot.java changes. This was quite painful because the app requires you to update to the latest version. Please fix this behavior and do not assume that a user will install the latest version or even that the update check will work! Otherwise all the old apks becomes useless.

Nevertheless, the bug was introduced in 8e348a11c26270397ab2ccd38b5b45e8c79f4fc2 . Reverting it with this patch on the current master works for me (of course this should be fixed properly):

```diff
diff --git a/app/src/main/java/com/topjohnwu/signing/SignBoot.java b/app/src/main/java/com/topjohnwu/signing/SignBoot.java
index 38f008f8..f32ded53 100644
--- a/app/src/main/java/com/topjohnwu/signing/SignBoot.java
+++ b/app/src/main/java/com/topjohnwu/signing/SignBoot.java
@@ -201,7 +201,7 @@ public class SignBoot {
                 + ((ramdskSize + pageSize - 1) / pageSize) * pageSize
                 + ((secondSize + pageSize - 1) / pageSize) * pageSize;
         int headerVersion = image.getInt(); // boot image header version or dt/extra size
-        if (headerVersion > 0 && headerVersion < BOOT_IMAGE_HEADER_VERSION_MAXIMUM) {
+        if (headerVersion > 0) {
             image.position(BOOT_IMAGE_HEADER_V1_RECOVERY_DTBO_SIZE_OFFSET);
             int recoveryDtboLength = image.getInt();
             length += ((recoveryDtboLength + pageSize - 1) / pageSize) * pageSize;
@@ -217,9 +217,6 @@ public class SignBoot {
                 throw new IllegalArgumentException(
                         "Invalid image header: invalid header length");
             }
-        } else {
-            // headerVersion is 0 or actually dt/extra size in this case
-            length += ((headerVersion + pageSize - 1) / pageSize) * pageSize;
         }
         length = ((length + pageSize - 1) / pageSize) * pageSize;
         if (length <= 0) {
```

Please note that you can test the image patching with your own device, you don't need the SM-G531F, which is the same thing I'm doing right now.

**Comment by osm0sis** [comment]
It's just not failing correctly anymore; it would always fail with AOSP-PXA format, that's expected, just not fail that way and definitely not take down the whole app.

**Comment by emanuele-f** [comment]
Are you only referring to the current master, right? The pre-21102 releases are expected to work? By the way, I will try to flash the image generated by Magisk Manger v7.3.2 (the release before the 8e348a1 commit) as it seems a safer option right now.

**Comment by topjohnwu** [comment]
@osm0sis PXA boot images will make page size larger than `0x02000000`, which of course breaks stuff

**Comment by osm0sis** [comment]
Yeah, but that's always been the case and it used to fail more gracefully.
