### ISSUE TITLE
v22.0 does not support

### ISSUE THREAD

**Issue by E7KMbb** [topjohnwu/Magisk#3927]
LG v30
Android9
Official system
![Screenshot_20210225-085905](https://user-images.githubusercontent.com/34418195/109087348-4261fa00-7748-11eb-8dc4-ebbc62390007.png)

**Comment by Shivelight** [comment]
I have the same problem, flashing from recovery yield out the same error.

```***********************
 Magisk 22.0 Installer 
***********************
- Mounting /system
- Mounting /vendor
- Device is system-as-root
- Mounting /apex/com.android.conscrypt
- Mounting /apex/com.android.media
- Mounting /apex/com.android.media.swcodec
- Mounting /apex/com.android.resolv
- Mounting /apex/com.android.runtime
- Mounting /apex/com.android.tzdata
- System-as-root, keep dm/avb-verity
CANNOT LINK EXECUTABLE "getprop": cannot locate symbol "__loader_shared_globals" referenced by "/apex/com.android.runtime/lib64/bionic/libc.so"...
linker: CANNOT LINK EXECUTABLE "getprop": cannot locate symbol "__loader_shared_globals" referenced by "/apex/com.android.runtime/lib64/bionic/libc.so"...
- Target image: /dev/block/mmcblk0p21
- Device platform: arm64
- Constructing environment
- Adding addon.d survival script
java.lang.IllegalArgumentException: Invalid image header: missing magic
	at com.topjohnwu.signing.SignBoot.getSignableImageSize(Unknown Source:176)
	at com.topjohnwu.signing.SignBoot.verifySignature(Unknown Source:19)
	at com.topjohnwu.signing.SignBoot.main(Unknown Source:33)
- Unpacking boot image
Parsing boot image: [/dev/block/mmcblk0p21]
! Unsupported/Unknown image format
- Unmounting partitions
Updater process ended with ERROR: 1
I:OrangeFox: installed standard zip: /sdcard/Download/Magisk-v22.0.zip
I:flash_zip: installer code = 0
Error installing ZIP file '/sdcard/Download/Magisk-v22.0.zip'
```

Android 10
Redmi 5 Plus (vince)
AICP q-15.0-WEEKLY-20210212

**Comment by popy2k14** [comment]
Guys, DO NOT reboot. it soft bricked my and other Oneplus 6Ts.
See here: https://github.com/topjohnwu/Magisk/issues/3924

**Comment by topjohnwu** [comment]
@E7KMbb please upload your boot image

**Comment by E7KMbb** [comment]
@popy2k14 Okay, but my problem has been solved, something changed my kernel, and it was solved when I re-flashed the kernel

**Comment by E7KMbb** [comment]
@topjohnwu My problem has been solved, something changed my kernel, and it was solved when I flashed the kernel again
