### ISSUE TITLE
Magisk 22.+ not detected by Manager, but SU still working on Android 6.0 Marshmallow with Samsung Note 4 SM-N910F TouchWiz, armeabi-v7a

### ISSUE THREAD

**Issue by leppit** [topjohnwu/Magisk#4173]
Device: Samsung Note 4, SM-N910F, armeabi-v7a
Android version: Android 6.0, Marshmallow,
Magisk version name: 22101 (20), (all 22+)
Magisk version code: f623b988 

UI: TouchWiz
Recovery: TWRP

Issue 1: Magisk (Manager) does not install/patch within the app, creating that signature error
Issue 2: Magisk (Manager) does not detect patched Magisk, shows only n/a
Issue 3: Magisk (Manager) wants to install current Manager though it is installed
Issue 4: Magisk (Manager) does not offer all features to control SU, hide, etc., though Magisk is patched and SU requests working

Done so far without solving the problem:

    uninstalled/reinstalled Manager
    unpatched/repatched stock boot via TWRP
    repatched Magisk boot-image via TWRP (no self-patched boot.img - ask, if I shall try to retrieve it)

The terminal-emulator can run magisk -v (->f623b988) or magisk -V (->) correctly.

Last Version without these Issues:
Magisk 8.0.7 (pre 22)

Please let me know, what additional infromation is needed and how to access, if necessary, before closing the threat.

PS: I followed for the logs this guide
https://didgeridoohan.com/magisk/MagiskHelp

Logs:

1) Excerpt of attached Magisk_install_log (/download):
[magisk_install_log_2021-04-09T164405Z.log](https://github.com/topjohnwu/Magisk/files/6286606/magisk_install_log_2021-04-09T164405Z.log)

- Target image: /dev/block/
- Device platform: armeabi-v7a
- Installing: f623b988 (22101)
! Unable to check signature
! Installation failed

2) Excerpt of attached magisk.log (/cache):
[magisk.log](https://github.com/topjohnwu/Magisk/files/6286587/magisk.log)

02-06 22:26:21.519   373   373 I : Magisk f623b988(22101) daemon started
 02-06 22:26:21.526   373   373 I : * Device API level: 23
 02-06 22:26:21.531   373   375 D : resetprop: getprop [ro.crypto.state]: [unencrypted]
 02-06 22:26:21.532   373   375 I : ** post-fs-data mode running
 02-06 22:26:21.533   373   375 I : * Mounting mirrors
 02-06 22:26:21.534   373   375 I : mount: /sbin/.magisk/mirror/system
 02-06 22:26:21.534   373   375 I : mount: /sbin/.magisk/mirror/data
 02-06 22:26:21.534   373   375 I : link: /sbin/.magisk/mirror/cache
 02-06 22:26:21.534   373   375 I : link: /sbin/.magisk/mirror/persist
 02-06 22:26:21.534   373   375 I : link: /sbin/.magisk/mirror/vendor
 02-06 22:26:21.534   373   375 I : * Initializing Magisk environment
 02-06 22:26:21.747   373   375 D : resetprop: prop [persist.sys.safemode] does not exist
 02-06 22:26:25.069   373   375 I : * Running post-fs-data.d scripts
 02-06 22:26:25.075   373   375 D : bind_mnt: /sbin/.magisk/modules <- /sbin/.magisk/mirror/data/adb/modules
 02-06 22:26:25.077   373   375 I : * Running module post-fs-data scripts
 02-06 22:26:25.077   373   375 I : * Loading modules
 02-06 23:26:27.343   373   734 I : ** late_start service mode running
 02-06 23:26:27.379   373   734 I : * Running service.d scripts
 02-06 23:26:27.379   373   734 I : * Running module service scripts
 04-09 16:39:18.193   373  5364 I : ** boot_complete triggered
 04-09 16:43:43.161   373 11689 D : su: request from pid=[11685], client=[16]
 04-09 16:43:43.165   373 11689 D : su: request from uid=[10269]
 04-09 16:43:43.165   373 11689 D : su: waiting child pid=[11690]
 04-09 16:43:43.165 11690 11690 D : su: fork handler
 04-09 16:43:43.166 11690 11690 D : su: use global namespace
 04-09 16:45:35.416   373 12539 D : su: request from pid=[12534], client=[17]
 04-09 16:45:35.417   373 12539 D : su: request from uid=[10295]
 04-09 16:45:39.651   373 12539 D : su: waiting child pid=[12566]
 04-09 16:45:39.651 12566 12566 D : su: fork handler
 04-09 16:45:39.653 12566 12566 D : su: use namespace of pid=[12534]
 04-09 16:45:53.548   373 12848 D : su: request from pid=[12845], client=[18]
 04-09 16:45:53.548   373 12848 D : su: request from uid=[10295]
 04-09 16:45:57.262   373 12848 D : su: waiting child pid=[12896]
 04-09 16:45:57.262 12896 12896 D : su: fork handler
 04-09 16:45:57.263 12896 12896 D : su: use namespace of pid=[12845]

3) Excerpt of TWRP Recovery last.log (cache/recovery):
[last_log.log](https://github.com/topjohnwu/Magisk/files/6286653/last_log.log)

I:Set page: 'install'
I:Set page: 'flash_confirm'
I:Set page: 'flash_zip'
I:operation_start: 'Flashing'
Installiere Zip '/sdcard/Download/magisk/Magisk-f623b988(22101).zip'
Suche nach Digest-Datei...
Digest-Prüfung übersprungen: keine Digest-Datei gefunden
I:Update binary zip
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment not used in updater.
Archive:  /sdcard/Download/magisk/Magisk-f623b988(22101).zip
  inflating: lib/x86/libbusybox.so
  inflating: lib/armeabi-v7a/libbusybox.so
unzip: short read
Archive:  /sdcard/Download/magisk/Magisk-f623b988(22101).zip
  inflating: lib/x86/libmagisk64.so
  inflating: assets/chromeos/futility
  inflating: assets/chromeos/kernel_data_key.vbprivk
  inflating: lib/armeabi-v7a/libmagiskboot.so
  inflating: assets/uninstaller.sh
  inflating: lib/armeabi-v7a/libmagiskinit.so
  inflating: META-INF/com/google/android/update-binary
  inflating: lib/x86/libmagiskboot.so
  inflating: lib/armeabi-v7a/libmagisk64.so
  inflating: assets/addon.d.sh
  inflating: lib/x86/libmagiskinit.so
  inflating: lib/armeabi-v7a/libmagisk32.so
  inflating: assets/boot_patch.sh
  inflating: assets/chromeos/kernel.keyblock
  inflating: assets/util_functions.sh
  inflating: META-INF/com/google/android/updater-script
  inflating: lib/x86/libmagisk32.so
**********************************
 Magisk f623b988(22101) Installer 
**********************************
- Mounting /system
- Target image: /dev/block/mmcblk0p17
- Device platform: arm
- Constructing environment
java.io.IOException: ioctl failed: EINVAL (Invalid argument)
	at libcore.io.IoBridge.available(IoBridge.java:74)
	at java.io.FileInputStream.available(FileInputStream.java:108)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:274)
	at com.topjohnwu.signing.SignBoot.fullRead(SignBoot.java:100)
	at com.topjohnwu.signing.SignBoot.verifySignature(SignBoot.java:155)
	at com.topjohnwu.signing.SignBoot.main(SignBoot.java:350)
Caused by: android.system.ErrnoException: ioctl failed: EINVAL (Invalid argument)
	at libcore.io.Posix.ioctlInt(Native Method)
	at libcore.io.ForwardingOs.ioctlInt(ForwardingOs.java:103)
	at libcore.io.IoBridge.available(IoBridge.java:58)
	... 5 more
- Unpacking boot image
Parsing boot image: [/dev/block/mmcblk0p17]
HEADER_VER      [0]
KERNEL_SZ       [9879096]
RAMDISK_SZ      [2886352]
SECOND_SZ       [0]
EXTRA_SZ        [3407872]
PAGESIZE        [4096]
NAME            [SYSMAGIC000KU]
CMDLINE         [console=null androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x3b7 dwc3_msm.cpu_to_affin=1]
CHECKSUM        [7c2318906ff8666f1c9df3b993922944aa9c6850000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
EXTRA_FMT       [raw]
SAMSUNG_SEANDROID
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Magisk patched boot image detected
Loading cpio: [ramdisk.cpio]
Remove [overlay.d]
Remove [overlay.d/sbin]
Remove [overlay.d/sbin/magisk32.xz]
Remove [.backup/.rmlist]
Remove [.backup]
Remove [.backup/.magisk]
Move [.backup/fstab.qcom] -> [fstab.qcom]
Move [.backup/init] -> [init]
Dump cpio: [ramdisk.cpio]
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Patch with flag KEEPVERITY=[false] KEEPFORCEENCRYPT=[false]
Found fstab file [fstab.qcom]
Remove pattern [,verify]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [fstab.qcom] -> [.backup/fstab.qcom]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [extra]
- Repacking boot image
Parsing boot image: [/dev/block/mmcblk0p17]
HEADER_VER      [0]
KERNEL_SZ       [9879096]
RAMDISK_SZ      [2886352]
SECOND_SZ       [0]
EXTRA_SZ        [3407872]
PAGESIZE        [4096]
NAME            [SYSMAGIC000KU]
CMDLINE         [console=null androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x3b7 dwc3_msm.cpu_to_affin=1]
CHECKSUM        [7c2318906ff8666f1c9df3b993922944aa9c6850000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
EXTRA_FMT       [raw]
SAMSUNG_SEANDROID
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [9879096]
RAMDISK_SZ      [2886630]
SECOND_SZ       [0]
EXTRA_SZ        [3407872]
PAGESIZE        [4096]
NAME            [SYSMAGIC000KU]
CMDLINE         [console=null androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x3b7 dwc3_msm.cpu_to_affin=1]
CHECKSUM        [905c567083e0de8531c8df6ceb83dd46a13c6ce6000000000000000000000000]
- Flashing new boot image
Cleaning up...
- Unmounting partitions
- Done
I:Updater process ended with RC=0
I:Install took 9 second(s).
Partitions-Informationen werden aktualisiert...
I:Data backup size is 14699MB, free: 498MB.
I:Unable to mount '/usbstorage'
I:Actual block device: '', current file system: 'vfat'
...Fertig
I:Set page: 'flash_done'
I:operation_end - status=0
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:operation_start: 'Format'
Formatiere Cache mit make_ext4fs...
Creating filesystem with parameters:
    Size: 209715200
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 6400
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 51200
    Block groups: 2
    Reserved block group size: 15
Created filesystem with 11/12800 inodes and 1865/51200 blocks
warning: wipe_block_device: Wipe via secure discard failed, used discard instead

I:Recreating /cache/recovery folder.
I:Copying file /etc/recovery.fstab to /cache/recovery/recovery.fstab
I:Version number saved to '/cache/recovery/.version'
Partitions-Informationen werden aktualisiert...
I:Data backup size is 14699MB, free: 498MB.
I:Unable to mount '/usbstorage'
I:Actual block device: '', current file system: 'vfat'
...Fertig
I:Set page: 'action_complete'
I:operation_end - status=0
I:operation_start: 'Format'
Dalvik Cache-Verzeichnisse bereinigen...
Bereinigt: /data/dalvik-cache...
-- Dalvik Cache-Verzeichnisse bereinigt!
Partitions-Informationen werden aktualisiert...
I:Set page: 'clear_vars'
I:Set page: 'flash_done'
I:Data backup size is 13777MB, free: 1421MB.
I:Unable to mount '/usbstorage'
I:Actual block device: '', current file system: 'vfat'
...Fertig
I:operation_end - status=0
I:Set page: 'clear_vars'
I:Set page: 'install'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'advanced'
I:Set page: 'copylog'
I:Set page: 'action_page'
I:operation_start: 'Copy Log'
I:Copying file /tmp/recovery.log to /data/media/0/recovery.log
Kernel-Log wurde nach /data/media/0/dmesg.log kopiert
Recovery-Log wurde nach /data/media/0/recovery.log kopiert.
I:Set page: 'action_complete'
I:operation_end - status=0
I:Set page: 'reboot_system_routine'
I:Set page: 'rebootcheck'
I:Set page: 'appcheck'
I:operation_start: 'Check for TWRP App'
I:App found at '/data/app/me.twrp.twrpapp-2'
I:operation_end - status=0
I:Copying file /cache/recovery/log to /cache/recovery/last_log
Neustart...

Related issues:

#4107 (closed - not enough info)
#4169 (closed - by bot)

**Comment by leppit** [comment]
see corrected issue #4174
