### ISSUE TITLE
Cast error while creating ASN1Sequence - car headunit on Android 10 

### ISSUE THREAD

**Issue by mariodantas** [topjohnwu/Magisk#4371]
Device: Sony Topway car Headunit
Android version: 10 
Magisk version name: f822ca5
Magisk version code: 23001

- Device platform: arm64-v8a
- Installing: 23.0 (23000)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [17090572]
RAMDISK_SZ      [779984]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [161962]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-02]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyS1,115200n8 buildvariant=user]
CHECKSUM        [3ee1e2a9b7347c65779485fed4ab909a2f546ca4000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
VBMETA
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[false]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Patch @ 00D2DB4C [736B69705F696E697472616D667300] -> [77616E745F696E697472616D667300]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [17090572]
RAMDISK_SZ      [779984]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [161962]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-02]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyS1,115200n8 buildvariant=user]
CHECKSUM        [3ee1e2a9b7347c65779485fed4ab909a2f546ca4000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [17090572]
RAMDISK_SZ      [1088241]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [161962]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-02]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyS1,115200n8 buildvariant=user]
CHECKSUM        [388399cc3224e69173fa8d8d7d99ba6604de3ab2000000000000000000000000]

****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched-23001_F4y3j.img 
****************************
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
- All done!

**Comment by mariodantas** [comment]
After patching boot.img with Magisk and check integrity i found something like this, below: 

boot.img failed integrity check by "python aosp/avb/avbtool.v1.2.py verify_image --image boot.img"
Signature check failed for SHA256_RSA4096 vbmeta struct boot.img



[boot.7z.gz](https://github.com/topjohnwu/Magisk/files/6501533/boot.7z.gz)
(this is a 7z file containing the boot.img impossible to root, the file has a 'gz' extension to allow upload here)

**Comment by mariodantas** [comment]
Note the following messages at the end of the magisk patch log:

**cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted**

**Comment by mariodantas** [comment]
Found this in a chinese forum, does it help ?

`fun disableVbMetaImg() {
        try {
            // find vbmeta.img block
            val vbmetaPath = ShellUtils.fastCmd("readlink -f `find /dev/block \\( -type b -o -type c -o -type l \\) -iname vbmeta | head -n 1`")
            if (TextUtils.isEmpty(vbmetaPath)) {
                Log.w(Const.TAG, "could not find vbmeta.img!")
                return
            }
            val patchedVbmetaPath = "/sdcard/patched_vbmeta.img"
            if (!Shell.sh("dd if=$vbmetaPath of=$patchedVbmetaPath").exec().isSuccess) {
                Log.w(Const.TAG, "extract vbmeta.img failed!")
                return
            }
            val patchedVbMeta = SuFile.open(patchedVbmetaPath).readBytes()
            // There's a 32-bit big endian |flags| field at offset 120 where
            // bit 0 corresponds to disable-verity and bit 1 corresponds to
            // disable-verification.
            ByteBuffer.wrap(patchedVbMeta).putInt(120, 2)
            File(patchedVbmetaPath).writeBytes(patchedVbMeta)
            // rewrite vbmeta.img
            Log.d(Const.TAG, "rewrite vbmeta.img finished: $patchedVbmetaPath to $vbmetaPath")
            Shell.sh("eval 'cat '$patchedVbmetaPath'' | eval 'cat -' | cat - /dev/zero > $vbmetaPath 2>/dev/null").exec()
        } catch (e: Throwable) {
            Log.i(Const.TAG, "disable vb_meta.img avb2.0 error:", e)
        }
    }`

**Comment by mariodantas** [comment]
And debugging APP (while patching a boot.img) I logged this, I hope this can help

2021-05-19 09:17:45.604 10255-10329/com.topjohnwu.magisk W/System.err: java.lang.ClassCastException: org.bouncycastle.asn1.DLApplicationSpecific cannot be cast to org.bouncycastle.asn1.ASN1Sequence
2021-05-19 09:17:45.605 10255-10329/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.signing.SignBoot$BootSignature.<init>(SignBoot.java:260)
2021-05-19 09:17:45.606 10255-10329/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.signing.SignBoot.verifySignature(SignBoot.java:167)
2021-05-19 09:17:45.607 10255-10329/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchBoot(MagiskInstaller.kt:341)
2021-05-19 09:17:45.608 10255-10329/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:298)
2021-05-19 09:17:45.609 10255-10329/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.doPatchFile(MagiskInstaller.kt:416)
2021-05-19 09:17:45.611 10255-10329/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:469)
2021-05-19 09:17:45.612 10255-10329/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:436)
2021-05-19 09:17:45.613 10255-10329/com.topjohnwu.magisk W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-05-19 09:17:45.614 10255-10329/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-05-19 09:17:45.615 10255-10329/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2021-05-19 09:17:45.616 10255-10329/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
2021-05-19 09:17:45.616 10255-10329/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2021-05-19 09:17:45.617 10255-10329/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by mariodantas** [comment]
I did a simple test in the SignBoot.java file like below

        public BootSignature(byte[] signature) throws Exception {
            ASN1InputStream stream = new ASN1InputStream(signature);

            **Timber.i("Reading ASN1Sequence...");**
            ASN1Sequence sequence = (ASN1Sequence) stream.readObject();
            **Timber.i("Created sequence object...");**


And the 1st Log appears in the logcat but not the 2nd log below ASN1Sequence

Throws this below:

2021-05-21 15:01:58.133 17642-17688/com.topjohnwu.magisk I/SignBoot$BootSignature: Reading ASN1Sequence...
2021-05-21 15:01:58.148 17642-17688/com.topjohnwu.magisk W/System.err: java.lang.ClassCastException: org.bouncycastle.asn1.DLApplicationSpecific cannot be cast to org.bouncycastle.asn1.ASN1Sequence
2021-05-21 15:01:58.149 17642-17688/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.signing.SignBoot$BootSignature.<init>(SignBoot.java:264)
2021-05-21 15:01:58.149 17642-17688/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.signing.SignBoot.verifySignature(SignBoot.java:169)
2021-05-21 15:01:58.149 17642-17688/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchBoot(MagiskInstaller.kt:341)
2021-05-21 15:01:58.149 17642-17688/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:298)
2021-05-21 15:01:58.149 17642-17688/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.doPatchFile(MagiskInstaller.kt:416)
2021-05-21 15:01:58.150 17642-17688/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:469)
2021-05-21 15:01:58.150 17642-17688/com.topjohnwu.magisk W/System.err:     at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:436)
2021-05-21 15:01:58.150 17642-17688/com.topjohnwu.magisk W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-05-21 15:01:58.150 17642-17688/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-05-21 15:01:58.150 17642-17688/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2021-05-21 15:01:58.150 17642-17688/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
2021-05-21 15:01:58.150 17642-17688/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2021-05-21 15:01:58.150 17642-17688/com.topjohnwu.magisk W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by mariodantas** [comment]
Forget to upload the boot.img I'm working with

[TS10boot.zip](https://github.com/topjohnwu/Magisk/files/6523285/TS10boot.zip)

**Comment by topjohnwu** [comment]
Nothing you see in the logs indicate anything incorrect is happening. All is expected behavior
