### ISSUE TITLE
Signing release

### ISSUE THREAD

**Issue by TugaPowerROM** [topjohnwu/Magisk#464]
When building with flag release, signing is now failing when before it was working fine:

* Signing Zip

Exception in thread "main" java.io.IOException: keystore password was incorrect
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2059)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:238)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.topjohnwu.utils.SignAPK.sign(SignAPK.java:88)
	at com.topjohnwu.utils.ZipSigner.main(ZipSigner.java:36)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: pad block corrupted
	... 6 more

Signing zip failed!

When using keytool to check the release-key.jks the password is accepted and its fine

keytool -v -list -keystore release-key.jks
Enter keystore password:  
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: tugapower

**Comment by topjohnwu** [comment]
The PKCS12 keystore type is currently not supported, it will use JKS by default. I will see what I can do, thanks for the report!
