### ISSUE TITLE
Can't Update Magisk -Error Downloading File-

### ISSUE THREAD

**Issue by akano12** [topjohnwu/Magisk#4930]
Device: Samsung Galaxy J6+ (SM-J610F)
Android version: 9.0
Magisk version name: 7e9d
Magisk version code: 23014

Not sure if this issue has been discussed before.
This issue started in 23010 and still exists till now,
i remember magisk having such behavior in builds previous to 23010 but was fixed when toggling DNS over HTTPS in settings,

Zygisk disabled & Manager isn't hidden

![Screenshot_20211112-143007](https://user-images.githubusercontent.com/50032603/141472035-789b9cc5-6707-451e-916c-9f86bbbe5eba.jpg)

**Comment by Fox2Code** [comment]
Yeah same problem, I didn't reported before because of real life issues, but can confirm.
Something I found weird is this behavior only affected my OxygenOS Android 11 phone.
My other older phone using EvolutionX Android 10 don't have this issue.

And yes I also remember DoH fixing this issue.

**Comment by Fox2Code** [comment]
After doing some research, I found out some ad-blocking scripts block `cdn.jsdelivr.net`, preventing Magisk from updating itself.
```
11-17 17:17:24.952 18821 19442 I okhttp.OkHttpClient: <-- HTTP FAILED: java.net.ConnectException: Failed to connect to cdn.jsdelivr.net/127.0.0.1:443
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: java.net.ConnectException: Failed to connect to cdn.jsdelivr.net/127.0.0.1:443
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at java.lang.Thread.run(Thread.java:923)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: Caused by: java.net.ConnectException: failed to connect to cdn.jsdelivr.net/127.0.0.1 (port 443) from /127.0.0.1 (port 48794) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at libcore.io.IoBridge.isConnected(IoBridge.java:287)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at libcore.io.IoBridge.connect(IoBridge.java:134)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at java.net.Socket.connect(Socket.java:621)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	... 20 more
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
11-17 17:17:24.954 18821 18872 E MarkDownDialog$build: 	... 30 more
```

**Comment by akano12** [comment]
yup, can confirm.

after clearing the hosts file magisk this issue was fixed :(

**Comment by digitalTrilunaire** [comment]
Hi,
Can reproduce the issue too (DotOS5.2 GSI), disabling Adaway (adblocker which modify host file) fix the issue. Thanks @Fox2Code

**Comment by akano12** [comment]
> Hi,
> Can reproduce the issue too (DotOS5.2 GSI, Magisk 23), disabling Adaway (adblocker which modify host file) fix the issue. Thanks @Fox2Code 
> Edit: after re-enabling the adblocker (and updating host files), it seems to work normally

In my case it only works when clearing hosts file :(

**Comment by Kkhansak** [comment]
> Device: Samsung Galaxy J6+ (SM-J610F) Android version: 9.0 Magisk version name: 7e9d Magisk version code: 23014
> 
> Not sure if this issue has been discussed before. This issue started in 23010 and still exists till now, i remember magisk having such behavior in builds previous to 23010 but was fixed when toggling DNS over HTTPS in settings,
> 
> Zygisk disabled & Manager isn't hidden
> 
> ![Screenshot_20211112-143007](https://user-images.githubusercontent.com/50032603/141472035-789b9cc5-6707-451e-916c-9f86bbbe5eba.jpg)

**Comment by luckyman1352** [comment]
Check safety net
