### ISSUE TITLE
Magisk App deadlock 

### ISSUE THREAD

**Issue by yujincheng08** [topjohnwu/Magisk#5178]
Device: mido
Android version: 11
Magisk version name: 0c1f68816e
Magisk version code: 23016

This crash is likely caused by upgrading libsu. This is exactly the first issue mentioned by #5135.

Here's the anr report generated manually by `kill -s SIGQUIT $(pidof com.topjohnwu.magisk)`.

[trace_00.txt](https://github.com/topjohnwu/Magisk/files/7825776/trace_00.txt)

**Comment by yujincheng08** [comment]
Here's the deadlock (tid=1 and tid=21):

```
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x733706a8 self=0x713b297be0
  | sysTid=8404 nice=0 cgrp=default sched=0/0 handle=0x7261bf44f8
  | state=S schedstat=( 1044668173 18099791 246 ) utm=91 stm=13 core=7 HZ=100
  | stack=0x7ffeec3000-0x7ffeec5000 stackSize=8192KB
  | held mutexes=
  at com.topjohnwu.superuser.internal.MainShell.get(MainShell.java:-1)
  - waiting to lock <0x01c35d3f> (a java.lang.Class<com.topjohnwu.superuser.internal.MainShell>) held by thread 21
  at com.topjohnwu.superuser.Shell.getShell(Shell.java:163)
  at com.topjohnwu.superuser.ShellUtils.fastCmd(ShellUtils.java:64)
  at com.topjohnwu.magisk.core.Info.loadState(Info.kt:55)
  at com.topjohnwu.magisk.core.Info.access$loadState(Info.kt:17)
  at com.topjohnwu.magisk.core.Info$env$2.invoke(Info.kt:30)
  at com.topjohnwu.magisk.core.Info$env$2.invoke(Info.kt:30)
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
  - locked <0x0452160c> (a kotlin.SynchronizedLazyImpl)
  at com.topjohnwu.magisk.core.Info.getEnv(Info.kt:30)
  at com.topjohnwu.magisk.databinding.FragmentHomeMd2BindingImpl.executeBindings(FragmentHomeMd2BindingImpl.java:226)
  at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:512)
  at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:484)
  at androidx.databinding.ViewDataBinding$OnStartListener.onStart(ViewDataBinding.java:1706)
  at java.lang.reflect.Method.invoke(Native method)
  at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:222)
  at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:199)
  at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:190)
  at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:40)
  at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
  at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
  at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
  at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
  at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
  at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:88)
  at androidx.fragment.app.Fragment.performStart(Fragment.java:3060)
  at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:587)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
  at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
  at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
  at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
  at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2791)
  at androidx.fragment.app.Fragment.performStart(Fragment.java:3062)
  at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:587)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
  at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
  at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
  at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
  at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2791)
  at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:273)
  at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:486)
  at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1441)
  at android.app.Activity.performStart(Activity.java:8018)
  at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:223)
  at android.app.ActivityThread.main(ActivityThread.java:7664)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

```
"DefaultDispatcher-worker-2" daemon prio=5 tid=21 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x12cc5630 self=0x713b2c1760
  | sysTid=8433 nice=0 cgrp=default sched=0/0 handle=0x6f59b8bcc0
  | state=S schedstat=( 28427131 2092658 38 ) utm=2 stm=0 core=6 HZ=100
  | stack=0x6f59a88000-0x6f59a8a000 stackSize=1043KB
  | held mutexes=
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:69)
  - waiting to lock <0x0452160c> (a kotlin.SynchronizedLazyImpl) held by thread 1
  at com.topjohnwu.magisk.core.Info.getEnv(Info.kt:30)
  at com.topjohnwu.magisk.core.utils.ShellInit.onInit(ShellInit.kt:89)
  at com.topjohnwu.superuser.internal.BuilderImpl.build(BuilderImpl.java:95)
  at com.topjohnwu.superuser.internal.BuilderImpl.build(BuilderImpl.java:50)
  at com.topjohnwu.superuser.internal.MainShell.lambda$get$2(MainShell.java:63)
  - locked <0x01c35d3f> (a java.lang.Class<com.topjohnwu.superuser.internal.MainShell>)
  at com.topjohnwu.superuser.internal.MainShell$$ExternalSyntheticLambda2.run(unavailable:-1)
  at com.topjohnwu.magisk.core.utils.DispatcherExecutor$execute$1.invokeSuspend(DispatcherExecutor.kt:20)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by yujincheng08** [comment]
`getEnv` will lock a kotlin lazy and call and lock MainShell;
while a locked MainShell will also call `getEnv` to lock the kotlin lazy.
