### ISSUE TITLE
Essential Phone boot stucked

### ISSUE THREAD

**Issue by saidie** [topjohnwu/Magisk#5275]
Device: Essential Phone
Android version: Android 11 (LineageOS 18.1)
Magisk version name: Canary
Magisk version code: 23019

[boot.img.gz](https://github.com/topjohnwu/Magisk/files/7935940/boot.img.gz)
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/7935946/dmesg.txt)
[logcat.txt](https://github.com/topjohnwu/Magisk/files/7935947/logcat.txt)
[mounts.txt](https://github.com/topjohnwu/Magisk/files/7935960/mounts.txt)

After flashing Magisk patched boot.img, the phone stucked at boot animation.

**Comment by yujincheng08** [comment]
```
01-26 02:53:12.409  1691  1691 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
01-26 02:53:12.409  1691  1691 E AndroidRuntime: java.lang.RuntimeException: Failed to create service com.android.server.display.DisplayManagerService: service constructor threw an exception
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:161)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:831)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:599)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:417)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:150)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	... 6 more
01-26 02:53:12.409  1691  1691 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: There must be at least two control points and the arrays must be of equal length.
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at android.util.Spline$MonotoneCubicSpline.<init>(Spline.java:131)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at android.util.Spline.createMonotoneCubicSpline(Spline.java:72)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at android.util.Spline.createSpline(Spline.java:47)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at com.android.server.display.DisplayManagerService.<init>(DisplayManagerService.java:348)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	at com.android.server.display.DisplayManagerService.<init>(DisplayManagerService.java:326)
01-26 02:53:12.409  1691  1691 E AndroidRuntime: 	... 9 more
```

**Comment by saidie** [comment]
Thank you, now it works!

I thought that I disabled all modules but probably not (I could not check module status because module button in the Magisk app was gray out since my phone lost root already). So I deleted the module file and the problem was gone.

```sh
# rm -rf /data/adb/modules/fomey.smalipatcher/
```
