### ISSUE TITLE
Can't open hidden Magisk app (crash) after Zygisk activation

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#5384]
Device: Xiaomi Poco X3 Pro
Android version: Android 11
Magisk version name: 1a1b346c
Magisk version code: 24102

After repacking Magisk app it stops opening if Zygisk is ON. After Zygisk disabling app works correct.

```
[02-06 20:29:23.370 12486:12486 D/AndroidRuntime] Shutting down VM
[02-06 20:29:23.371 12486:12486 E/AndroidRuntime] FATAL EXCEPTION: main
Process: w.elyceu.b.w.dv.n, PID: 12486
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{w.elyceu.b.w.dv.n/e.s}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3455)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3699)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference
	at I.instantiateActivity(:1)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1254)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3443)
	... 11 more
```

Full log: [logcat_02-06-2022_20-29-36.txt](https://github.com/topjohnwu/Magisk/files/8010803/logcat_02-06-2022_20-29-36.txt)

**Comment by Displax** [comment]
Look like the same as https://github.com/topjohnwu/Magisk/issues/4926

**Comment by yujincheng08** [comment]
You didn't upgrade the stub successfully. Please restore the Magisk app and hide it again.
