### ISSUE TITLE
Split screen on Module page crashes stub app

### ISSUE THREAD

**Issue by yujincheng08** [topjohnwu/Magisk#5413]
Device: Any
Android version: 12
Magisk version name: canary
Magisk version code: 24102

```
java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:241)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:215)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:143)
        at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:75)
        at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:124)
        at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:114)
        at java.lang.reflect.Constructor.newInstance0(Constructor.java:-2)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:881)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1033)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:988)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1150)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1111)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:709)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:547)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapter.onCreateBinding(BindingRecyclerViewAdapter.java:117)
        at me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapter.onCreateViewHolder(BindingRecyclerViewAdapter.java:155)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:866)
        at android.view.View.layout(View.java:23563)
        at android.view.ViewGroup.layout(ViewGroup.java:6452)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3870)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3320)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2284)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9050)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
        at android.view.Choreographer.doCallbacks(Choreographer.java:946)
        at android.view.Choreographer.doFrame(Choreographer.java:875)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8210)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by yujincheng08** [comment]
@RikkaW
