### ISSUE TITLE
 Magisk cannot patch bootloader on Android12 phone

### ISSUE THREAD

**Issue by wirawan0** [topjohnwu/Magisk#5498]
Device: Pixel 3 XL
Android version: 12 (see below)
Magisk version name: 
Magisk version code: 24102

Tried to install Magisk on Pixel 3 XL that was just updated to Android 12, encountered this error:

```
- Device platform: arm64-v8a
- Installing: 1a1b346c (24102)
- Copying image to cache
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
- Unpacking boot image
! Unsupported/Unknown image format
! Installation failed
```

Bootloader was obtained from official source, this file:
crosshatch-sp1a.210812.015/bootloader-crosshatch-b1c1-0.4-7617406.img

Source zip: https://developers.google.com/android/images#crosshatch >> image version 12.0.0 (SP1A.210812.015, Oct 2021) .

The magisk log itself contains the following:

```
02-28 02:33:39.194 28241 28267 W System.err: java.lang.IllegalArgumentException: Invalid image header: missing magic
02-28 02:33:39.194 28241 28267 W System.err:    at com.topjohnwu.magisk.signing.SignBoot.getSignableImageSize(SignBoot.java:187)
02-28 02:33:39.194 28241 28267 W System.err:    at com.topjohnwu.magisk.signing.SignBoot.verifySignature(SignBoot.java:150)
02-28 02:33:39.194 28241 28267 W System.err:    at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchBoot(MagiskInstaller.kt:337)
02-28 02:33:39.194 28241 28267 W System.err:    at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:298)
02-28 02:33:39.194 28241 28267 W System.err:    at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.doPatchFile(MagiskInstaller.kt:413)
02-28 02:33:39.194 28241 28267 W System.err:    at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:466)
02-28 02:33:39.194 28241 28267 W System.err:    at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:433)
02-28 02:33:39.194 28241 28267 W System.err:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-28 02:33:39.194 28241 28267 W System.err:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-28 02:33:39.194 28241 28267 W System.err:    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
02-28 02:33:39.194 28241 28267 W System.err:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
02-28 02:33:39.194 28241 28267 W System.err:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
02-28 02:33:39.194 28241 28267 W System.err:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

See attached for the bootloader image.

Thanks,
Wirawan

**Comment by wirawan0** [comment]
[crosshatch-sp1a.210812.015-bootloader.zip](https://github.com/topjohnwu/Magisk/files/8151448/crosshatch-sp1a.210812.015-bootloader.zip)

**Comment by Displax** [comment]
You need to patch boot, NOT bootloader...

**Comment by wirawan0** [comment]
Yes, I did solve it. Ilya's response was helpful. It was a mistake of a
newbie. I got the phone successfully rooted.

Wirawan

**Comment by wirawan0** [comment]
I downloaded this one from Google website: crosshatch-sp1a.210812.016.c1-factory-67ea87fc.zip (starting url: https://developers.google.com/android/images). Inside it, there are other zip files:

```
Archive:  /home/wirawan/Projects/logs/pixel3XL/imgs/crosshatch-sp1a.210812.016.a2-factory-0de199e1.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2021-12-16 15:32   crosshatch-sp1a.210812.016.a2/
  8726312  2021-12-16 15:32   crosshatch-sp1a.210812.016.a2/bootloader-crosshatch-b1c1-0.4-7617406.img
     1063  2021-12-16 15:32   crosshatch-sp1a.210812.016.a2/flash-base.sh
1981822871  2021-12-16 15:32   crosshatch-sp1a.210812.016.a2/image-crosshatch-sp1a.210812.016.a2.zip
     1122  2021-12-16 15:32   crosshatch-sp1a.210812.016.a2/flash-all.sh
 73183372  2021-12-16 15:32   crosshatch-sp1a.210812.016.a2/radio-crosshatch-g845-00194-210812-b-7635520.img
     1005  2021-12-16 15:32   crosshatch-sp1a.210812.016.a2/flash-all.bat
---------                     -------
2063735745                     7 files
```

The inner zip file inside the zip file above has boot.img inside it. *This was the instruction that I missed all along.*

I hope this is useful, but if you have additional questions, you might want to ask on the forum or open another issue, since this is actually a closed Github issue. I thought I would respond so we all have a permanent record of what ended upworking. Thanks for asking.
