### ISSUE TITLE
Randomized Magisk App Crashed

### ISSUE THREAD

**Issue by Stillhard** [topjohnwu/Magisk#5510]
Device: 
Android version: 11
Magisk version name: 7cfce9ff
Magisk version code: 24201

After randomize the Magisk App Beta from [here](https://github.com/topjohnwu/Magisk/tree/v24.2) OR the Canary from [here](https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@becbcbd159137ae474238c582f5f2ed6f4a959f8/app-debug.apk) and do a reboot, the renamed Magisk app (qmrsc.nz.j.kmofgmx) crashed:

```
2022-03-02 18:07:58.575 646-648/? D/Magisk: su: request from pid=[3502], client=[19]
2022-03-02 18:07:58.575 646-648/? D/Magisk: su: request from uid=[10249]
2022-03-02 18:07:58.576 646-648/? D/Magisk: magiskdb: query policy=[2] log=[1] notify=[1]
2022-03-02 18:07:58.583 646-648/? D/Magisk: su: waiting child pid=[3510]
2022-03-02 18:07:58.584 3510-3510/? D/Magisk: su: fork handler
2022-03-02 18:07:58.584 3510-3510/? D/Magisk: su: use namespace of pid=[3502]
2022-03-02 18:07:58.895 1489-1562/? I/ActivityManager: Start proc 3545:qmrsc.nz.j.kmofgmx/u0a235 for content provider {qmrsc.nz.j.kmofgmx/v.K}
2022-03-02 18:07:58.967 1489-3541/? D/os.ActivityManagerServiceLice: make process active qmrsc.nz.j.kmofgmx(3545)
2022-03-02 18:07:58.995 3545-3545/? W/ContextImpl: Failed to ensure /data/user/0/qmrsc.nz.j.kmofgmx/cache: mkdir failed: errno 126 (Required key not available)
2022-03-02 18:07:59.283 3545-3545/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: qmrsc.nz.j.kmofgmx, PID: 3545
    java.lang.RuntimeException: Unable to instantiate application iuf.vF: java.lang.NullPointerException: Attempt to get length of null array
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1252)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7015)
        at android.app.ActivityThread.access$1600(ActivityThread.java:257)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:268)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at e.<init>(Unknown Source:39)
        at g.attachBaseContext(:7)
        at android.app.Application.attach(Application.java:351)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1165)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1244)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7015) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:257) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:268) 
        at android.app.ActivityThread.main(ActivityThread.java:8019) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 
2022-03-02 18:07:59.290 717-749/? I/libPowerHal: [perfNotifyAppState] pack:qmrsc.nz.j.kmofgmx, pid:3545, STATE_DEAD
2022-03-02 18:07:59.294 1489-3587/? D/AES: ExceptionLog: notify aed, process:qmrsc.nz.j.kmofgmx pid:3545 cause:data_app_crash 
2022-03-02 18:07:59.338 1489-1981/? I/ActivityManager: Process qmrsc.nz.j.kmofgmx (pid 3545) has died: fg  IMPF
2022-03-02 18:07:59.339 1489-1981/? D/os.ActivityManagerServiceLice: make process inactive qmrsc.nz.j.kmofgmx(3545)
2022-03-02 18:07:59.341 717-749/? I/libPowerHal: [perfNotifyAppState] pack:qmrsc.nz.j.kmofgmx, pid:3545, STATE_DEAD
2022-03-02 18:07:59.357 1489-1562/? I/ActivityManager: Start proc 3601:qmrsc.nz.j.kmofgmx/u0a235 for restart qmrsc.nz.j.kmofgmx
2022-03-02 18:07:59.396 1489-1661/? D/os.ActivityManagerServiceLice: make process active qmrsc.nz.j.kmofgmx(3601)
2022-03-02 18:07:59.400 3525-3581/? D/BinderSender: onActive: uid=10235, packages=qmrsc.nz.j.kmofgmx
2022-03-02 18:07:59.411 3601-3601/? W/ContextImpl: Failed to ensure /data/user/0/qmrsc.nz.j.kmofgmx/cache: mkdir failed: errno 126 (Required key not available)
2022-03-02 18:07:59.418 3601-3601/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: qmrsc.nz.j.kmofgmx, PID: 3601
    java.lang.RuntimeException: Unable to instantiate application iuf.vF: java.lang.NullPointerException: Attempt to get length of null array
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1252)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7015)
        at android.app.ActivityThread.access$1600(ActivityThread.java:257)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:268)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at e.<init>(Unknown Source:39)
        at g.attachBaseContext(:7)
        at android.app.Application.attach(Application.java:351)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1165)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1244)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7015) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:257) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:268) 
        at android.app.ActivityThread.main(ActivityThread.java:8019) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 
2022-03-02 18:07:59.422 717-749/? I/libPowerHal: [perfNotifyAppState] pack:qmrsc.nz.j.kmofgmx, pid:3601, STATE_DEAD
2022-03-02 18:07:59.429 1489-3638/? D/AES: ExceptionLog: notify aed, process:qmrsc.nz.j.kmofgmx pid:3601 cause:data_app_crash 
2022-03-02 18:07:59.447 1489-2264/? W/ActivityManager: Process qmrsc.nz.j.kmofgmx has crashed too many times: killing!
2022-03-02 18:07:59.447 1489-2264/? I/ActivityManager: Killing 3601:qmrsc.nz.j.kmofgmx/u0a235 (adj 0): crash
2022-03-02 18:07:59.448 1489-2264/? D/os.ActivityManagerServiceLice: make process inactive qmrsc.nz.j.kmofgmx(3601)
2022-03-02 18:07:59.449 1489-2578/? D/ActivityManager: Timeout waiting for provider qmrsc.nz.j.kmofgmx/10235 for provider qmrsc.nz.j.kmofgmx.provider providerRunning=false caller=unknown/0
2022-03-02 18:07:59.449 717-749/? I/libPowerHal: [perfNotifyAppState] pack:qmrsc.nz.j.kmofgmx, pid:3601, STATE_DEAD
2022-03-02 18:08:00.272 1489-2427/? W/ActivityTaskManager: checkDualprofileControl, from:com.android.shell, to:qmrsc.nz.j.kmofgmx, with act:android.intent.action.VIEW, callingUserId:0, toUserId:0, aInfo:ActivityInfo{aeefe49 t.D}
2022-03-02 18:08:00.273 1489-2427/? I/ActivityTaskManager: START u0 {act=android.intent.action.VIEW flg=0x18000020 pkg=qmrsc.nz.j.kmofgmx cmp=qmrsc.nz.j.kmofgmx/t.D (has extras)} from uid 0
2022-03-02 18:08:00.294 1489-1557/? D/DexOptExtImpl: qmrsc.nz.j.kmofgmx reason is install
2022-03-02 18:08:00.304 1489-1562/? I/ActivityManager: Start proc 3752:qmrsc.nz.j.kmofgmx/u0a235 for top-activity {qmrsc.nz.j.kmofgmx/t.D}
2022-03-02 18:08:00.338 1489-2427/? D/os.ActivityManagerServiceLice: make process active qmrsc.nz.j.kmofgmx(3752)
2022-03-02 18:08:00.342 1489-2427/? D/os.fingerprint: onRealStartActivityLocked next:ActivityRecord{e608d7c u0 qmrsc.nz.j.kmofgmx/t.D t5} isKeyguardShowing:true
2022-03-02 18:08:00.342 1489-1549/? D/VideoCallEnhancerControlImpl: className is qmrsc.nz.j.kmofgmx/t.D
2022-03-02 18:08:00.344 717-749/? I/libPowerHal: [perfNotifyAppState] foreground:qmrsc.nz.j.kmofgmx, pid:3752, uid:10235
2022-03-02 18:08:00.344 717-749/? I/UxUtility: notifyForegroundApp pack:qmrsc.nz.j.kmofgmx, uid:10235
2022-03-02 18:08:00.346 1489-2427/? D/FloatWindow: pkgName = qmrsc.nz.j.kmofgmx
2022-03-02 18:08:00.352 3525-3581/? D/BinderSender: onActive: uid=10235, packages=qmrsc.nz.j.kmofgmx
2022-03-02 18:08:00.365 3752-3752/? W/ContextImpl: Failed to ensure /data/user/0/qmrsc.nz.j.kmofgmx/cache: mkdir failed: errno 126 (Required key not available)
2022-03-02 18:08:00.373 3752-3752/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: qmrsc.nz.j.kmofgmx, PID: 3752
    java.lang.RuntimeException: Unable to instantiate application iuf.vF: java.lang.NullPointerException: Attempt to get length of null array
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1252)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7015)
        at android.app.ActivityThread.access$1600(ActivityThread.java:257)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:268)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at e.<init>(Unknown Source:39)
        at g.attachBaseContext(:7)
        at android.app.Application.attach(Application.java:351)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1165)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1244)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7015) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:257) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:268) 
        at android.app.ActivityThread.main(ActivityThread.java:8019) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 
2022-03-02 18:08:00.380 717-749/? I/libPowerHal: [perfNotifyAppState] pack:qmrsc.nz.j.kmofgmx, pid:3752, STATE_DEAD
2022-03-02 18:08:00.385 1489-3788/? D/AES: ExceptionLog: notify aed, process:qmrsc.nz.j.kmofgmx pid:3752 cause:data_app_crash 
2022-03-02 18:08:00.410 1489-1535/? W/ActivityTaskManager:   Force finishing activity qmrsc.nz.j.kmofgmx/t.D
2022-03-02 18:08:00.436 1489-1535/? I/ActivityManager: Process qmrsc.nz.j.kmofgmx (pid 3752) has died: prcp TPSL
2022-03-02 18:08:00.436 1489-1535/? D/os.ActivityManagerServiceLice: make process inactive qmrsc.nz.j.kmofgmx(3752)
2022-03-02 18:08:00.437 717-749/? I/libPowerHal: [perfNotifyAppState] pack:qmrsc.nz.j.kmofgmx, pid:3752, STATE_DEAD
2022-03-02 18:08:00.847 1489-1549/? W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{e608d7c u0 qmrsc.nz.j.kmofgmx/t.D t-1 f}}
```

**Comment by Stillhard** [comment]
Restored it and do a reboot, no crash, repeated several times, the same behavior

**Comment by Stillhard** [comment]
One more thing **after every reboot**, this shows:
![photo_2022-03-02_18-49-49](https://user-images.githubusercontent.com/219005/156356376-90483cfd-38a6-41be-a210-6e902b2aa6f2.jpg)
Translation: [Upgrade to full Magisk to finish the setup. Download and install?](https://github.com/topjohnwu/Magisk/blob/df191cd2b56dc650f2d6a7fd94b1f91f244f5c04/stub/src/main/res/values/strings.xml#L3)
