### ISSUE TITLE
Get navHostFragment before adding?

### ISSUE THREAD

**Issue by vvb2060** [topjohnwu/Magisk#5765]
```
04-25 09:41:54.917  5565  5565 E AndroidRuntime: FATAL EXCEPTION: main
04-25 09:41:54.917  5565  5565 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 5565
04-25 09:41:54.917  5565  5565 E AndroidRuntime: java.lang.NullPointerException: null cannot be cast to non-null type androidx.navigation.fragment.NavHostFragment
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at java.util.Objects.requireNonNull(Objects.java:245)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at com.topjohnwu.magisk.arch.NavigationActivity$navHostFragment$2.invoke(NavigationActivity.kt:14)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at com.topjohnwu.magisk.arch.NavigationActivity$navHostFragment$2.invoke(NavigationActivity.kt:13)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at com.topjohnwu.magisk.arch.NavigationActivity.getNavHostFragment(NavigationActivity.kt:13)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at com.topjohnwu.magisk.arch.NavigationActivity.getCurrentFragment(NavigationActivity.kt:18)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at com.topjohnwu.magisk.arch.NavigationActivity.dispatchKeyEvent(NavigationActivity.kt:23)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3090)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:431)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6232)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6081)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5553)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5610)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5576)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5728)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5584)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5785)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5557)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5610)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5576)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5584)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5557)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5610)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5576)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5761)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5934)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3210)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2752)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2743)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3187)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.os.MessageQueue.nativePollOnce(Native Method)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.os.MessageQueue.next(MessageQueue.java:335)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8134)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
04-25 09:41:54.917  5565  5565 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by yujincheng08** [comment]
This issue happens only on lower versions of Android. At least on Android R, the key event won't dispatch unless a content view is set.
