### ISSUE TITLE
Stuck on bootscreen

### ISSUE THREAD

**Issue by imlaoyou2333** [topjohnwu/Magisk#5768]
Device: Huawei P10
Android version: 12 (gsi)
Magisk version name: 63a89d9f
Magisk version code: 24306
[bugreport-hi3660-SQ1D.220205.004-2022-04-28-06-04-05.zip](https://github.com/topjohnwu/Magisk/files/8580619/bugreport-hi3660-SQ1D.220205.004-2022-04-28-06-04-05.zip)

**Comment by canyie** [comment]
> E System  : java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.android.server.pm.Settings$VersionInfo.fingerprint' on a null object reference

Any module installed? I don't think the fatal crash seems not caused by Magisk itself

**Comment by imlaoyou2333** [comment]
No module installed

**Comment by canyie** [comment]
The issue will disappears after removing Magisk by flashing the stock boot image, right?

```
04-28 06:03:21.389  1000  6871  6871 I PackageManagerTiming: loadFallbacks
04-28 06:03:21.389  1000  6871  6871 I PackageManagerTiming: read user settings
04-28 06:03:21.395  1000  6871  6871 W PackageManager: No start tag found in package manager settings
04-28 06:03:21.396  1000  6871  6871 E PackageManager: No start tag found in package manager settings
04-28 06:03:21.397  1000  6871  6871 I Watchdog: Resuming HandlerChecker: main thread for reason: packagemanagermain. Pause count: 0
04-28 06:03:21.397  1000  6871  6871 E System  : ******************************************
04-28 06:03:21.397  1000  6871  6871 E System  : ************ Failure starting system services
04-28 06:03:21.397  1000  6871  6871 E System  : java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.android.server.pm.Settings$VersionInfo.fingerprint' on a null object reference
04-28 06:03:21.397  1000  6871  6871 E System  : 	at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:7631)
04-28 06:03:21.397  1000  6871  6871 E System  : 	at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:7133)
04-28 06:03:21.397  1000  6871  6871 E System  : 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:1170)
04-28 06:03:21.397  1000  6871  6871 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:884)
04-28 06:03:21.397  1000  6871  6871 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:617)
04-28 06:03:21.397  1000  6871  6871 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
04-28 06:03:21.397  1000  6871  6871 E System  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
04-28 06:03:21.397  1000  6871  6871 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.android.server.pm.Settings$VersionInfo.fingerprint' on a null object reference
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:7631)
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:7133)
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:1170)
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:884)
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:617)
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
04-28 06:03:21.398  1000  6871  6871 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```
The file `/data/system/packages.xml` seems to be corrupted. Try to rename/delete it and reboot.

**Comment by yujincheng08** [comment]
I don't think it's Magisk's issue.
