### ISSUE TITLE
RecyclerView IndexOutOfBoundsException: Inconsistency detected

### ISSUE THREAD

**Issue by vvb2060** [topjohnwu/Magisk#5879]
```
05-30 17:22:14.874  9924  9924 E AndroidRuntime: FATAL EXCEPTION: main
05-30 17:22:14.874  9924  9924 E AndroidRuntime: Process: rhc.otvpekva, PID: 9924
05-30 17:22:14.874  9924  9924 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 52(offset:334).state:54 androidx.recyclerview.widget.RecyclerView{194533b VFED..... ......ID 0,0-1080,2340 #7f090068 app:id/app_list}, adapter:a.Ks@8259a58, layout:androidx.recyclerview.widget.LinearLayoutManager@519b7b1, context:com.topjohnwu.magisk.ui.MainActivity@78dd535
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$e.T(RecyclerView.java:140)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$c.c(LinearLayoutManager.java:9)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.lx(LinearLayoutManager.java:1)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.wY(LinearLayoutManager.java:12)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.rd(LinearLayoutManager.java:122)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.n(RecyclerView.java:61)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.Y(RecyclerView.java:13)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.j(CoordinatorLayout.java:59)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:9)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.View.layout(View.java:23065)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3625)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3085)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2076)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8508)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
05-30 17:22:14.874  9924  9924 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:826)
05-30 17:22:14.875  9924  9924 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
05-30 17:22:14.875  9924  9924 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-30 17:22:14.875  9924  9924 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-30 17:22:14.875  9924  9924 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
05-30 17:22:14.875  9924  9924 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8107)
05-30 17:22:14.875  9924  9924 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 17:22:14.875  9924  9924 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
05-30 17:22:14.875  9924  9924 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
05-30 17:22:15.024  9924  9924 I Process : Sending signal. PID: 9924 SIG: 9
```

**Comment by yujincheng08** [comment]
https://github.com/topjohnwu/Magisk/commit/382568bd3c41bbadb30091d2eb28e411a07dec8e
