### ISSUE TITLE
Error inflating class FragmentContainerView: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by vvb2060** [topjohnwu/Magisk#5880]
```
05-30 17:42:54.381  6752  6752 E AndroidRuntime: FATAL EXCEPTION: main
05-30 17:42:54.381  6752  6752 E AndroidRuntime: Process: io.github.vvb2060.magisk, PID: 6752
05-30 17:42:54.381  6752  6752 E AndroidRuntime: android.view.InflateException: Binary XML file line #25 in io.github.vvb2060.magisk:layout/activity_main_md2: Binary XML file line #25 in io.github.vvb2060.magisk:layout/activity_main_md2: Error inflating class androidx.fragment.app.FragmentContainerView
05-30 17:42:54.381  6752  6752 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #25 in io.github.vvb2060.magisk:layout/activity_main_md2: Error inflating class androidx.fragment.app.FragmentContainerView
05-30 17:42:54.381  6752  6752 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1601)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1641)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.navigation.fragment.NavHostFragment.onAttach(NavHostFragment.kt:110)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.Fragment.performAttach(Fragment.java:3063)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1720)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentContainerView.addDisappearingFragmentView(FragmentContainerView.kt:323)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.kt:323)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1081)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.kt:303)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.kt:284)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at com.topjohnwu.magisk.arch.UIActivity.setContentView(UIActivity.kt:68)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at com.topjohnwu.magisk.ui.MainActivity.showMainUI(MainActivity.kt:51)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at com.topjohnwu.magisk.arch.BaseMainActivity.onCreate$lambda-2$lambda-1(BaseMainActivity.java:61)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:201)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.os.Looper.loop(Looper.java:288)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7877)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-30 17:42:54.381  6752  6752 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-30 17:42:54.441  6752  6752 I Process : Sending signal. PID: 6752 SIG: 9
```

**Comment by yujincheng08** [comment]
I think this line of code causes the problem.

This line of code is asynchronized. And it will restore the saved instance state. However, if this line of code runs later than the first time of save state, it will crash.

https://github.com/topjohnwu/Magisk/blob/2c092ffdef46512e94dd1b9c974e4b280e1da7fa/app/src/main/java/com/topjohnwu/magisk/arch/BaseMainActivity.kt#L60

**Comment by yujincheng08** [comment]
```
FATAL EXCEPTION: main
Process: com.topjohnwu.magisk, PID: 10832
android.view.InflateException: Binary XML file line #31 in com.topjohnwu.magisk:layout/activity_main_md2: Binary XML file line #31 in com.topjohnwu.magisk:layout/activity_main_md2: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #31 in com.topjohnwu.magisk:layout/activity_main_md2: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1610)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1650)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
	at androidx.navigation.fragment.NavHostFragment.onAttach(NavHostFragment.kt:110)
	at androidx.fragment.app.Fragment.performAttach(Fragment.java:3063)
	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
	at com.topjohnwu.magisk.arch.UIActivity.setContentView(UIActivity.kt:73)
	at com.topjohnwu.magisk.ui.MainActivity.showMainUI(MainActivity.kt:63)
	at com.topjohnwu.magisk.ui.SplashActivity.preLoad$lambda$6(SplashActivity.kt:126)
	at com.topjohnwu.magisk.ui.SplashActivity.$r8$lambda$DYu3vVnARbRWH2M0unFOv2EKWcU(Unknown Source:0)
	at com.topjohnwu.magisk.ui.SplashActivity$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8052)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

successfully reproduce.
