### ISSUE TITLE
Android 5.0 Compatibility

### ISSUE THREAD

**Issue by vvb2060** [topjohnwu/Magisk#5888]
- [x] #5793
The app won't start, crashes every time it launches.
    ```
    JNI DETECTED ERROR IN APPLICATION: can't call void android.view.View.setTranslationY(float) on null object
    ```

- [x] #5889
    ```
    Error: Unknown option: -p
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getType()' on a null object reference
            at com.android.commands.am.Am.runStart(Am.java:676)
            at com.android.commands.am.Am.onRun(Am.java:304)
            at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
            at com.android.commands.am.Am.main(Am.java:99)
            at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
            at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
    ```

- [x] Client cannot connect to `magiskd` when selinux is disabled
  https://github.com/topjohnwu/Magisk/blob/8a73a160293a9958baf21086e57c23f75b805b3c/native/jni/core/socket.cpp#L29-L30

- [x] #5834

    Some buttons do not support D-PAD

- [x] I think magiskinit will crash here when sepolicy fails to load (wontfix):
https://github.com/topjohnwu/Magisk/blob/622e09862a05c87b3d363c230fb02a49d5ff90bc/native/jni/init/selinux.cpp#L11-L15

- [x] Zygisk unable to turn on when no selinux:
https://github.com/topjohnwu/Magisk/blob/0b5f973b318c792de03ab65c074425a802396c0b/native/jni/zygisk/main.cpp#L15-L25

- [x] Incorrect background color
![Screenshot_1654018209](https://user-images.githubusercontent.com/26996262/171237258-a446d786-1c3a-4480-8079-9b76d35b2336.png)

- [x] Disabled Remove button not grayed out
![Screenshot_1654018574](https://user-images.githubusercontent.com/26996262/171240981-a93a838c-a17f-4262-baad-6668360ea76d.png)

- [x] Magisk app crashes when saving log
    ```
    E/App: java.io.FileNotFoundException: Invalid argument
            at android.os.Parcel.openFileDescriptor(Native Method)
            at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:253)
            at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:199)
            at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:916)
            at android.content.ContentResolver.openOutputStream(ContentResolver.java:686)
            at com.topjohnwu.magisk.core.utils.MediaStoreUtils.outputStream(MediaStoreUtils.kt:103)
            at com.topjohnwu.magisk.ui.log.LogViewModel$saveMagiskLog$1$1.invokeSuspend(LogViewModel.kt:64)
            at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
            at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
            at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
    ```

- [x] Snackbar shows behind the virtual key bar
![image](https://user-images.githubusercontent.com/31466456/171321136-83b4b41d-dcea-4311-80a2-5d10b1811012.png)

and more?

**Comment by vvb2060** [comment]
- [ ] Incorrect background color

![Screenshot_1654018209](https://user-images.githubusercontent.com/26996262/171237258-a446d786-1c3a-4480-8079-9b76d35b2336.png)

**Comment by vvb2060** [comment]
@topjohnwu How to test an app when su is not available. We don't have a real device for Android 5.0, should we drop support for it?

**Comment by Displax** [comment]
Can confirm that Magisk not work properly on 5.1. i have real device if need for testing, but is it worth?

**Comment by canyie** [comment]
- [ ] Magisk app crashes when saving log
```
E/App: java.io.FileNotFoundException: Invalid argument
        at android.os.Parcel.openFileDescriptor(Native Method)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:253)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:199)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:916)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:686)
        at com.topjohnwu.magisk.core.utils.MediaStoreUtils.outputStream(MediaStoreUtils.kt:103)
        at com.topjohnwu.magisk.ui.log.LogViewModel$saveMagiskLog$1$1.invokeSuspend(LogViewModel.kt:64)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by canyie** [comment]
- [ ] Snackbar shows behind the virtual key bar
![image](https://user-images.githubusercontent.com/31466456/171321136-83b4b41d-dcea-4311-80a2-5d10b1811012.png)

**Comment by yujincheng08** [comment]
All seem fixed.
