### ISSUE TITLE
White Blank Modules Tab

### ISSUE THREAD

**Issue by reiryuki** [topjohnwu/Magisk#5981]
Device: Xiaomi Redmi 4A (rolex)
Android version: 12.1
ROM: Nusantara Project
Magisk version name: cacf8736
Magisk version code: 25001

Modules tab in Magisk app is white blanked after the Magisk  app is re-opened sometime and doesn't show the modules list (unless I must go to the other tab of the app first, then modules list can be showed up). It happens both in the canary and the stable version.

![Screenshot_20220614-232504_Magisk](https://user-images.githubusercontent.com/46316533/173630140-5b224fe4-c641-4ef7-aba0-2598f48606b0.png)

[magisk_app_canary_version_logcat.txt](https://github.com/topjohnwu/Magisk/files/8901759/magisk_app_canary_version_logcat.txt)

[magisk_app_stable_version_logcat.txt](https://github.com/topjohnwu/Magisk/files/8901760/magisk_app_stable_version_logcat.txt)

[magisk_log_2022-06-14T23.29.31.log](https://github.com/topjohnwu/Magisk/files/8901762/magisk_log_2022-06-14T23.29.31.log)

I have another question. Can the update.json supports pling.com direct download? Because I uploads my modules to pling.com.

**Comment by osm0sis** [comment]
update.json supports anywhere that allows direct downloads. Mine point to xda attachments for example.

**Comment by reiryuki** [comment]
@osm0sis yes of course, but pling.com does not provide such a thing. I've tried to put direct link from pling but it's not detected by the magisk app.

**Comment by osm0sis** [comment]
Then it's not a direct link. 😉🙂

**Comment by vvb2060** [comment]
Do you have a way to reproduce it?

**Comment by reiryuki** [comment]
@vvb2060 yes usually it occurs while coming back to magisk app from recents or opening the app from launcher while the saved state of magisk app is still in "Modules" tab after the cached process is killed by system oom. This is the last log with the issue:
[logcat_06-15-2022_17-28-50.txt](https://github.com/topjohnwu/Magisk/files/8908467/logcat_06-15-2022_17-28-50.txt)
.

**Comment by reiryuki** [comment]
https://user-images.githubusercontent.com/46316533/173808122-15013b5c-15ec-4cb0-9176-6eb66279f1cb.mp4

**Comment by reiryuki** [comment]
Happens too in latest canary
MAGISK_VER='9183a0a6'
MAGISK_VER_CODE=25101
[logcat_06-23-2022_05-27-17.txt](https://github.com/topjohnwu/Magisk/files/8962220/logcat_06-23-2022_05-27-17.txt)

**Comment by canyie** [comment]
`FragmentActivity.onCreate()` recreates `ModuleFragment` which creates `ModuleViewModel`. At this time `RootService` is not yet ready, `RootUtils.fs == FileSystems.LOCAL` which have no permission to access `MAGISKTMP`. So `ModuleViewModel` thinks the device is not rooted and shows nothing.

**Comment by vvb2060** [comment]
```
09-02 20:02:34.073 25509 25509 D RootUtils$Connection: await
09-02 20:02:34.073 25509 25509 D RootUtils$Connection: java.lang.RuntimeException: onMainThread: true
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.core.utils.RootUtils$Connection.await(RootUtils.kt:116)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.core.utils.RootUtils$Companion.getFs(RootUtils.kt:128)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.core.model.module.LocalModule$Companion.loaded(LocalModule.kt:127)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.ui.module.ModuleViewModel.<init>(ModuleViewModel.kt:39)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at java.lang.Class.newInstance(Native Method)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.arch.VMFactory.create(ViewModelHolder.kt:40)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.lifecycle.ViewModelProvider$Factory$-CC.$default$create(ViewModelProvider.kt:83)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.arch.VMFactory.create(Unknown Source:0)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.ui.module.ModuleFragment$special$$inlined$viewModel$1.invoke(ViewModelHolder.kt:47)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.ui.module.ModuleFragment$special$$inlined$viewModel$1.invoke(ViewModelHolder.kt:46)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.ui.module.ModuleFragment.getViewModel(ModuleFragment.kt:19)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.ui.module.ModuleFragment.getViewModel(ModuleFragment.kt:16)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.arch.ViewModelHolder$DefaultImpls.startObserveLiveData(ViewModelHolder.kt:20)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.arch.BaseFragment.startObserveLiveData(BaseFragment.kt:16)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.arch.BaseFragment.onCreate(BaseFragment.kt:28)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2875)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1990)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.Fragment.onCreate(Fragment.java:1965)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:169)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2875)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.core.base.BaseActivity.onCreate(BaseActivity.kt:75)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.arch.UIActivity.onCreate(UIActivity.kt:42)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.topjohnwu.magisk.ui.SplashActivity.onCreate(SplashActivity.kt:43)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.Activity.performCreate(Activity.java:8000)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.Activity.performCreate(Activity.java:7984)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.os.Handler.dispatchMessage(Handler.java:106)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.os.Looper.loop(Looper.java:223)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at android.app.ActivityThread.main(ActivityThread.java:7656)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at java.lang.reflect.Method.invoke(Native Method)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-02 20:02:34.073 25509 25509 D RootUtils$Connection:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

`com.topjohnwu.magisk.ui.SplashActivity.onCreate(SplashActivity.kt:43)`

https://github.com/topjohnwu/Magisk/blob/6e299018a432deae49df454a9e5b5a2f9d57b9ce/app/src/main/java/com/topjohnwu/magisk/ui/SplashActivity.kt#L35-L61

**Comment by reiryuki** [comment]
Thanks for this fix. This is fixed and Magisk Delta also applies this fix syncing with Magisk Official update.

![Screenshot_20221202-202533~2](https://user-images.githubusercontent.com/46316533/205304455-2d7ca170-1897-4910-ab84-f037f0ec68d4.png)

And this is a similar case in the Home tab (Latest: N/A).
I know the screenshot is not from Magisk Official, But I think both of them are having the same issue. I'm using Magisk Delta right now but Magisk Delta also based on Magisk Official except for for some special features that I need.

[logcat_12-02-2022_20-37-56.txt](https://github.com/topjohnwu/Magisk/files/10141578/logcat_12-02-2022_20-37-56.txt)

[magisk_log_2022-12-02T20.55.33.log](https://github.com/topjohnwu/Magisk/files/10141603/magisk_log_2022-12-02T20.55.33.log)
