### ISSUE TITLE
Redmi Note 10 Pro isn't boot with Magisk v25 on Android 12

### ISSUE THREAD

**Issue by tony8077616** [topjohnwu/Magisk#6020]
Hello all
My friend who use Redmi Note 10 Pro with MIUI13 13.0.9.0(Android 12) but it always freeze at splash screen
I've already try with Magisk App patch boot.img and TWRP flash with apk package 

Same problem on MIUI13 13.0.10.0(Android 12)

-->
Here is the logcat
[logcat.log](https://github.com/topjohnwu/Magisk/files/8958251/logcat.log)

Device: Redmi Note 10 Pro
Android version: 12
Magisk version name: 25.1
Magisk version code: 4eb71830(25101)

**Comment by canyie** [comment]
```
06-22 21:39:11.006  2576  2576 E Zygote  : System zygote died with fatal exception
06-22 21:39:11.006  2576  2576 E Zygote  : java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Typeface.mStyle' on a null object reference
06-22 21:39:11.006  2576  2576 E Zygote  : 	at android.graphics.Typeface.create(Typeface.java:990)
06-22 21:39:11.006  2576  2576 E Zygote  : 	at android.graphics.Typeface.setSystemFontMap(Typeface.java:1531)
06-22 21:39:11.006  2576  2576 E Zygote  : 	at android.graphics.Typeface.loadPreinstalledSystemFontMap(Typeface.java:1614)
06-22 21:39:11.006  2576  2576 E Zygote  : 	at com.android.server.SystemServer.run(SystemServer.java:854)
06-22 21:39:11.006  2576  2576 E Zygote  : 	at com.android.server.SystemServer.main(SystemServer.java:619)
06-22 21:39:11.006  2576  2576 E Zygote  : 	at java.lang.reflect.Method.invoke(Native Method)
06-22 21:39:11.006  2576  2576 E Zygote  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
06-22 21:39:11.006  2576  2576 E Zygote  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
06-22 21:39:11.006  2576  2576 D AndroidRuntime: Shutting down VM
06-22 21:39:11.006  2576  2576 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
06-22 21:39:11.006  2576  2576 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Typeface.mStyle' on a null object reference
06-22 21:39:11.006  2576  2576 E AndroidRuntime: 	at android.graphics.Typeface.create(Typeface.java:990)
06-22 21:39:11.006  2576  2576 E AndroidRuntime: 	at android.graphics.Typeface.setSystemFontMap(Typeface.java:1531)
06-22 21:39:11.006  2576  2576 E AndroidRuntime: 	at android.graphics.Typeface.loadPreinstalledSystemFontMap(Typeface.java:1614)
06-22 21:39:11.006  2576  2576 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:854)
06-22 21:39:11.006  2576  2576 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:619)
06-22 21:39:11.006  2576  2576 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-22 21:39:11.006  2576  2576 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
06-22 21:39:11.006  2576  2576 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

**Comment by yujincheng08** [comment]
disable all your modules first.

**Comment by tony8077616** [comment]
Hi,
I've already delete all the modules from `/data/adb/modules`
And I've already use with 0b26882f debug version to flash and still can't boot.
Here are the log
[recovery.log](https://github.com/topjohnwu/Magisk/files/8976612/recovery.log)
[logcat.log](https://github.com/topjohnwu/Magisk/files/8976614/logcat.log)

**Comment by yujincheng08** [comment]
STOP lying:

> 02-18 14:40:19.810  1007  1009 I Magisk  : japanesehandwrite_font: loading mount files
