### ISSUE TITLE
MagiskManager NPE when entering input in downloads search field

### ISSUE THREAD

**Issue by Antoine-dh** [topjohnwu/Magisk#621]
using version 5.9.1 (139) on Xiaomi Redmi Note 4 with LineageOS 15.1 (Android 8.1)

> java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
        at com.topjohnwu.magisk.adapters.ReposAdapter.filter(ReposAdapter.java:134)
        at com.topjohnwu.magisk.fragments.ReposFragment$1.onQueryTextChange(ReposFragment.java:101)
        at android.widget.SearchView.onTextChanged(SearchView.java:1250)
        at android.widget.SearchView.-wrap9(Unknown Source:0)
        at android.widget.SearchView$8.onTextChanged(SearchView.java:1776)
        at android.widget.TextView.sendOnTextChanged(TextView.java:9364)
        at android.widget.TextView.handleTextChanged(TextView.java:9451)
        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:11926)
        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:341)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by vvb2060** [comment]
#620
