### ISSUE TITLE
Hidden app update (25203->25204) leads to "Full Magisk" screen loop

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#6317]
Device: ASUS ZenFone 4
Android version: 9
Magisk version name: c3b4678f
Magisk version code: 25204

After updating the app to the latest version, it hangs in a loop at the "Upgrade to full Magisk to finish the setup" screen, confirming just leads to the download prompt and then the same screen appears again. I restarted the device but the problem persists. The solution was to uninstall the hidden app and then install the updated apk.  After that it is possible to hide the app again.
[fullupgradeloop.txt](https://github.com/topjohnwu/Magisk/files/9758872/fullupgradeloop.txt)

**Comment by Displax** [comment]
Same on 25205

**Comment by yaoberh** [comment]
Same on a12 (sm-227m)

**Comment by osm0sis** [comment]
Yep, can confirm. I had to unhide the Magisk app to update, then rehide.

To break out of the loop you need to go to /data/user_de and find the hidden Magisk app's directory, and then put the 25203 .apk as dyn/current.apk with the correct app_### ownership.

**Comment by Rolodo** [comment]
A bit more details for people that like me who didn't know what to do.
I was able to find the version 25203 apk on some site... 
But @osm0sis not sure if we could provide the link to this version and maybe 25204.

I did the following with the apk version 25203 on my computer (as shell had root permission already), 
this could be done in a terminal emulator but it didn't have the permission;

```
adb shell
su
cp /storage/emulated/0/Download/25203.apk /data/user_de/0/[HIDDEN_NAME]/dyn/current.apk
cd /data/user_de/0/[HIDDEN_NAME]/dyn
chown u0_a254 current.apk
chgrp u0_a254 current.apk
chmod 7777 current.apk
```

Rebooted, waited, opened settings (the magisk app)
Unhid
Updated the magisk app
Updated the magisk boot
Rebooted
Not sure if those were the needed step but they worked for me...

Thanks

**Comment by SunsparcSolaris** [comment]
I encountered this but didn't see this issue before attempting to troubleshoot. Now I'm apparently stuck without root entirely as no version of patched boot.img will show Magisk installed. I have patched boot.img with 25200, 25201, 25203, and 25205. All of these versions show Magisk Installed: N/A after flashing via `fastboot flash boot` and then booting back into Android. I don't have root at all, so unable to try any fixes from above.

Pixel 6 (oriole), stock Android 12.1.0 (SQ3A.220705.004, Jul 2022)

**Comment by vith** [comment]
I was also able to break out of the loop thanks to the instructions shared here: putting the 25203 apk at `dyn/current.apk` to cancel the upgrade, but even after disabling Work Profile I still can't upgrade from 25203 to 25205 (at least without unhiding, which I'm avoiding trying because I don't want all my Google Wallet payment methods to get deauthorized, etc.).

Everything seems to be working fine for now anyway, so I guess I'll just wait to try future canary versions.

Model `Pixel 6`
Android version `13`
Security update `October 5, 2022`
Build number `TP1A.221005.002`

**Comment by osm0sis** [comment]
You can do anything you want with Airplane Mode on PlayIntegrity/SafetyNet-wise, and Google Wallet doesn't check for Magisk app anyway, so don't be afraid to unhide, update and rehide.

**Comment by vith** [comment]
Thanks, you were right about Airplane Mode. Upgraded without detection.

**Comment by leranp** [comment]
What can i do if I don't have root permission to a shell or explorer app to replace the file?
Is there any other option to fix it without uninstalling?

**Comment by Quu1337** [comment]
Deleted the hidden app in panic, reinstalled, had N/A. Flashed patched boot image and still have N/A.
No idea what to do. Terminal has root, adb shell doesnt.

**Comment by canyie** [comment]
```
java.lang.NullPointerException
    at java.lang.VMClassLoader.findLoadedClass(Native Method)
    at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
    at com.topjohnwu.magisk.AppClassLoader.loadClass(ClassLoaders.java:34)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at com.topjohnwu.magisk.DynLoad.createAndSetupApp(DynLoad.java:153)
    at com.topjohnwu.magisk.DelegateApplication.attachBaseContext(DelegateApplication.java:17)
    at android.app.Application.attach(Application.java:331)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6689)
    at android.app.ActivityThread.access$1500(ActivityThread.java:247)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7842)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
Looks like e9af773901888ade14bbc63365b81d38722e9235 caused this. That commit removed `android:appComponentFactory`  from `AndroidManifest.xml`, but the old stub app still tried to load it so got null pointer.
I believe this is not fixable except reverting that commit because we cannot fix an old version. The right way to update is that unhide the app before updating, or uninstall the hidden app, install the new one, then rehide.
Maybe we should add some warnings like what we do when v22.0 releases 🤔

**Comment by olesalscheider** [comment]
> Uninstalling the hidden app and downloading/installing the newest version again worked perfectly.

This might sound stupid, but how do I uninstall the hidden app? All I see is the updated magisk manager that won't start now... I don't know what the hidden name was - is there a way to figure this out afterwards?
