### ISSUE TITLE
bootloop full dumpstate

### ISSUE THREAD

**Issue by behomonth** [topjohnwu/Magisk#6435]
Hello,

I have ADB access for 3-5 minutes and then it cuts off. Waiting for your suggestions.

Thank you.

Device: Tablet 
Android version: 12
Magisk version name: a468fd94:MAGISK:D
Magisk version code: 25205
[dumpstate_sys_error.tmp.zip](https://github.com/topjohnwu/Magisk/files/10203330/dumpstate_sys_error.tmp.zip)

**Comment by yujincheng08** [comment]
Crash log:

```
12-11 23:44:07.073  1000   933   933 E WifiContext: Attempted to fetch resources before Wifi Resources APK is loaded!
12-11 23:44:07.073  1000   933   933 E WifiContext: java.lang.IllegalStateException
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.wifi.WifiContext.getWifiOverlayApkPkgName(WifiContext.java:71)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.wifi.WifiContext.getResourcesApkContext(WifiContext.java:93)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.wifi.WifiContext.getResources(WifiContext.java:120)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.wifi.WifiCarrierInfoManager.<init>(WifiCarrierInfoManager.java:296)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.wifi.WifiInjector.<init>(WifiInjector.java:266)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.wifi.WifiService.<init>(WifiService.java:48)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:154)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.SystemServiceManager.startServiceFromJar(SystemServiceManager.java:110)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2510)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.SystemServer.run(SystemServer.java:971)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.server.SystemServer.main(SystemServer.java:778)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at java.lang.reflect.Method.invoke(Native Method)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
12-11 23:44:07.073  1000   933   933 E WifiContext: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1108)
```

This is not magisk's issue.

**Comment by behomonth** [comment]
Magisk was in hidden state I started process to make it visible and then I lost the system.

I installed from scratch and now it's fine.

I don't think about hiding Magisk anymore.
