### ISSUE TITLE
LG V521 stuck on Magisk Logo

### ISSUE THREAD

**Issue by CourteousGeek** [topjohnwu/Magisk#6488]
Device: LG G Pad X 8.0
Android version: 7.0
Magisk version name: 831a398b
Magisk version code: 25206
Works fine with magisk v24.3
Using logcat reader.
[logcat_12-28-2022_12-44-02.txt](https://github.com/topjohnwu/Magisk/files/10315656/logcat_12-28-2022_12-44-02.txt)

**Comment by yujincheng08** [comment]
When stuck, run `kill -s SIGQUIT $(pidof com.topjohnwu.magisk)` as root and upload `/data/anr/`

**Comment by CourteousGeek** [comment]
Empty in /data/anr/ after running command as root.

**Comment by canyie** [comment]
```
01-02 12:06:08.743  2268  2268 D AndroidRuntime: Calling main entry com.topjohnwu.superuser.internal.RootServerMain
01-02 12:06:08.929  2268  2268 W ResourceType: No package identifier when getting value for resource number 0x00060035
01-02 12:06:08.930  2268  2268 E IPC     : Error in IPCMain
01-02 12:06:08.930  2268  2268 E IPC     : android.content.res.Resources$NotFoundException: Resource ID #0x60035
01-02 12:06:08.930  2268  2268 E IPC     : 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:208)
01-02 12:06:08.930  2268  2268 E IPC     : 	at android.content.res.Resources.getBoolean(Resources.java:1036)
01-02 12:06:08.930  2268  2268 E IPC     : 	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:454)
01-02 12:06:08.930  2268  2268 E IPC     : 	at android.app.LoadedApk.getClassLoader(LoadedApk.java:599)
01-02 12:06:08.930  2268  2268 E IPC     : 	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1919)
01-02 12:06:08.930  2268  2268 E IPC     : 	at android.app.LoadedApk.getResources(LoadedApk.java:812)
01-02 12:06:08.930  2268  2268 E IPC     : 	at android.app.ContextImpl.<init>(ContextImpl.java:2043)
01-02 12:06:08.930  2268  2268 E IPC     : 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:1847)
01-02 12:06:08.930  2268  2268 E IPC     : 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:1832)
01-02 12:06:08.930  2268  2268 E IPC     : 	at com.topjohnwu.superuser.internal.RootServerMain.<init>(SourceFile:6)
01-02 12:06:08.930  2268  2268 E IPC     : 	at com.topjohnwu.superuser.internal.RootServerMain.main(SourceFile)
01-02 12:06:08.930  2268  2268 E IPC     : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
01-02 12:06:08.930  2268  2268 E IPC     : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
01-02 12:06:08.931  2268  2268 I art     : System.exit called, status: 1
01-02 12:06:08.931  2268  2268 I AndroidRuntime: VM exiting with result code 1.
```

**Comment by canyie** [comment]
Can you upload `/system/framework/framework.jar`?

**Comment by CourteousGeek** [comment]
https://anonfiles.com/W7ZcO7Pfyd/framework_jar

**Comment by CourteousGeek** [comment]
> Can you upload `/system/framework/framework.jar`?
https://anonfiles.com/W7ZcO7Pfyd/framework_jar

**Comment by yujincheng08** [comment]
Upload the whole `/system/framework` directory

**Comment by CourteousGeek** [comment]
> Upload the whole `/system/framework` directory

https://anonfiles.com/bafaP6P4yf/framework_7z

**Comment by yujincheng08** [comment]
```java
    private void createOrUpdateClassLoaderLocked(List<String> addedPaths) {
        boolean isBundledApp;
        String zip;
        if (!this.mPackageName.equals(ZenModeConfig.SYSTEM_AUTHORITY)) {
            if (this.mIncludeCode && Resources.getSystem().getBoolean(R.bool.config_integrity_enabled) && ActivityThread.sIsIntegrityServiceEnabled > 0 && ((this.mApplicationInfo.flags & 128) == 128 || (this.mApplicationInfo.flags & 1) != 1)) {
                this.mIntegrityManager = IntegrityManager.getInstance(this.mActivityThread.getSystemContext());
                if (this.mIntegrityManager != null) {
                    switch (this.mIntegrityManager.verifyIntegrityForApplication(this.mApplicationInfo.packageName)) {
                        case -1:
                            Slog.w(TAG, "[LGIS] Block App Execution");
                            throw new SecurityException(this.mApplicationInfo.packageName + " is blocked for bad integrity");
                    }
                } else {
                    Slog.w(TAG, "[LGIS] LGIS is not working");
                }
            }
            if (!Objects.equals(this.mPackageName, ActivityThread.currentPackageName())) {
                VMRuntime.getRuntime().vmInstructionSet();
                try {
                    ActivityThread.getPackageManager().notifyPackageUse(this.mPackageName, 6);
                } catch (RemoteException re) {
                    throw re.rethrowFromSystemServer();
                }
            }
            if (this.mRegisterPackage) {
                try {
                    ActivityManagerNative.getDefault().addPackageDependency(this.mPackageName);
                } catch (RemoteException e) {
                    throw e.rethrowFromSystemServer();
                }
            }
            List<String> zipPaths = new ArrayList<>(10);
            List<String> libPaths = new ArrayList<>(10);
            makePaths(this.mActivityThread, this.mApplicationInfo, zipPaths, libPaths);
            if (this.mApplicationInfo.isSystemApp()) {
                isBundledApp = !this.mApplicationInfo.isUpdatedSystemApp();
            } else {
                isBundledApp = false;
            }
            String libraryPermittedPath = this.mDataDir;
            if (isBundledApp) {
                libraryPermittedPath = libraryPermittedPath + File.pathSeparator + System.getProperty("java.library.path");
            }
            String librarySearchPath = TextUtils.join(File.pathSeparator, libPaths);
            if (this.mIncludeCode) {
                if (zipPaths.size() == 1) {
                    zip = zipPaths.get(0);
                } else {
                    zip = TextUtils.join(File.pathSeparator, zipPaths);
                }
                boolean needToSetupJitProfiles = false;
                if (this.mClassLoader == null) {
                    StrictMode.ThreadPolicy oldPolicy = StrictMode.allowThreadDiskReads();
                    this.mClassLoader = ApplicationLoaders.getDefault().getClassLoader(zip, this.mApplicationInfo.targetSdkVersion, isBundledApp, librarySearchPath, libraryPermittedPath, this.mBaseClassLoader);
                    StrictMode.setThreadPolicy(oldPolicy);
                    needToSetupJitProfiles = true;
                }
                if (addedPaths != null && addedPaths.size() > 0) {
                    ApplicationLoaders.getDefault().addPath(this.mClassLoader, TextUtils.join(File.pathSeparator, addedPaths));
                    needToSetupJitProfiles = true;
                }
                if (needToSetupJitProfiles && !ActivityThread.isSystem()) {
                    setupJitProfileSupport();
                }
            } else if (this.mClassLoader == null) {
                StrictMode.ThreadPolicy oldPolicy2 = StrictMode.allowThreadDiskReads();
                this.mClassLoader = ApplicationLoaders.getDefault().getClassLoader(ProxyInfo.LOCAL_EXCL_LIST, this.mApplicationInfo.targetSdkVersion, isBundledApp, librarySearchPath, libraryPermittedPath, this.mBaseClassLoader);
                StrictMode.setThreadPolicy(oldPolicy2);
            }
        } else if (this.mClassLoader == null) {
            if (this.mBaseClassLoader != null) {
                this.mClassLoader = this.mBaseClassLoader;
            } else {
                this.mClassLoader = ClassLoader.getSystemClassLoader();
            }
        }
    }
```

**Comment by canyie** [comment]
How about this?
[app-release.zip](https://github.com/topjohnwu/Magisk/files/10334444/app-release.zip)

**Comment by Unknown78** [comment]
fwiw, it doesn't stuck, no conflict with your previous build, here's the log if you need it.
[PatchedBoot-debug_app_canyie_v5.log](https://github.com/topjohnwu/Magisk/files/10334752/PatchedBoot-debug_app_canyie_v5.log)

**Comment by CourteousGeek** [comment]
Good progress, Now this popup shows up in every reboot. ![Screenshot_2023-01-03-09-41-09](https://user-images.githubusercontent.com/77457021/210379457-2861ef64-f99c-4703-8851-fbba6689477c.png)

**Comment by canyie** [comment]
Ignore it for now, I'm not sure if my PR would gets merged
