### ISSUE TITLE
Magisk manager crashes on first open after install and uninstalls itself

### ISSUE THREAD

**Issue by BlazeCodeDev** [topjohnwu/Magisk#6580]
Device: Pixel 6 Pro
Android version: 13 (T2B3.230109.002)
Magisk version name: 831a398b
Magisk version code: 25206

**What is expected to happen:** 
1. Magisk manager installs successfully
2. On first open the app asks for permissions and proceeds to the main screen
3. The app stays installed

**What actually happens:**
1. Magisk manager installs successfully
2. On first open the app asks for notification permission and crashes shortly after
3. The app uninstalls itself

**Logcat:**
```
2023-02-01 22:24:54.679  1665-1746  ActivityManager         system_server                        I  Killing 29712:com.topjohnwu.magisk/u0a294 (adj 0): stop com.topjohnwu.magisk due to deletePackageX
```

[Full logat](https://pastebin.com/DmtAR1ux)

**Additional info:**

- Magisk manager is being installed after the device has been patched/rooted 
- Root access is in fact working, only the manager is crashing
- The app runs without crashes on the same build when it's unpatched/unrooted

**Comment by 0subzero** [comment]
Just had the same issue.
Not sure what happened but when i open the app it said something ...
Then i've just delete it and can't install again.
Installing - Open - Disappearing - installing ... etc ...

So finally fix was like rename Magisk-v25.2.apk to uninstaller.zip
goto TWRP, and install this zip.
So magisk was deleted.
Then i've rebooted to OS to check if it's still working :))
Then went back to twrp and install Magisk-v25.2.apk

If fixes the issue.
Have fun!

**Comment by BlazeCodeDev** [comment]
Unfortunately I didn't get an error message. I also don't use TWRP, I always patch my boot images, thanks anyway :)

**Comment by yujincheng08** [comment]
```
2023-02-01 22:24:54.679  1665-1746  ActivityManager         system_server                        I  Killing 29712:com.topjohnwu.magisk/u0a294 (adj 0): stop com.topjohnwu.magisk due to deletePackageX
```

This is because the signature verification fails or version code verification fails. Please make sure you install the official magisk app and patch your boot using the exact magisk app.

**Comment by BlazeCodeDev** [comment]
I used the official app from this repo and patched the image using that.

**Comment by Msprg** [comment]
I'm currently experiencing the exact same issue with Magisk 26000.

I've previously had the app hidden but the shortcut vanished with no way to get it back, while the official manager uninstalls itself instead.

I tried uninstalling from TWRP, reboot to system, install Magisk app, ... reboot to TWRP, install 26000 patched bootimage.

Only then the Magisk app seems to be content and is working as expected.

**Comment by alirezaazarm** [comment]
I have same issue with v27. I had it but i didnt know when i uninstalled it. when i tried to install it again, opened the app for first time and then it automatically uninstalled again ...

**Comment by Lesiuk** [comment]
Same issue on pixel 8 pro.

**Comment by Micha10** [comment]
Same issue with Oneplus 6T after updating to the latest version. Other already granted apps can get root. After starting the MM it is being deinstalled. Here are my logs:

`2024-12-16 19:19:54.988  1642-5399  ActivityTaskManager     system_server                        I  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.ui.MainActivity bnds=[471,775][575,1000]} with LAUNCH_MULTIPLE from uid 10445 (BAL_ALLOW_ALLOWLISTED_COMPONENT) result code=0
2024-12-16 19:19:54.989  3003-3088  WindowManagerShell      com.android.systemui                 V  Transition requested (#11): android.os.BinderProxy@ad5045c TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=3013 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.ui.MainActivity } baseActivity=ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity} topActivity=ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity} origActivity=null realActivity=ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity} numActivities=1 lastActiveTime=258334 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@f2f1365} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 79 - 0, 0) topActivityInfo=ActivityInfo{412383a com.topjohnwu.magisk.ui.MainActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1080 topActivityLetterboxHeight=2340 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 11 }
2024-12-16 19:19:54.992  1642-1789  ActivityManager         system_server                        I  Start proc 11245:com.topjohnwu.magisk/u0a590 for next-top-activity {com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}
2024-12-16 19:19:55.009  1642-5415  CoreBackPreview         system_server                        D  Window{cdcc3b8 u0 Splash Screen com.topjohnwu.magisk}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@f89dd93, mPriority=0, mIsAnimationCallback=false}
2024-12-16 19:19:55.012 11245-11245 opjohnwu.magisk         usap64                               I  Using CollectorTypeCC GC.
2024-12-16 19:19:55.016 11245-11245 opjohnwu.magisk         usap64                               E  Not starting debugger since process cannot load the jdwp agent.
2024-12-16 19:19:55.019  1642-1758  WindowManager           system_server                        V  Sent Transition (#11) createdAt=12-16 19:19:54.978 via request=TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=3013 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.ui.MainActivity } baseActivity=ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity} topActivity=ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity} origActivity=null realActivity=ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity} numActivities=1 lastActiveTime=258334 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{2fcc4ce Task{f253ee9 #3013 type=standard A=10590:com.topjohnwu.magisk}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 79 - 0, 0) topActivityInfo=ActivityInfo{b4a5b70 com.topjohnwu.magisk.ui.MainActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1080 topActivityLetterboxHeight=2340 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 11 }
2024-12-16 19:19:55.019  1642-1758  WindowManager           system_server                        V      info={id=11 t=OPEN f=0x0 trk=0 opt={t=SCALE_UP bounds=Rect(471, 775 - 831, 1555)} r=[0@Point(0, 0)] c=[
                                                                                                            {WCT{RemoteToken{2fcc4ce Task{f253ee9 #3013 type=standard A=10590:com.topjohnwu.magisk}}} m=OPEN f=NONE leash=Surface(name=Task=3013)/@0x1e851d0 sb=Rect(0, 0 - 1080, 2340) eb=Rect(0, 0 - 1080, 2340) d=0},
                                                                                                            {WCT{RemoteToken{328e1c1 Task{4ca3e3b #1 type=undefined}}} m=TO_BACK f=SHOW_WALLPAPER leash=Surface(name=Task=1)/@0x8fcf3b9 sb=Rect(0, 0 - 1080, 2340) eb=Rect(0, 0 - 1080, 2340) d=0}
                                                                                                        ]}
2024-12-16 19:19:55.071 11245-11245 nativeloader            usap64                               D  Configuring clns-4 for other apk /data/app/~~qOUFXHX36gy9Y0cNWRBbTA==/com.topjohnwu.magisk-K0hO1QDRDxtFKqFM6x_r4Q==/base.apk. target_sdk_version=35, uses_libraries=, library_path=/data/app/~~qOUFXHX36gy9Y0cNWRBbTA==/com.topjohnwu.magisk-K0hO1QDRDxtFKqFM6x_r4Q==/lib/arm64:/data/app/~~qOUFXHX36gy9Y0cNWRBbTA==/com.topjohnwu.magisk-K0hO1QDRDxtFKqFM6x_r4Q==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.topjohnwu.magisk
2024-12-16 19:19:55.082 11245-11245 GraphicsEnvironment     usap64                               V  com.topjohnwu.magisk is not listed in per-application setting
2024-12-16 19:19:55.125 11245-12460 ProfileInstaller        usap64                               D  Skipping profile installation for com.topjohnwu.magisk
2024-12-16 19:19:55.199  1642-5399  CoreBackPreview         system_server                        D  Window{4a8d33a u0 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@ac73bc7, mPriority=0, mIsAnimationCallback=false}
2024-12-16 19:19:55.835  1642-1788  ActivityManager         system_server                        I  Force stopping com.topjohnwu.magisk appid=10590 user=-1: deletePackageX
2024-12-16 19:19:55.842  1642-1788  ActivityManager         system_server                        I  Killing 11245:com.topjohnwu.magisk/u0a590 (adj 0): stop com.topjohnwu.magisk due to deletePackageX
2024-12-16 19:19:55.848  1642-1788  ActivityTaskManager     system_server                        W  Force removing ActivityRecord{1f480ed u0 com.topjohnwu.magisk/.ui.MainActivity t3013 f}}: app died, no saved state
2024-12-16 19:19:55.867  1642-5399  ActivityManager         system_server                        V  Got obituary of 11245:com.topjohnwu.magisk
2024-12-16 19:19:55.867  1642-4550  WindowManager           system_server                        I  WIN DEATH: Window{4a8d33a u0 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}
2024-12-16 19:19:55.867  1642-4550  InputManager-JNI        system_server                        W  Input channel object '4a8d33a com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity (client)' was disposed without first being removed with the input manager!
2024-12-16 19:19:55.911  1642-1758  WindowManager           system_server                        V      info={id=12 t=OPEN f=0x0 trk=0 r=[0@Point(0, 0)] c=[
                                                                                                            {WCT{RemoteToken{328e1c1 Task{4ca3e3b #1 type=undefined}}} m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1)/@0x8fcf3b9 sb=Rect(0, 0 - 1080, 2340) eb=Rect(0, 0 - 1080, 2340) d=0},
                                                                                                            {WCT{RemoteToken{2fcc4ce Task{f253ee9 #3013 type=standard A=10590:com.topjohnwu.magisk}}} m=CLOSE f=NONE leash=Surface(name=Task=3013)/@0x1e851d0 sb=Rect(0, 0 - 1080, 2340) eb=Rect(0, 0 - 1080, 2340) d=0},
                                                                                                            {null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{aa18adf token=android.os.Binder@5d5257e})/@0xeaa4acb sb=Rect(0, 0 - 1080, 2340) eb=Rect(0, 0 - 1080, 2340) d=0}
                                                                                                        ]}
2024-12-16 19:19:56.110  1642-1875  ActivityManager         system_server                        I  Force stopping com.topjohnwu.magisk appid=10590 user=0: pkg removed
2024-12-16 19:19:56.111  1642-1875  WindowManager           system_server                        I    Force removing ActivityRecord{1f480ed u0 com.topjohnwu.magisk/.ui.MainActivity t3013 f} isExiting}
2024-12-16 19:19:56.111  1642-1875  WindowManager           system_server                        W  removeAppToken: Attempted to remove non-existing token: Token{d3cf76e ActivityRecord{1f480ed u0 com.topjohnwu.magisk/.ui.MainActivity t3013 f} isExiting}}
2024-12-16 19:19:56.130  1642-1875  AppOps                  system_server                        E  package com.topjohnwu.magisk not found, can't check for attributionTag null
2024-12-16 19:19:56.130  1642-1875  AppOps                  system_server                        E  Bad call made by uid 1000. Package "com.topjohnwu.magisk" does not belong to uid 10590.
2024-12-16 19:19:56.131  1642-1875  AppOps                  system_server                        E  Cannot checkOperation
                                                                                                    java.lang.SecurityException: Specified package "com.topjohnwu.magisk" under uid 10590 but it is not
                                                                                                    	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:4541)
                                                                                                    	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:4401)
                                                                                                    	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:4393)
                                                                                                    	at com.android.server.appop.AppOpsService.checkOperationUnchecked(AppOpsService.java:2763)
                                                                                                    	at com.android.server.appop.AppOpsService.checkOperationImpl(AppOpsService.java:2745)
                                                                                                    	at com.android.server.appop.AppOpsService.-$$Nest$mcheckOperationImpl(AppOpsService.java:0)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.$r8$lambda$p7Z0eGBUU1-Gt7vHG9S-93UhGlY(AppOpsService.java:0)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher$$ExternalSyntheticLambda9.apply(R8$$SyntheticClass:0)
                                                                                                    	at com.android.server.policy.AppOpsPolicy.checkOperation(AppOpsPolicy.java:235)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.checkOperation(AppOpsService.java:7196)
                                                                                                    	at com.android.server.appop.AppOpsService.checkOperation(AppOpsService.java:2718)
                                                                                                    	at android.app.AppOpsManager.checkOpNoThrow(AppOpsManager.java:9273)
                                                                                                    	at android.app.AppOpsManager.checkOpNoThrow(AppOpsManager.java:9266)
                                                                                                    	at com.android.server.wm.ActivityTaskSupervisor.killTaskProcessesIfPossible(ActivityTaskSupervisor.java:1798)
                                                                                                    	at com.android.server.wm.ActivityTaskSupervisor.cleanUpRemovedTask(ActivityTaskSupervisor.java:1767)
                                                                                                    	at com.android.server.wm.ActivityTaskSupervisor.removeTask(ActivityTaskSupervisor.java:1713)
                                                                                                    	at com.android.server.wm.ActivityTaskSupervisor.removeTask(ActivityTaskSupervisor.java:1678)
                                                                                                    	at com.android.server.wm.RecentTasks.removeTasksByPackageName(RecentTasks.java:746)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService$LocalService.removeRecentTasksByPackageName(ActivityTaskManagerService.java:7131)
                                                                                                    	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:15265)
                                                                                                    	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14920)
                                                                                                    	at com.android.server.am.ActivityManagerService$LocalService.broadcastIntent(ActivityManagerService.java:18698)
                                                                                                    	at com.android.server.pm.BroadcastHelper.broadcastIntent(BroadcastHelper.java:220)
                                                                                                    	at com.android.server.pm.BroadcastHelper.doSendBroadcast(BroadcastHelper.java:191)
                                                                                                    	at com.android.server.pm.BroadcastHelper.sendPackageBroadcast(BroadcastHelper.java:138)
                                                                                                    	at com.android.server.pm.BroadcastHelper.lambda$sendPackageBroadcastAndNotify$5(BroadcastHelper.java:853)
                                                                                                    	at com.android.server.pm.BroadcastHelper.$r8$lambda$clcBGnQt-06kKHBsgiJHusWsyNs(BroadcastHelper.java:0)
                                                                                                    	at com.android.server.pm.BroadcastHelper$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                    	at com.android.server.ServiceThread.run(ServiceThread.java:46)
2024-12-16 19:19:56.133  1642-1875  ActivityManager         system_server                        I  Force stopping com.topjohnwu.magisk appid=10590 user=0: pkg removed
2024-12-16 19:19:56.134  1642-1875  WindowManager           system_server                        I    Force removing ActivityRecord{1f480ed u0 com.topjohnwu.magisk/.ui.MainActivity t3013 f} isExiting}
2024-12-16 19:19:56.134  1642-1875  WindowManager           system_server                        W  removeAppToken: Attempted to remove non-existing token: Token{d3cf76e ActivityRecord{1f480ed u0 com.topjohnwu.magisk/.ui.MainActivity t3013 f} isExiting}}
2024-12-16 19:19:56.149  1642-2808  StorageManagerService   system_server                        V  Package com.topjohnwu.magisk does not have legacy storage
2024-12-16 19:19:56.155  1642-2762  InputManager-JNI        system_server                        W  Input channel object 'cdcc3b8 Splash Screen com.topjohnwu.magisk (client)' was disposed without first being removed with the input manager!
2024-12-16 19:19:56.192  3290-3290  CarrierSvcBindHelper    com.android.phone                    D  onPackageRemoved: com.topjohnwu.magisk
2024-12-16 19:19:56.201  1642-2773  RollbackManager         system_server                        I  broadcast=ACTION_PACKAGE_FULLY_REMOVED pkg=com.topjohnwu.magisk
2024-12-16 19:19:56.209  1642-2816  WifiService             system_server                        W  Couldn't get PackageInfo for package:com.topjohnwu.magisk
2024-12-16 19:19:56.209  1642-2816  WifiService             system_server                        D  Remove settings for package:com.topjohnwu.magisk
2024-12-16 19:19:56.209  1642-2816  WifiConfigManager       system_server                        D  Remove all networks for app ApplicationInfo{430f814 com.topjohnwu.magisk}
2024-12-16 19:19:56.223  6333-6333  Finsky:background       com.android.vending                  I  [2] aamx.C(82): Package no longer installed: com.topjohnwu.magisk
2024-12-16 19:19:56.235  1642-2816  PasspointManager        system_server                        I  No app ops listener found for com.topjohnwu.magisk
2024-12-16 19:19:56.235  1642-2816  WifiService             system_server                        W  Couldn't get PackageInfo for package:com.topjohnwu.magisk
2024-12-16 19:19:56.235  1642-2816  WifiService             system_server                        D  Remove settings for package:com.topjohnwu.magisk
2024-12-16 19:19:56.235  1642-2816  WifiConfigManager       system_server                        D  Remove all networks for app ApplicationInfo{fe64ab0 com.topjohnwu.magisk}
2024-12-16 19:19:56.236  6333-6333  Finsky:background       com.android.vending                  I  [2] unk.d(69): IQ: onPackageRemoved com.topjohnwu.magisk, replacing=false, uninstallingFromPlay=false
2024-12-16 19:19:56.244  1642-2816  PasspointManager        system_server                        I  No app ops listener found for com.topjohnwu.magisk
2024-12-16 19:19:56.257  3705-12523 ProximityAuth           com.google.android.gms.persistent    I  [RecentAppsMediator] Package removed: (user=UserHandle{0}) com.topjohnwu.magisk
2024-12-16 19:19:56.258  6333-6333  Finsky:background       com.android.vending                  I  [2] aamx.C(82): Package no longer installed: com.topjohnwu.magisk
2024-12-16 19:19:56.270  5710-5710  Finsky                  com.android.vending                  I  [2] meb.f(7): AIM: AppInfoCacheUpdater -> invalidating apps: [com.topjohnwu.magisk]
2024-12-16 19:19:56.366  3939-12046 WorkSourceUtil          com.google.android.gms               E  Could not find package: com.topjohnwu.magisk
2024-12-16 19:19:56.375  3939-12553 Icing                   com.google.android.gms               I  doRemovePackageData com.topjohnwu.magisk
2024-12-16 19:19:56.509  3939-12529 SQLiteLog               com.google.android.gms               W  (28) double-quoted string literal: "com.topjohnwu.magisk"
2024-12-16 19:19:56.515  6333-6380  Finsky:background       com.android.vending                  I  [327] zxk.ks(139): aalm - recording uninstall for com.topjohnwu.magisk on [7QK964wyFxQJU3L0bth1W-ZVquzHHQ9UkNRFYf2Mquo]
2024-12-16 19:19:56.558  5710-6088  Finsky                  com.android.vending                  I  [330] mfy.a(47): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.topjohnwu.magisk]
2024-12-16 19:19:56.756  6333-6333  Finsky:background       com.android.vending                  I  [2] aamx.C(82): Package no longer installed: com.topjohnwu.magisk
2024-12-16 19:19:56.775  5710-12595 Finsky                  com.android.vending                  I  [404] az.a(21): Asset module storage cleared for package com.topjohnwu.magisk.
2024-12-16 19:19:56.988  5710-6003  Finsky                  com.android.vending                  I  [318] mfy.a(47): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.topjohnwu.magisk]
2024-12-16 19:19:56.995  1642-1642  Telecom                 system_server                        I  CarModeTracker: Package com.topjohnwu.magisk is not tracked.: SSH.oR@AWM
2024-12-16 19:19:57.033  1642-1642  ConditionProviders      system_server                        I  Disallowing condition provider com.topjohnwu.magisk (userSet: true)
2024-12-16 19:19:57.065  5710-5710  Finsky                  com.android.vending                  W  [2] agxc.b(126): STU: Failed to get storage stats for package 'com.topjohnwu.magisk' (1601: Error getting stats: android.content.pm.PackageManager.NameNotFoundException)
2024-12-16 19:19:57.140  4341-4341  AiAiEcho                com.google.android.as                I  AppFetcherImplV2 onPackageRemoved com.topjohnwu.magisk.
2024-12-16 19:19:57.223  2930-2930  PersistedS...edReceiver com.android.permissioncontroller     D  Received android.intent.action.PACKAGE_FULLY_REMOVED for com.topjohnwu.magisk for u0
2024-12-16 19:19:57.713  4371-5339  MediaProvider           com.android.providers.media.module   D  Deleted 0 Android/media items belonging to com.topjohnwu.magisk on /data/user/0/com.android.providers.media.module/databases/external.db
2024-12-16 19:19:57.986  4371-5339  MediaProvider           com.android.providers.media.module   D  Orphaned 2 items belonging to com.topjohnwu.magisk on /data/user/0/com.android.providers.media.module/databases/external.db
2024-12-16 19:19:57.992  4371-5339  FuseDaemon              com.android.providers.media.module   I  Successfully deleted rows in leveldb for owner_id: 650 and ownerPackageIdentifier: com.topjohnwu.magisk::0
2024-12-16 19:19:57.996  4371-5339  MediaGrants             com.android.providers.media.module   D  Removed 0 media_grants for 0 user for [com.topjohnwu.magisk]. Reason: Package orphaned`
