### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by vvb2060** [topjohnwu/Magisk#6836]
```
04-06 13:49:00.396 28394 28394 E AndroidRuntime: java.lang.UnsupportedOperationException
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at java.util.AbstractList.remove(AbstractList.java:167)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at java.util.AbstractList$Itr.remove(AbstractList.java:387)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at kotlin.collections.CollectionsKt__MutableCollectionsKt.filterInPlace$CollectionsKt__MutableCollectionsKt(CollectionsKt__MutableCollections.kt:0)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at kotlin.collections.CollectionsKt__MutableCollectionsKt.filterInPlace$CollectionsKt__MutableCollectionsKt(CollectionsKt__MutableCollections.kt:0)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at kotlin.collections.CollectionsKt__MutableCollectionsKt.removeAll(CollectionsKt__MutableCollections.kt:0)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at com.topjohnwu.magisk.ui.superuser.SuperuserViewModel$deletePressed$updateState$1.invokeSuspend(SuperuserViewModel.java:0)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.q(BaseContinuationImpl.java:6)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:0)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at android.os.Looper.loop(Looper.java:223)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7656)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-06 13:49:00.396 28394 28394 E AndroidRuntime: Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5546994, Dispatchers.Main.immediate]
```

**Comment by topjohnwu** [comment]
Fixed with 7be958e35da7225a753ed7c73887b729c8d54b64
