### ISSUE TITLE
[Bug] Magisk placeholder app crashes on v26.1

### ISSUE THREAD

**Issue by galaxy4627** [topjohnwu/Magisk#7044]
Device: Nintendo Switch (icosa)
Android version: 10
Magisk version name: 26.1
Magisk version code: 26102

On newer versions of Magisk >v26.0 the placeholder app crashes, this issue does not occur on v25.2.

Crash Log:

```
06-03 19:01:18.692  6777  6777 E opjohnwu.magis: No package ID 7f found for ID 0x7f010003.
06-03 19:01:18.692  6777  6777 D AndroidRuntime: Shutting down VM
06-03 19:01:18.693  6777  6777 E AndroidRuntime: FATAL EXCEPTION: main
06-03 19:01:18.693  6777  6777 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 6777
06-03 19:01:18.693  6777  6777 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.topjohnwu.magisk/x.COMPONENT_PLACEHOLDER_2}: android.content.res.Resources$NotFoundException: String resource ID #0x7f010003
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
06-03 19:01:18.693  6777  6777 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f010003
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.content.res.Resources.getText(Resources.java:367)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.content.res.Resources.getString(Resources.java:460)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.content.Context.getString(Context.java:639)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at x.E(SourceFile:1)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at x.onCreate(SourceFile:4)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7824)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7813)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
06-03 19:01:18.693  6777  6777 E AndroidRuntime:        ... 11 more
06-03 19:01:18.695  3372  4277 W ActivityTaskManager:   Force finishing activity com.topjohnwu.magisk/x.COMPONENT_PLACEHOLDER_2
```

**Comment by yujincheng08** [comment]
Looks like you are not using the debug version. Please use the debug version to report bugs.
