### ISSUE TITLE
Patch boot error     There is also an error when opening stub.apk

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#7117]
Device:Lenovo L78071
Android version:10
Magisk version name:a8c4a33e
Magisk version code:26103

```
- Device platform: arm64-v8a
- Installing: a8c4a33e (26103)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [11686759]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [1236914]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-06]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xA90000 androidboot.hardware=qcom androidboot.console=ttyMSM0 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 service_locator.enable=1 androidboot.configfs=true androidboot.usbcontroller=a600000.dwc3 swiotlb=1 loop.max_part=7 buildvariant=user]
CHECKSUM        [6417e2f884e0f7b8bb394651103c3f5afd586c47000000000000000000000000]
KERNEL_FMT      [gzip]
VBMETA
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
resetprop: get prop [ro.crypto.state]: [encrypted]
 preinit device: cache
- Pre-init storage partition: cache
 Add file [init] (100750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add file [overlay.d/sbin/magisk32.xz] (100644)
Add file [overlay.d/sbin/magisk64.xz] (100644)
Add file [overlay.d/sbin/stub.xz] (100644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Failed to process cpio: No such file or directory (os error 2)
! Unable to patch ramdisk
! Installation failed


```

Stub cannot be opened properly. Once the manager is uninstalled, it is not possible to install the manager through stub
https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/stub-debug.apk
```
06-25 11:20:33.175 22713 22713 D AndroidRuntime: Shutting down VM
06-25 11:20:33.176 22713 22713 E AndroidRuntime: FATAL EXCEPTION: main
06-25 11:20:33.176 22713 22713 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 22713
06-25 11:20:33.176 22713 22713 E AndroidRuntime: android.content.res.Resources$NotFoundException: String resource ID #0x7f010003
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at android.content.res.Resources.getText(Resources.java:367)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at android.content.res.Resources.getString(Resources.java:460)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at android.content.Context.getString(Context.java:639)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at com.topjohnwu.magisk.DownloadActivity.showDialog(DownloadActivity.java:118)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at com.topjohnwu.magisk.DownloadActivity.lambda$fetchCanary$4(DownloadActivity.java:130)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at com.topjohnwu.magisk.DownloadActivity.$r8$lambda$GhMLn7DCagaMTCcQLXOrMkLfuwE(Unknown Source:0)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at com.topjohnwu.magisk.DownloadActivity$$ExternalSyntheticLambda4.onResponse(Unknown Source:4)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at com.topjohnwu.magisk.net.Request.lambda$submit$2(Request.java:153)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at com.topjohnwu.magisk.net.Request$$ExternalSyntheticLambda7.run(Unknown Source:4)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-25 11:20:33.176 22713 22713 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)

```

**Comment by androiddisk** [comment]
[boot.zip](https://github.com/topjohnwu/Magisk/files/11858693/boot.zip)

**Comment by yujincheng08** [comment]
#7109

**Comment by androiddisk** [comment]
> Duplicate of #7109

The error reported by the stub is not a duplicate, is it

**Comment by yujincheng08** [comment]
> > Duplicate of #7109
> 
> The error reported by the stub is not a duplicate, is it

#7118
