### ISSUE TITLE
Bootloop on ZTE RedMagic 5s using magisk 26400/26401

### ISSUE THREAD

**Issue by happyme531** [topjohnwu/Magisk#7557]
Device: ZTE RedMagic 5s (NX659J)
Android version: 11
Magisk version name: aa6c7c15:MAGISK:D
Magisk version code: 26401

I'm using Magisk 25.2 before, and after upgrading to 26.4, the device can't boot properly, result in a black screen not responding to any action except long pressing power botton showing a power menu. ADB works fine. 
After disabling all modules the issue still exists, entering Android safe mode does not work either.
Flashing the old Magisk 25.2-patched boot.img back to device solves the issue.

Log files:
[dmesg.log](https://github.com/topjohnwu/Magisk/files/13464293/dmesg.log)
[logcat.zip](https://github.com/topjohnwu/Magisk/files/13464323/logcat.zip)

/proc/mounts:
```                                                                                                                                                                               
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,size=5952880k,nr_inodes=1488220,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600,ptmxmode=000 0 0
proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
tmpfs /mnt tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=5952880k,nr_inodes=1488220,mode=755,gid=1000 0 0
/dev/block/by-name/metadata /metadata ext4 rw,seclabel,nosuid,nodev,noatime,discard 0 0
/dev/block/dm-5 / ext4 ro,seclabel,nodev,relatime,discard 0 0
/dev/block/dm-6 /system_ext ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-7 /product ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-8 /vendor ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-9 /odm ext4 ro,seclabel,relatime,discard 0 0
tmpfs /apex tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=5952880k,nr_inodes=1488220,mode=755 0 0
tmpfs /linkerconfig tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=5952880k,nr_inodes=1488220,mode=755 0 0
tmpfs /mnt/installer tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=5952880k,nr_inodes=1488220,mode=755,gid=1000 0 0
tmpfs /mnt/androidwritable tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=5952880k,nr_inodes=1488220,mode=755,gid=1000 0 0
/dev/block/dm-5 /apex/com.android.os.statsd ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.resolv ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.adbd ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.sdkext ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.art ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.wifi ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.extservices ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.conscrypt ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.i18n ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.media.swcodec ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.vndk.v30 ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.mediaprovider ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.ipsec ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.tzdata ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.tethering ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.media ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.neuralnetworks ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.permission ext4 ro,seclabel,relatime,discard 0 0
/dev/block/dm-5 /apex/com.android.runtime ext4 ro,seclabel,relatime,discard 0 0
none /dev/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
none /dev/cg2_bpf cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
none /dev/cpuctl cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
none /acct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
none /dev/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0
none /dev/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
none /dev/memcg cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
none /dev/stune cgroup rw,nosuid,nodev,noexec,relatime,schedtune 0 0
tmpfs /linkerconfig tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=5952880k,nr_inodes=1488220,mode=755 0 0
tracefs /sys/kernel/tracing tracefs rw,seclabel,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
none /config configfs rw,nosuid,nodev,noexec,relatime 0 0
binder /dev/binderfs binder rw,relatime,max=1048576,stats=global 0 0
none /sys/fs/fuse/connections fusectl rw,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,seclabel,relatime 0 0
/dev/block/bootdevice/by-name/cache /cache ext4 rw,seclabel,nosuid,nodev,noatime 0 0
/dev/block/bootdevice/by-name/persist /mnt/vendor/persist ext4 rw,seclabel,nosuid,nodev,noatime 0 0
/dev/block/bootdevice/by-name/modem /vendor/firmware_mnt vfat ro,context=u:object_r:firmware_file:s0,relatime,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro 0 0
/dev/block/bootdevice/by-name/dsp /vendor/dsp ext4 ro,seclabel,nosuid,nodev,relatime 0 0
/dev/block/bootdevice/by-name/bluetooth /vendor/bt_firmware vfat ro,context=u:object_r:bt_firmware_file:s0,relatime,uid=1002,gid=3002,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro 0 0
/dev/block/bootdevice/by-name/userdata /data f2fs rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,fsync_mode=nobarrier 0 0
/dev/block/bootdevice/by-name/userdata /data/user/0 f2fs rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,fsync_mode=nobarrier 0 0
tmpfs /data_mirror tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=5952880k,nr_inodes=1488220,mode=700,gid=1000 0 0
/dev/block/bootdevice/by-name/userdata /data_mirror/data_ce/null f2fs rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,fsync_mode=nobarrier 0 0
/dev/block/bootdevice/by-name/userdata /data_mirror/data_ce/null/0 f2fs rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,fsync_mode=nobarrier 0 0
/dev/block/bootdevice/by-name/userdata /data_mirror/data_de/null f2fs rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,fsync_mode=nobarrier 0 0
/dev/block/bootdevice/by-name/userdata /data_mirror/cur_profiles f2fs rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,fsync_mode=nobarrier 0 0
tmpfs /storage tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=5952880k,nr_inodes=1488220,mode=755,gid=1000 0 0
adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
diag /dev/ffs-diag functionfs rw,relatime 0 0
diag_mdm /dev/ffs-diag-1 functionfs rw,relatime 0 0
diag_mdm2 /dev/ffs-diag-2 functionfs rw,relatime 0 0
/data/incremental/MT_data_app_vmdl729/backing_store /data/incremental/MT_data_app_vmdl729/mount incremental-fs rw,seclabel,nosuid,nodev,noatime,read_timeout_ms=10000,readahead=0 0 0
/data/incremental/MT_data_app_vmdl729/backing_store /data/app/~~QVMbyy0jAzhFyllEayxaOg== incremental-fs rw,seclabel,nosuid,nodev,noatime,read_timeout_ms=10000,readahead=0 0 0
/data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/full/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/dev/fuse /mnt/user/0/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/installer/0/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/androidwritable/0/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /storage/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/data/media /mnt/pass_through/0/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/0/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /storage/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/0/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/0/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/0/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /storage/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/0/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/0/emulated/0/nubialog sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /storage/emulated/0/nubialog sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/0/emulated/0/nubialog sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/0/emulated/0/nubialog sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/0/emulated/0/tencent sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /storage/emulated/0/tencent sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/0/emulated/0/tencent sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/0/emulated/0/tencent sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/0/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/dev/fuse /mnt/user/10/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/installer/10/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/androidwritable/10/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/data/media /mnt/pass_through/10/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/10/emulated/10/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/10/emulated/10/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/10/emulated/10/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/10/emulated/10/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/10/emulated/10/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/10/emulated/10/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
```

**Comment by happyme531** [comment]
Magisk 26.3/26300 Works fine.

**Comment by Unknown78** [comment]
Please try [the latest successful build that was pushed by topjohnwu](https://github.com/topjohnwu/Magisk/actions/workflows/build.yml?query=branch%3Amaster+is%3Asuccess+event%3Apush+actor%3Atopjohnwu).
> Currently it is [cfb20b0f86414d851b51e10cd633328d405ca4f7](https://github.com/topjohnwu/Magisk/suites/18073040664/artifacts/1041400471)

Click to download, extract the .zip file, you'll find the .apk to install.
Unhide and uninstall previous installation of Magisk.
Install it to get the App and do Direct-Install patch as usual.
If `app-release.apk` didn't work, try `app-debug.apk`. Both App and Direct-Install patch.

<hr>

If those didn't work, then we need logs with App and Direct-Install from that `app-debug.apk`.

Desktop requirements:
- Phone USB Drivers Installed
- `adb` from [Android SDK Platform-Tools](https://developer.android.com/tools/releases/platform-tools#downloads)

Phone requirements:
- USB Debugging enabled
- USB Debugging authorized/allowed the Desktop
- Superuser granted the `com.android.shell` (`adb shell`)

Steps:
1. Turn off the phone.
2. On the desktop, open terminal/shell/cmd
3. Change directory to the extracted `platform-tools` folder.
4. Enter `adb logcat > logcat.log`
5. Connect the phone to desktop.
6. Turn on the phone

If it doesn't bootloop:
> 7. Wait till home shows up + another 60 seconds,
> 8.  If you're **able** to open Magisk App, then go to Logs, tap the diskette icon. Get `magisk_log_dateTtime.log` in your internal storage Download folder.
> 9. Back to desktop, press `CTRL+C`
> 10. If earlier you're **not able** to open Magisk App, enter `adb shell su -c cat /cache/magisk.log > magisk.log`
> 11. Enter `adb shell su -c dmesg > dmesg.log`
> 12. Enter `adb shell su -c cat /proc/mounts > proc_mounts.log`
> 13. Restart the phone, wait till power on, and then enter `adb wait-for-device shell su -c cat /proc/last_kmsg > last_kmsg.log`

If it does bootloop:
> 7. Wait till it restart itself
> 8. Back to desktop, press `CTRL+C`
> 9. Enter `adb wait-for-device shell su -c cat /cache/magisk.log > magisk.log`
> 10. Enter `adb wait-for-device shell su -c dmesg > dmesg.log`
> 11. Enter `adb wait-for-device shell su -c cat /proc/mounts > proc_mounts.log`
> 12. Enter `adb wait-for-device shell su -c cat /proc/last_kmsg > last_kmsg.log`

Attach all the log files here.

**Comment by yujincheng08** [comment]
```
11-25 22:06:09.612   766   766 D Magisk  : zygisk64: pre  forkAndSpecialize [cn.nubia.theme.apply]
11-25 22:06:09.614   766   766 D Zygote  : Forked child process 2499
11-25 22:06:09.615  1686  1750 I ActivityManager: Start proc 2499:cn.nubia.theme.apply/1000 for service {cn.nubia.theme.apply/cn.nubia.theme.apply.ThemeApplyService}
11-25 22:06:09.615  2499  2499 W Zygote  : Unable to open libbeluga.so: dlopen failed: library "libbeluga.so" not found.
11-25 22:06:09.616  2499  2499 F zygote64: jni_internal.cc:729] JNI FatalError called: (zygote) Failed dup3() on descriptor 4: Invalid argument
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655] Runtime aborting...
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655] Dumping all threads without mutator lock held
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655] All threads:
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655] DALVIK THREADS (1):
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655] "main" prio=5 tid=1 Runnable
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x71f55338 self=0xb400007d8ccd2c00
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | sysTid=766 nice=0 cgrp=default sched=0/0 handle=0x7e13e974f8
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | stack=0x7fcf786000-0x7fcf788000 stackSize=8192KB
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | held mutexes= "abort lock" "mutator lock"(shared held)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   native: (backtrace::Unwind failed for thread 766: Thread doesn't exist)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native method)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:352)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteConnection.processOneCommand(ZygoteConnection.java:257)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:546)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655] 
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655] Aborting thread:
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655] "main" prio=5 tid=1 Native
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x71f55338 self=0xb400007d8ccd2c00
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | sysTid=766 nice=0 cgrp=default sched=0/0 handle=0x7e13e974f8
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | stack=0x7fcf786000-0x7fcf788000 stackSize=8192KB
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   | held mutexes= "abort lock"
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   native: (backtrace::Unwind failed for thread 766: Thread doesn't exist)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native method)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:352)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteConnection.processOneCommand(ZygoteConnection.java:257)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:546)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
11-25 22:06:09.621  2499  2499 F zygote64: runtime.cc:655] 
11-25 22:06:09.621  2499  2499 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 2499 (main), pid 2499 (main)
11-25 22:06:09.639  2507  2507 I crash_dump64: performing dump of process 2499 (target tid = 2499)
11-25 22:06:09.642  2507  2507 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-25 22:06:09.642  2507  2507 F DEBUG   : Build fingerprint: 'nubia/NX659J/NX659J:11/RKQ1.200826.002/nubia.20210910.215452:user/release-keys'
11-25 22:06:09.642  2507  2507 F DEBUG   : Revision: '0'
11-25 22:06:09.642  2507  2507 F DEBUG   : ABI: 'arm64'
11-25 22:06:09.642  2507  2507 F DEBUG   : Timestamp: 2023-11-25 22:06:09+0800
11-25 22:06:09.642  2507  2507 F DEBUG   : pid: 2499, tid: 2499, name: main  >>> zygote64 <<<
11-25 22:06:09.642  2507  2507 F DEBUG   : uid: 0
11-25 22:06:09.642  2507  2507 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-25 22:06:09.642  2507  2507 F DEBUG   : Abort message: 'JNI FatalError called: (zygote) Failed dup3() on descriptor 4: Invalid argument'
11-25 22:06:09.642  2507  2507 F DEBUG   :     x0  0000000000000000  x1  00000000000009c3  x2  0000000000000006  x3  0000007fcff81c30
11-25 22:06:09.642  2507  2507 F DEBUG   :     x4  0000007e13da2000  x5  0000007e13da2000  x6  0000007e13da2000  x7  00000000000024d8
11-25 22:06:09.642  2507  2507 F DEBUG   :     x8  00000000000000f0  x9  e0450246456639a1  x10 0000000000000000  x11 ffffffc0fffffbdf
11-25 22:06:09.642  2507  2507 F DEBUG   :     x12 0000000000000001  x13 0000000000000886  x14 0024b769fa81c000  x15 0000554916d4c99a
11-25 22:06:09.642  2507  2507 F DEBUG   :     x16 0000007e0f693958  x17 0000007e0f6726b0  x18 0000007e13064000  x19 00000000000009c3
11-25 22:06:09.642  2507  2507 F DEBUG   :     x20 00000000000009c3  x21 00000000ffffffff  x22 0000007d8c1be60d  x23 0000000000000016
11-25 22:06:09.642  2507  2507 F DEBUG   :     x24 0000007d8c19e2e7  x25 0000000000000001  x26 0000007d8c1b539f  x27 0000007d8c7bb000
11-25 22:06:09.642  2507  2507 F DEBUG   :     x28 b400007d8cd19360  x29 0000007fcff81cb0
11-25 22:06:09.642  2507  2507 F DEBUG   :     lr  0000007e0f625f20  sp  0000007fcff81c10  pc  0000007e0f625f4c  pst 0000000000001000
```

**Comment by yujincheng08** [comment]
fixed
