### ISSUE TITLE
Magisk crash during install

### ISSUE THREAD

**Issue by fernando-carvalho-91** [topjohnwu/Magisk#7838]
Device: Samsung S24 Ultra (SM-S928B)
Android version: 14
Magisk version name: 3d91a561
Magisk version code: 27001

[Image 1](https://ibb.co/StHmnnV)

[samsung-SM-S928B-Android-14_2024-02-21_141456.zip](https://github.com/topjohnwu/Magisk/files/14360728/samsung-SM-S928B-Android-14_2024-02-21_141456.zip)

After clicking "Let's go" for patching the AP this error occurs.

```
java.lang.IndexOutOfBoundsException
                                                                                                    	at java.io.BufferedInputStream.read(BufferedInputStream.java:331)
                                                                                                    	at java.io.FilterInputStream.read(FilterInputStream.java:133)
                                                                                                    	at org.kamranzafar.jtar.TarInputStream.read(TarInputStream.java:99)
                                                                                                    	at java.io.FilterInputStream.read(FilterInputStream.java:107)
                                                                                                    	at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:106)
                                                                                                    	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.processTar(MagiskInstaller.kt:231)
                                                                                                    	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:410)
                                                                                                    	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchFile(MagiskInstaller.kt:536)
                                                                                                    	at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:584)
                                                                                                    	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:553)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f56a525, Dispatchers.Main.immediate]
```

**Comment by yujincheng08** [comment]
r u sure the tar is not broken?

**Comment by fernando-carvalho-91** [comment]
> r u sure the tar is not broken?

I'm sure the tar is not broken!

Downloaded again the image (S928BXXU1AWM9_S928BOXM1AWM9_EUX) and tried again... same error.

**Comment by vvb2060** [comment]
https://appcenter.ms/users/vvb2060/apps/Magisk/crashes/errors/318435481u/reports/2516943348496829999-2d35f6aa-6203-48e7-93e4-b18a07312b84/attachments
