### ISSUE TITLE
Hide magisk app feature not work on canary version 27002

### ISSUE THREAD

**Issue by kaisar945** [topjohnwu/Magisk#7982]
Device: OnePlus 11
Android version: 14
Magisk version name: canary
Magisk version code: 27002

I found the reason this is happening is because in this version the stub.apk does not contain the AndroidManifest.xml and I'm curious why no one else is reporting this bug

Logcat:

```
04-09 17:05:18.296 15952 28018 W PackageParser: Failed to parse /data/user/0/com.topjohnwu.magisk/cache/stub.apk
04-09 17:05:18.296 15952 28018 W PackageParser: java.io.FileNotFoundException: AndroidManifest.xml
04-09 17:05:18.296 15952 28018 W PackageParser: 	at android.content.res.ApkAssets.nativeOpenXml(Native Method)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at android.content.res.ApkAssets.openXml(ApkAssets.java:382)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1520)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1487)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:993)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1202)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1116)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:8346)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:8323)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at a.P8.g(SourceFile:10)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at a.P8.F(SourceFile:306)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at a.XB.c(SourceFile:35)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at a.xp.e(SourceFile:6)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at a.UH.run(SourceFile:104)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at a.VM.run(SourceFile:33)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at a.LA.run(SourceFile:3)
04-09 17:05:18.296 15952 28018 W PackageParser: 	at a.Lf.run(SourceFile:92)
04-09 17:05:18.296 15952 28018 W PackageManager: Failure to parse package archive
04-09 17:05:18.296 15952 28018 W PackageManager: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/user/0/com.topjohnwu.magisk/cache/stub.apk
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1543)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1487)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:993)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1202)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1116)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:8346)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:8323)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at a.P8.g(SourceFile:10)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at a.P8.F(SourceFile:306)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at a.XB.c(SourceFile:35)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at a.xp.e(SourceFile:6)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at a.UH.run(SourceFile:104)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at a.VM.run(SourceFile:33)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at a.LA.run(SourceFile:3)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at a.Lf.run(SourceFile:92)
04-09 17:05:18.296 15952 28018 W PackageManager: Caused by: java.io.FileNotFoundException: AndroidManifest.xml
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.res.ApkAssets.nativeOpenXml(Native Method)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.res.ApkAssets.openXml(ApkAssets.java:382)
04-09 17:05:18.296 15952 28018 W PackageManager: 	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1520)
04-09 17:05:18.296 15952 28018 W PackageManager: 	... 14 more
```

bad stub.apk

```
https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@3180e66585494131b76b498531c2d3a56e56e69b/stub-release.apk
```

**Comment by yujincheng08** [comment]
Fixed by 7abe635de92b41f989f1043781c7cce82c06b40d
