### ISSUE TITLE
MagiskHide not work at Android 9 / H2OS 9.0.5 / Oneplus 6T

### ISSUE THREAD

**Issue by lialosiu** [topjohnwu/Magisk#804]
The game `jp.co.cygames.princessconnectredive` crash, and throw `CrackProofAndroidError`

```
ErrorCode = 61
2018/11/28 17:47:44
jp.co.cygames.princessconnectredive
OnePlus
ONEPLUS A6010
9
003e1cc8-0133f080-0bed53fa
b49cd263-47919163-787f8b89
66448ca8-404b76d6-22a87c3f
06258d8d-d6833390-9dd15173
4f287d83-109e639b-f53855c5
4ebe31ce-0f63b24a-cab71650
832ab961-66baaace-334c9492
```

Magisk Manager `6.0.1-a9f265a5(159) (com.hc8Qg16PI2uzsP.I)`

Magisk `v17.4-a9f265a5`

and some logcat may help:

```
11-28 17:56:23.175   908  1113 D RestartProcessManager: Last Running Package : jp.co.cygames.princessconnectredive , start time 1543398983175
11-28 17:56:23.176   908  2923 D EmbryoManager: Embryo claimed. jp.co.cygames.princessconnectredive, pid=11258
11-28 17:56:23.177   908  2923 D OnePlusSmartBoostManager: writeHotCount jp.co.cygames.princessconnectredive, pid=11258
11-28 17:56:23.178   908  2923 V ActivityManager: GestureButton: skip computeBounds for this=ActivityRecord{66c7b5d u0 jp.co.cygames.princessconnectredive/com.unity3d.player.UnityPlayerActivity t700} maxAspectRatio=2.16
11-28 17:56:23.184 11258 11258 I Perf    : Connecting to perf service.
11-28 17:56:23.186 11258 11258 E libc    : Access denied finding property "vendor.perf.iop_v3.enable"
11-28 17:56:23.174 11258 11258 W ssconnectredive: type=1400 audit(0.0:8968): avc: denied { read } for name="u:object_r:vendor_iop_prop:s0" dev="tmpfs" ino=23740 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_iop_prop:s0 tclass=file permissive=0
11-28 17:56:23.186 11258 11258 E libc    : Access denied finding property "vendor.perf.iop_v3.enable.debug"
11-28 17:56:23.174 11258 11258 W ssconnectredive: type=1400 audit(0.0:8969): avc: denied { read } for name="u:object_r:vendor_iop_prop:s0" dev="tmpfs" ino=23740 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_iop_prop:s0 tclass=file permissive=0
11-28 17:56:23.188  3081  4000 D GridItemProvider: saveToolBoxItemsToPreference: jsonStr= [{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.unity3d.player.UnityPlayerActivity","mPackage":"jp.co.cygames.princessconnectredive"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"jp.co.cygames.princessconnectredive"},"itemType":0,"launchCount":4,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"a.c","mPackage":"com.hc8Qg16PI2uzsP.I"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.hc8Qg16PI2uzsP.I"},"itemType":0,"launchCount":7,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.google.android.gm.ConversationListActivityGmail","mPackage":"com.google.android.gm"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.google.android.gm"},"itemType":0,"launchCount":16,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.oppo.market.activity.MainActivity","mPackage":"com.oppo.market"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.oppo.market"},"itemType":0,"launchCount":22,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"moe.shizuku.redirectstorage.MainActivity","mPackage":"moe.shizuku.redirectstorage"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"moe.shizuku.redirectstorage"},"itemType":0,"launchCount":15,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"moe.shizuku.manager.MainActivity","mPackage":"moe.shizuku.privileged.api"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"moe.shizuku.privileged.api"},"itemType":0,"launchCount":4,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.github.shadowsocks.MainActivity","mPackage":"com.github.shadowsocks"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.github.shadowsocks"},"itemType":0,"launchCount":5,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.catchingnow.icebox.activity.mainActivity.MainAppActivity","mPackage":"com.catchingnow.icebox"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.catchingnow.icebox"},"itemType":0,"launchCount":17,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.tencent.mm.ui.LauncherUI","mPackage":"com.tencent.mm"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.tencent.mm"},"itemType":0,"launchCount":33,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.google.android.apps.photos.home.HomeActivity","mPackage":"com.google.android.apps.photos"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.google.android.apps.photos"},"itemType":0,"launchCount":7,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.oneplus.filemanager.HomePageActivity","mPackage":"com.oneplus.filemanager"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.oneplus.filemanager"},"itemType":0,"launchCount":13,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.mixplorer.activities.BrowseAct
11-28 17:56:23.189   908  1304 D OemPhoneWindowManager: GestureButton: setInitialDisplaySize force set mHasNavigationBar to false.
11-28 17:56:23.194   908  2923 V ActivityManager: GestureButton: skip computeBounds for this=ActivityRecord{66c7b5d u0 jp.co.cygames.princessconnectredive/com.unity3d.player.UnityPlayerActivity t700} maxAspectRatio=2.16
11-28 17:56:23.197   908  2923 V ActivityManager: GestureButton: skip computeBounds for this=ActivityRecord{66c7b5d u0 jp.co.cygames.princessconnectredive/com.unity3d.player.UnityPlayerActivity t700} maxAspectRatio=2.16
11-28 17:56:23.197   908  1304 I ActivityManager: Config changes=20000480 {1.0 0 460mcc11mnc [ja_JP,zh_CN_#Hans,zh_HK_#Hant,en_US] ldltr sw411dp w861dp h380dp 420dpi nrml long hdr widecg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2261) mAppBounds=Rect(79, 0 - 2340, 1080) mWindowingMode=fullscreen mActivityType=undefined} s.17mThemeChanged = 0}
11-28 17:56:23.198   781  2797 D AudioPolicyService: setRecordSilenced() uid 10177 on silenced 0
11-28 17:56:23.209   908  1304 E ActivityManager: Failed to schedule configuration change
11-28 17:56:23.209   908  1304 E ActivityManager: android.os.DeadObjectException
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.os.BinderProxy.transactNative(Native Method)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.os.BinderProxy.transact(Binder.java:1177)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:1815)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:129)
11-28 17:56:23.209   908  1304 E ActivityManager:       at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
11-28 17:56:23.209   908  1304 E ActivityManager:       at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:100)
11-28 17:56:23.209   908  1304 E ActivityManager:       at com.android.server.am.ActivityManagerService.updateGlobalConfigurationLocked(ActivityManagerService.java:24730)
11-28 17:56:23.209   908  1304 E ActivityManager:       at com.android.server.am.ActivityManagerService.updateDisplayOverrideConfigurationLocked(ActivityManagerService.java:24850)
11-28 17:56:23.209   908  1304 E ActivityManager:       at com.android.server.am.ActivityManagerService.updateDisplayOverrideConfiguration(ActivityManagerService.java:24816)
11-28 17:56:23.209   908  1304 E ActivityManager:       at com.android.server.wm.WindowManagerService.sendNewConfiguration(WindowManagerService.java:4779)
11-28 17:56:23.209   908  1304 E ActivityManager:       at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:2491)
11-28 17:56:23.209   908  1304 E ActivityManager:       at com.android.server.wm.Session.relayout(Session.java:245)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.view.ViewRootImpl.relayoutWindow(ViewRootImpl.java:7121)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2178)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1633)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7786)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.view.Choreographer.doCallbacks(Choreographer.java:816)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.view.Choreographer.doFrame(Choreographer.java:751)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.os.Handler.handleCallback(Handler.java:873)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.os.Handler.dispatchMessage(Handler.java:99)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.os.Looper.loop(Looper.java:193)
11-28 17:56:23.209   908  1304 E ActivityManager:       at android.os.HandlerThread.run(HandlerThread.java:65)
11-28 17:56:23.209   908  1304 E ActivityManager:       at com.android.server.ServiceThread.run(ServiceThread.java:44)
11-28 17:56:23.209   908  1304 I ActivityManager: Override config changes=20000480 {1.0 0 460mcc11mnc [ja_JP,zh_CN_#Hans,zh_HK_#Hant,en_US] ldltr sw411dp w861dp h380dp 420dpi nrml long hdr widecg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2261) mAppBounds=Rect(79, 0 - 2340, 1080) mWindowingMode=fullscreen mActivityType=undefined} s.17mThemeChanged = 0} for displayId=0
11-28 17:56:23.209   908  1304 D OemPhoneWindowManager: GestureButton: setInitialDisplaySize force set mHasNavigationBar to false.
11-28 17:56:23.210   908  1304 I chatty  : uid=1000(system) android.anim identical 1 line
11-28 17:56:23.211   908  1304 D OemPhoneWindowManager: GestureButton: setInitialDisplaySize force set mHasNavigationBar to false.
11-28 17:56:23.211   908  1304 V ActivityManager: GestureButton: skip computeBounds for this=ActivityRecord{66c7b5d u0 jp.co.cygames.princessconnectredive/com.unity3d.player.UnityPlayerActivity t700} maxAspectRatio=2.16
11-28 17:56:23.211   908  1304 D OemGestureButton: Update mNavigationBarPosition to 1 displayRotation=1
11-28 17:56:23.214   908  1407 I OemGestureButton: updateGestureButtonRegion: mNavigationBarPosition=1 mSwipeStartThreshold=50
11-28 17:56:23.227  1732  1732 D LiveWallpaper: onConfigurationChanged# engine update: true, clear cache: false
11-28 17:56:23.228  3118  3118 D UpdateService: onConfigurationChanged
11-28 17:56:23.236  3081  3081 D RecyclerViewWrapper: onWindowVisibilityChanged:8
11-28 17:56:23.236  5374  5374 D Tinker.DefaultAppLike: onConfigurationChanged:{1.0 0 460mcc11mnc [ja_JP,zh_CN_#Hans,zh_HK_#Hant,en_US] ldltr sw411dp w861dp h380dp 420dpi nrml long hdr widecg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2261) mAppBounds=Rect(79, 0 - 2340, 1080) mWindowingMode=fullscreen mActivityType=undefined} s.17mThemeChanged = 0}
11-28 17:56:23.242  1732  1732 D LiveWallpaper.Engine: onVisibilityChanged# true -> false
11-28 17:56:23.249  2321  2321 D OPDialerLayoutCache: updateViewCache size = 0
11-28 17:56:23.290 11258 11258 V Font    : Change font:2
11-28 17:56:23.292  7811  7811 D OPCardpackage: OnePlusCardReminder [onReceive act = android.intent.action.CONFIGURATION_CHANGED]
11-28 17:56:23.293  1878  2243 D PhoneInterfaceManager: [PhoneIntfMgr] getTetherApnRequired(): dunRequired = 0
11-28 17:56:23.293  7811  7811 D OPCardpackage: OnePlusCardReminder [readCardDatabase begin]
11-28 17:56:23.293  7811  7811 D OPCardpackage: readCardDatabase where : (event_time>1543312583293 and event_time<1543571783293) or (type=9 and order_by_time>1543398983293 and order_by_time<1543571783293)
11-28 17:56:23.296  7811  7811 D OPCardpackage: OnePlusCardReminder [readCardDatabase end]
11-28 17:56:23.296  7811  7811 D OPCardpackage: OnePlusCardReminder [setAlarm begin]
11-28 17:56:23.296  7811  7811 D OPCardpackage: OnePlusCardReminder [setAlarm end]
11-28 17:56:23.299  7811 12527 D OPCardpackage: CardWidgetProvider [header_flag = unexpired]
11-28 17:56:23.307  1667  1667 D StatusBar: disable<e i a s b h r c s > disable2<q i n >
11-28 17:56:23.294 11258 11258 W jp.co.cygames.princessconnectredive: type=1400 audit(0.0:8970): avc: denied { read } for comm=45474C20496E6974 name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=23737 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
11-28 17:56:23.309 11258 12529 E libc    : Access denied finding property "vendor.debug.egl.profiler"
11-28 17:56:23.310  1732  1732 D LiveWallpaper.Engine: onSurfaceRedrawNeeded#
11-28 17:56:23.310 11258 12529 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
11-28 17:56:23.294 11258 11258 W jp.co.cygames.princessconnectredive: type=1400 audit(0.0:8971): avc: denied { read } for comm=45474C20496E6974 name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=23737 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
11-28 17:56:23.311  1732  1732 D LiveWallpaper.Engine: drawBackground# draw again. count: 1
11-28 17:56:23.313  7811 12527 D OPCardpackage: CardWidgetProvider [viewType = 0]
11-28 17:56:23.317  1667  1667 E ndroid.systemu: Invalid ID 0x00000000.
11-28 17:56:23.321  3081  3081 V Theme   : net.oneplus.launcher, Add app's resource
11-28 17:56:23.323  3081  3081 D Launcher: onConfigurationChanged# old: {1.0 0 460mcc11mnc [ja_JP,zh_CN_#Hans,zh_HK_#Hant,en_US] ldltr sw411dp w411dp h860dp 420dpi nrml long hdr widecg port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 79 - 1080, 2340) mWindowingMode=fullscreen mActivityType=home} s.10mThemeChanged = 0}
11-28 17:56:23.323  3081  3081 D Launcher: onConfigurationChanged# new: {1.0 0 460mcc11mnc [ja_JP,zh_CN_#Hans,zh_HK_#Hant,en_US] ldltr sw411dp w861dp h380dp 420dpi nrml long hdr widecg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2340, 1080) mAppBounds=Rect(79, 0 - 2340, 1080) mWindowingMode=fullscreen mActivityType=home} s.17mThemeChanged = 0}
11-28 17:56:23.330   908  2927 I android_os_HwBinder: HwBinder: Starting thread pool for default::vendor.oneplus.hardware.param@1.0::IOneplusParam
11-28 17:56:23.330   750   750 D OPParam : sid = 304, ad = 312480, off = 1184
11-28 17:56:23.330   750   750 D OPParam : getParamIntSYNC: param get 4 4c4a0 0
11-28 17:56:23.331  3081  3081 D InvariantDeviceProfile: WORKSPACE_XML - default_workspace_cn_5x5_6t
11-28 17:56:23.333   908  2927 I android_os_HwBinder: HwBinder: Starting thread pool for default::vendor.oneplus.hardware.param@1.0::IOneplusParam
11-28 17:56:23.333   750   750 D OPParam : sid = 304, ad = 312480, off = 1184
11-28 17:56:23.333   750   750 D OPParam : getParamIntSYNC: param get 4 4c4a0 0
11-28 17:56:23.333  3081  3081 D InvariantDeviceProfile: getDefaultToolboxLayout# customType=NONE
11-28 17:56:23.334   908  1181 D OemPhoneWindowManager: GestureButton: setInitialDisplaySize force set mHasNavigationBar to false.
11-28 17:56:23.334  3081  3081 V Theme   : net.oneplus.launcher, Add app's resource
11-28 17:56:23.337  3081  3081 V Theme   : net.oneplus.launcher, Add app's resource
11-28 17:56:23.339   908  1412 I InputReader: Reconfiguring input devices.  changes=0x00000004
11-28 17:56:23.339   908  1412 I InputReader: Device reconfigured: id=6, name='synaptics,s3320', size 1080x2340, orientation 1, mode 1, display id 0
11-28 17:56:23.347  3081  3081 D Launcher.Workspace: onStartStateTransition# toState: ALL_APPS
11-28 17:56:23.347  3081  3081 D Launcher.Workspace: onEndStateTransition# toState: ALL_APPS
11-28 17:56:23.347  3081  3081 D Launcher.Model: startLoader# bindPage: 0, modelLoaded: true, loaderRunning: false
11-28 17:56:23.347  3081  3081 D LoaderTask:    main  <- model@clearPendingBinds
11-28 17:56:23.347  3081  3081 D LoaderTask: bindWorkspace# validFirstPage: true, currentScreen: 0, currentScreenId: 0
11-28 17:56:23.348  3081  3081 D LoaderTask:    main  <- model@clearPendingBinds & startBinding
11-28 17:56:23.348  3081  3081 D QuickPage: destroy
11-28 17:56:23.348  3081  3081 I WeatherProvider: un-subscribe the weather callback: WelcomePanel
11-28 17:56:23.349  3081  3081 I         : clear pending jobs in TaskWorker
11-28 17:56:23.350  3081  3081 D Launcher: setQuickPage: net.oneplus.launcher.quickpage.EmptyQuickPage@88b704d
11-28 17:56:23.350  3081  3081 D Launcher.Workspace: DynamicIcon Workspace updateCurrentPageDynamicIconState success
11-28 17:56:23.352  3081  3081 D LoaderTask:    main  <- model@bindScreens
11-28 17:56:23.353  3081  3081 D LoaderTask:    main  <- model@bindWorkspaceItems# from 0 to 6
11-28 17:56:23.356  3081  3081 D LoaderTask:    main  <- model@bindWorkspaceItems# from 6 to 9
11-28 17:56:23.357   785  2705 W SurfaceFlinger: Attempting to destroy on removed layer: c7d0574 AssistPreviewPanel#0
11-28 17:56:23.370  3081  3081 D FolderContent: currentHeight=933, expectedHeight=933
11-28 17:56:23.371  3081  3081 D LoaderTask:    main  <- model@finishFirstPageBind
11-28 17:56:23.334   908  1181 I chatty  : uid=1000(system) android.display identical 1 line
11-28 17:56:23.335   908  1181 D OemPhoneWindowManager: GestureButton: setInitialDisplaySize force set mHasNavigationBar to false.
11-28 17:56:23.371  3081  3081 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
11-28 17:56:23.372  3081  3081 D LoaderTask:    main  <- model@onPageBoundSynchronously & executeOnNextDraw
11-28 17:56:23.374  3081  3081 D LoaderTask:    main  <- model@bindAllApplications
11-28 17:56:23.364 11258 11258 W ssconnectredive: type=1400 audit(0.0:8972): avc: denied { read } for name="u:object_r:vendor_iop_prop:s0" dev="tmpfs" ino=23740 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_iop_prop:s0 tclass=file permissive=0
11-28 17:56:23.376 11258 11258 E libc    : Access denied finding property "vendor.perf.iop_v3.enable"
11-28 17:56:23.376  3081  3081 D AlphabeticalAppsList: refillAdapterItems app = 72, recent = 2, adapter = 73, searchResults =  null, filtered = 72, AllappsStore app = 72, recent = 2
11-28 17:56:23.376 11258 11258 E libc    : Access denied finding property "vendor.perf.iop_v3.enable.debug"
11-28 17:56:23.376  3081  3081 D AlphabeticalAppsList: refillAdapterItems app = 72, recent = 2, adapter = 73, searchResults =  null, filtered = 72, AllappsStore app = 72, recent = 2
11-28 17:56:23.377  3081  3081 D AlphabeticalHiddenAppsList: [refillAdapterItems] hidden app size = 2
11-28 17:56:23.377  3081  3081 D AlphabeticalHiddenAppsList: [updateAdapterItems] hasFilter: false, filtersAppInfos size = 72, mAdapterItems size = 2
```

**Comment by Didgeridoohan** [comment]
Have you made absolutely sure that it is Magisk that the game is detecting and not something like Developer options or USB Debugging?

I can't see anything in that log that has anything to do with detecting Magisk...

**Comment by lialosiu** [comment]
Yes, I tried. But nothing help...
The game running normally at my OnePlus 3 with Android 8, same version magisk.
I not know  what's the problem 🤣

**Comment by Didgeridoohan** [comment]
If the game is running fine on a different device, with the same version of Magisk installed, it is easy to deduce that it isn't actually Magisk that is the problem...

Magisk release v17.4-a9f265a5(17318) have a function to take care of the procfs leak natively (https://github.com/topjohnwu/Magisk/commit/f723427b8b253e4d0631891cf3af787e64c8b8fc), but could you use the [ProcGate app](https://github.com/topjohnwu/ProcGate/releases/latest) and make sure your leaks are fixed on the OP6T and then try again?

**Comment by lialosiu** [comment]
I installed ProcGate and try to run.

But it say `No leaks detected!`

I very suspect that it is my phone particular problem now🤣
