### ISSUE TITLE
Crash on LOS 16.0 on Pocophone, after update

### ISSUE THREAD

**Issue by nemanjan00** [topjohnwu/Magisk#805]
```
11-28 13:17:29.897 31842 31923 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
11-28 13:17:29.897 31842 31923 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 31842
11-28 13:17:29.897 31842 31923 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
11-28 13:17:29.897 31842 31923 E AndroidRuntime:        at a.td.c(Unknown Source:18)
11-28 13:17:29.897 31842 31923 E AndroidRuntime:        at a.td.lambda$lApFV5crSlcNHaSEwkdB4VcvD8c(Unknown Source:0)
11-28 13:17:29.897 31842 31923 E AndroidRuntime:        at a.-$$Lambda$td$lApFV5crSlcNHaSEwkdB4VcvD8c.run(Unknown Source:0)
11-28 13:17:29.897 31842 31923 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-28 13:17:29.897 31842 31923 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-28 13:17:29.897 31842 31923 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
11-28 13:17:29.902  2820  4513 W ActivityManager:   Force finishing activity com.topjohnwu.magisk/a.c
```

**Comment by nemanjan00** [comment]
Fixed after updating Magisk. (MagiskManager was newer)
