### ISSUE TITLE
Fail to `Hide the Magisk app`

### ISSUE THREAD

**Issue by Unknown78** [topjohnwu/Magisk#8268]
Device: Samsung Galaxy Note 4 SM-N910H
Android version: 7.1.1 Nougat (API 25)
Magisk version name: debug
Magisk version code: 27006 ([0495468d](https://github.com/topjohnwu/Magisk/commit/0495468d0257b17db459b460d5424d0e9df680fd)) [[Download](https://github.com/topjohnwu/magisk-files/commit/db7e410709ab5a555b28963bfd709837fba0fba6)]

Device platform: armeabi-v7a

**System**: 
- [REFINED_NOTE8_7.1_T2.zip](https://t.me/RefinedNougat/491)
- [Konup_RisingNote4_for_RefinedNote8_7.1.1_ver.2.3.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-updated-mod-risingnote4-ver-2-3.4363583/) 
- [Konup_HomeOneUI_RefinedNote8_7.1.1_ver.2.0_14.07.2022.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-oneui-port-home-screen-bixby-weather-wallpaper-choice-apps.4371353/)
- [Konup_SamsungCamera7_RefinedNote8_7.1.1_v.1.2.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-updated-stock-samsungcamera7-ver-1-2-now-writing-60fps.4201475/)
- [ModemServiceMode_RefinedNote8_7.1.1.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-updated-mod-risingnote4-ver-2-3.4363583/post-88539729)

**Boot**:
- [Helios_Kernel-V3.2-N910C.H-20240107.zip](https://github.com/ananjaser1211/Helios_5433/issues/1#issuecomment-1880082613)

---

# Problem

If I try to `Hide the Magisk App` then it will fail.

First it asks me to grant superuser access to the proxy app, so I grant it.
The proxy app opened, but a pop up appears that tells me to restore to the original APK.

<details><summary><b>Screenshot 1 (click to expand)</b></summary>

![Screenshot_29 07 24_08 37 29](https://github.com/user-attachments/assets/546196e4-d4d9-48d3-b0df-648809196d90)
</details>

<details><summary><b>Screenshot 2 (click to expand)</b></summary>

![Screenshot_29 07 24_08 38 09](https://github.com/user-attachments/assets/60095cc5-a02b-406b-b567-ecbd60518b16)
</details>

[logcat_Magisk_27006_0495468d_app-debug_2024-07-29T08.36.59.900000.txt](https://github.com/user-attachments/files/16406500/logcat_Magisk_27006_0495468d_app-debug_2024-07-29T08.36.59.900000.txt)

## Highlights

```java
07-29 08:37:11.992 29093 29093 I art     : Rejecting re-init on previously-failed class java.lang.Class<j$.nio.file.attribute.r>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/attribute/FileAttribute;
07-29 08:37:11.992 29093 29093 I art     :   at j$.time.Instant j$.time.Instant.ofEpochSecond(long, long) (SourceFile:2)
07-29 08:37:11.992 29093 29093 I art     :   at void j$.time.Instant.<clinit>() (SourceFile:16)
07-29 08:37:11.992 29093 29093 I art     :   at java.lang.String algd.a() (PG:12)
07-29 08:37:11.992 29093 29093 I art     :   at algc algc.a() (PG:1)
07-29 08:37:11.992 29093 29093 I art     :   at void lvb.i() (PG:15)
07-29 08:37:11.992 29093 29093 I art     :   at void lvb.onCreate() (PG:23)
07-29 08:37:11.992 29093 29093 I art     :   at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at void android.os.Looper.loop() (Looper.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-29 08:37:11.992 29093 29093 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:-1)
07-29 08:37:11.992 29093 29093 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.FileAttribute" on path: DexPathList[[zip file "/data/app/com.android.vending-2/base.apk", zip file "/data/app/com.android.vending-2/split_config.armeabi_v7a.apk", zip file "/data/app/com.android.vending-2/split_config.en.apk"],nativeLibraryDirectories=[/data/app/com.android.vending-2/lib/arm, /data/app/com.android.vending-2/base.apk!/lib/armeabi-v7a, /data/app/com.android.vending-2/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.android.vending-2/split_config.en.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
07-29 08:37:11.992 29093 29093 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
07-29 08:37:11.992 29093 29093 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:-1)
07-29 08:37:11.992 29093 29093 I art     :   at j$.time.Instant j$.time.Instant.ofEpochSecond(long, long) (SourceFile:2)
07-29 08:37:11.992 29093 29093 I art     :   at void j$.time.Instant.<clinit>() (SourceFile:16)
07-29 08:37:11.992 29093 29093 I art     :   at java.lang.String algd.a() (PG:12)
07-29 08:37:11.992 29093 29093 I art     :   at algc algc.a() (PG:1)
07-29 08:37:11.992 29093 29093 I art     :   at void lvb.i() (PG:15)
07-29 08:37:11.992 29093 29093 I art     :   at void lvb.onCreate() (PG:23)
07-29 08:37:11.993 29093 29093 I art     :   at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:-1)
07-29 08:37:11.993 29093 29093 I art     :   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
07-29 08:37:11.993 29093 29093 I art     :   at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
07-29 08:37:11.993 29093 29093 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:-1)
07-29 08:37:11.993 29093 29093 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:-1)
07-29 08:37:11.993 29093 29093 I art     :   at void android.os.Looper.loop() (Looper.java:-1)
07-29 08:37:11.993 29093 29093 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:-1)
07-29 08:37:11.993 29093 29093 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-29 08:37:11.993 29093 29093 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:-1)
07-29 08:37:11.993 29093 29093 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:-1)
```

```java
07-29 08:37:15.636  3446  4529 E ActivityTrigger: activityStartTrigger: not whiteListedotbrgv.n/p.BxY.a8/1
```

```java
07-29 08:37:21.163 27466 27466 E WindowManager: android.view.WindowLeaked: Activity com.topjohnwu.magisk.ui.MainActivity has leaked window DecorView@625d49e[Hiding the Magisk app…] that was originally added here
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.app.Dialog.show(Dialog.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.topjohnwu.magisk.core.tasks.AppMigration.hide(AppMigration.kt:216)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.topjohnwu.magisk.ui.settings.SettingsViewModel$onItemAction$1.invokeSuspend(SettingsViewModel.kt:108)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.topjohnwu.magisk.ui.settings.SettingsViewModel.onItemAction(SettingsViewModel.kt:108)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.topjohnwu.magisk.ui.settings.BaseSettingsItem$Input.onPressed$lambda$5$lambda$4$lambda$2$lambda$1(BaseSettingsItem.kt:89)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.topjohnwu.magisk.ui.settings.BaseSettingsItem$Input.$r8$lambda$aI6UiGFPvOKeNlFFaYQ-NtKUy0Q(BaseSettingsItem.kt)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.topjohnwu.magisk.ui.settings.BaseSettingsItem$Input$$ExternalSyntheticLambda3.invoke(D8$$SyntheticClass:0)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.topjohnwu.magisk.view.MagiskDialog$ButtonViewModel.clicked(MagiskDialog.kt:122)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.topjohnwu.magisk.databinding.DialogMagiskBaseBindingImpl._internalCallbackOnClick(DialogMagiskBaseBindingImpl.java:562)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.topjohnwu.magisk.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.view.View.performClick(View.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.widget.TextView.performClick(TextView.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.view.View$PerformClick.run(View.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.os.Looper.loop(Looper.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
07-29 08:37:21.163 27466 27466 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
07-29 08:37:21.163 27466 27466 D ViewRootImpl@dbf92d9[Hiding the Magisk app…]: mHardwareRenderer.destroy()#4
07-29 08:37:21.164  3446 27215 D WindowManager: disposeInputChannel mInputChannel: d67b235 Hiding the Magisk app… (server)
07-29 08:37:21.164  2972  3023 I SurfaceFlinger: id=531 Removed Hiding the Magisk app… (3/6)
07-29 08:37:21.164  2972  8846 I SurfaceFlinger: id=531 Removed Hiding the Magisk app… (-2/6)
07-29 08:37:21.167  3446 27215 D InputTransport: Input channel destroyed: fd=366
07-29 08:37:21.174 29501 29501 I AppsEdgePanelProvider: count=0
07-29 08:37:21.176  3446  6548 D MountService: getExternalStorageMountMode : 1
07-29 08:37:21.177  3446  6548 D MountService: getExternalStorageMountMode : 3
07-29 08:37:21.179 27466 27466 D ViewRootImpl@dbf92d9[Hiding the Magisk app…]: dispatchDetachedFromWindow
07-29 08:37:21.180  3446  6548 D MountService: getExternalStorageMountMode : final mountMode=1, uid : 1000, packageName : com.samsung.android.app.assistantmenu
07-29 08:37:21.180  3446  5078 W WindowManager: Failed looking up window
07-29 08:37:21.180  3446  5078 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@5449c6c does not exist
```

```java
07-29 08:37:23.567 29249 29249 W System.err: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{otbrgv.n/com.topjohnwu.magisk.ui.MainActivity}
07-29 08:37:23.567 29249 29249 W System.err: 	at android.app.ApplicationPackageManager.getActivityInfoAsUser(ApplicationPackageManager.java)
07-29 08:37:23.567 29659 29659 D TaskEdgePanelProvider: onReceive android.intent.action.PACKAGE_ADDED
07-29 08:37:23.567 29249 29249 W System.err: 	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java)
07-29 08:37:23.567 29249 29249 W System.err: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java)
07-29 08:37:23.568 29249 29249 W System.err: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java)
07-29 08:37:23.568 29249 29249 W System.err: 	at androidx.core.view.WindowCompat$Api16Impl.setDecorFitsSystemWindows(WindowCompat.java:150)
07-29 08:37:23.568 29249 29249 W System.err: 	at androidx.core.view.WindowCompat.setDecorFitsSystemWindows(WindowCompat.java:122)
07-29 08:37:23.568 29249 29249 W System.err: 	at com.topjohnwu.magisk.arch.UIActivity.onCreate(UIActivity.kt:74)
07-29 08:37:23.568 29249 29249 W System.err: 	at com.topjohnwu.magisk.ui.MainActivity.onCreate(MainActivity.kt:71)
07-29 08:37:23.569 29249 29249 W System.err: 	at android.app.Activity.performCreate(Activity.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at android.os.Looper.loop(Looper.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 08:37:23.569 29249 29249 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
07-29 08:37:23.569 29249 29249 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
07-29 08:37:23.572  2998  2998 W keystore: ENTER abort from uid 10016
```

```java
07-29 08:37:24.506  3446  5076 E ActivityTrigger: activityStartTrigger: not whiteListedcom.topjohnwu.magisk/com.topjohnwu.magisk.ui.surequest.SuRequestActivity/27006
```

```java
07-29 08:37:24.584 27466 27466 E AppContext: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.ui.surequest.SuRequestActivity}: java.lang.RuntimeException: Unable to instantiate application com.topjohnwu.magisk.core.App: java.lang.IllegalStateException: Base context already set
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.os.Handler.dispatchMessage(Handler.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.os.Looper.loop(Looper.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.app.ActivityThread.main(ActivityThread.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 08:37:24.584 27466 27466 E AppContext: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
07-29 08:37:24.584 27466 27466 E AppContext: Caused by: java.lang.RuntimeException: Unable to instantiate application com.topjohnwu.magisk.core.App: java.lang.IllegalStateException: Base context already set
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.app.LoadedApk.makeApplication(LoadedApk.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	... 10 more
07-29 08:37:24.584 27466 27466 E AppContext: Caused by: java.lang.IllegalStateException: Base context already set
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.content.ContextWrapper.attachBaseContext(ContextWrapper.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at com.topjohnwu.magisk.core.AppContext.attachApplication(AppContext.kt:74)
07-29 08:37:24.584 27466 27466 E AppContext: 	at com.topjohnwu.magisk.core.App.attachBaseContext(App.kt:24)
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.app.Application.attach(Application.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.app.Instrumentation.newApplication(Instrumentation.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	at android.app.Instrumentation.newApplication(Instrumentation.java)
07-29 08:37:24.584 27466 27466 E AppContext: 	... 11 more
```

```java
07-29 08:37:24.680  3446  3468 I ActivityManager: Process com.topjohnwu.magisk (pid 27466) has died(80,1277)
```

```java
07-29 08:37:40.186  2923  8682 W Magisk  : su: request rejected (10201)
07-29 08:37:40.186  2923  8682 E Magisk  : write failed with 32: Broken pipe
```

**Comment by madzul** [comment]
Got this problem before. My workaround is to change settings for superuser request (Automatic Response) just before hiding the magisk.

**Comment by cebtenzzre** [comment]
> Got this problem before. My workaround is: change settings for superuser request (`Automatic Response`) to `Grant`, just before hiding the magisk.

This worked for me as well.

**Comment by yujincheng08** [comment]
Is 27003 normal?

**Comment by SalvatoreNoschese** [comment]
> Got this problem before. My workaround is: change settings for superuser request (`Automatic Response`) to `Grant`, just before hiding the magisk.

I'm here also for this (canary and P7P). Thanks to this, I fixed 👍

**Comment by hhihhio** [comment]
my bank app can detect developer settings, knox, device status and some root app installed (titanium backup, root explorer), android 11 block normal user to see Android/data folder so magisk must have do this for some root file. or some new file store in root folder or /data after root % patch boot.img it detect and refuse to run

**Comment by DarkanParx** [comment]
I've had the same issue, however upon restoring the original app root was somehow lost. I tried reflashing the patched .img via fastboot but although it completes successfully, upon reboot there is no root. Any ideas/suggestions? Thanks

**Comment by Umokazan** [comment]
"I've had the same issue, however upon restoring the original app root was somehow lost. I tried reflashing the patched .img via fastboot but although it completes successfully, upon reboot there is no root. Any ideas/suggestions? Thanks" stuck here too : (

**Comment by hhihhio** [comment]
because in the system or google app is the spy. you need to isolate all system apps from root recognition to prevent them from sharing intelligence with each other. the system has intelligence to report about root status in many ways, just need to know how apps collect information about rooted phone risk and magisk needs to solve all that problem by blind all info it can try get to know rooted device. There are also many security software experts who have studied magisk and android applications to find ways to improve root detection in applications such as banking or government. magisk needs to encrypt root operations progress, modify system permissions when rooting so that applications cannot find files or cat -proc information from the system. my bank app see zygote.sh in / root folder and it say device rooted, so magisk have to blind it and prevent it can see any file like that. or it can check app list in phone, app installed history, please do like android 11 or more block user to see file in android/data, same way magisk please block it too see android system file like data/app or file in /.

My banking app now silently blocks transfer access and it no longer publicly announces root like before but will report unknown errors

**Comment by hhihhio** [comment]
hi john. in the system or google app is the spy. you need to isolate all system apps from root recognition to prevent them from sharing intelligence with each other. the system has intelligence to report about root status in many ways, just need to know how apps collect information about rooted phone risk and magisk needs to solve all that problem by blind all info it can try get to know rooted device. There are also many security software experts who have studied magisk and android applications to find ways to improve root detection in applications such as banking or government. magisk needs to encrypt root operations progress, modify system permissions when rooting so that applications cannot find files or cat -proc information from the system. my bank app see zygote.sh in / root folder and it say device rooted, so magisk have to blind it and prevent it can see any file like that. or it can check app list in phone, app installed history, please do like android 11 or more block user to see file in android/data, same way magisk please block it too see android system file like data/app or file in /.

My banking app now silently blocks transfer access and it no longer publicly announces root like before but will report unknown errors

my other app show error like unlocked oem or bootloader, modified android but only uninstall root magisk it allow me to use even oem or boot loader unlocked, custom twrp installed(ss galaxy j7 prime aroid 8.1, j5 (2016) android 7, j4+ android 9, j8 android 10) no matter I do add it deny list, play integrity, lsposed, module, hide app random name... it still detect root. only way I tried is use supersu and disable root, then uninstall supersu so it can't detect root. when need I reinstall supersu and enable root again

momo app show root detected notify when open so you can try this to solve the problem

**Comment by hhihhio** [comment]
> [@hhihhio](https://github.com/hhihhio) [@DarkanParx](https://github.com/DarkanParx) [@Umokazan](https://github.com/Umokazan)
> 
> Please create new issue.

they always closed my issue as not planed so excuse me or sorry but I have to borrow some1 issue have almost same problem

**Comment by Unknown78** [comment]
I've just tried it in [v30.4](https://github.com/topjohnwu/Magisk/releases/tag/v30.4), and it seems to be fixed.

I'm worried that this only applies to my device.
Could you guys please also verify? @madzul @cebtenzzre @SalvatoreNoschese

**Comment by Unknown78** [comment]
It doesn't work again in [v30.7](https://github.com/topjohnwu/Magisk/releases/tag/v30.7)
Even after set the `Automatic Response` to `Grant`

**Comment by 0xwolkx0** [comment]
Can confirm
Oneplus 15t with ColorOS 16.0.5.703 (no idea if it matters)
Can't hide Magisk, got an infinite loading.

**Comment by osm0sis** [comment]
Any difference with the new app in 31.0?

**Comment by Unknown78** [comment]
# Magisk v31.0 of [app-debug.apk](https://github.com/topjohnwu/Magisk/releases/tag/v31.0)

Why the setting is missing in the new UI?

<details><summary><b>Screenshot of the Settings in the New UI (click to expand/shrink)</b></summary>

<img width="50%" height="50%" alt="New_UI_Screenshot" src="https://github.com/user-attachments/assets/0dae3268-a2a4-4ffe-bc08-72c36791a945" />
</details>

# Magisk v31.0 of [Magisk-v31.0-legacy.apk](https://github.com/topjohnwu/magisk-files/releases/tag/files)

<details><summary><b>Screenshot of the Settings in the Old UI (click to expand/shrink)</b></summary>

<img width="50%" height="50%" alt="Old_UI_Screenshot" src="https://github.com/user-attachments/assets/3e6e3e3e-5b89-416c-ae28-72d270cbb0cb" />
</details>

## First case, `Automatic Response` is set to `Prompt`

It still errors.
And the root is lost until I reboot it.
Why?

The logcat right from `Hide the Magisk app` till I opened again the original Magisk app that has lost its root access.
[Magisk-v31.0-legacy_prompt_logcat_2026-09-08T03.04.21.004000.txt](https://github.com/user-attachments/files/31928126/Magisk-v31.0-legacy_prompt_logcat_2026-09-08T03.04.21.004000.txt)

The magisk_log from the original app that has lost its root access,
[Magisk-v31.0-legacy_prompt_magisk_log_2026-09-08T03.06.38.log](https://github.com/user-attachments/files/31928120/Magisk-v31.0-legacy_prompt_magisk_log_2026-09-08T03.06.38.log)


## Second case, `Automatic Response` is set to `Grant`

It works.
Why?

The `Automatic Response` setting went back to `Prompt` by itself.
The `Restore the Magisk app` is working with it being set to `Prompt`.

The logcat from set to `Grant`, `Hide the Magisk app` to the hided app and then `Restore the Magisk app` back to the original app,
[Magisk-v31.0-legacy_grant_logcat_2026-09-08T04.08.39.003000.txt](https://github.com/user-attachments/files/31928464/Magisk-v31.0-legacy_grant_logcat_2026-09-08T04.08.39.003000.txt)

The magisk_log from the hided app,
[Magisk-v31.0-legacy_grant_magisk_log_2026-09-08T04.09.31.log](https://github.com/user-attachments/files/31928482/Magisk-v31.0-legacy_grant_magisk_log_2026-09-08T04.09.31.log)

# Summary

It is unclear the reason of why the `Grant` setting for the `Automatic Response` works while the `Prompt` does not.
It might regress in the next version just like before, oscillating between working and not.

Furthermore, it is alo unclear the reason of why the setting is missing in the new UI.

**Comment by osm0sis** [comment]
No, check in the new app. It's not in Settings anymore, it's the eyeball icon on the main page.

Automatic often helps it work when there are race condition issues with the hiding process. It's a long-standing known issue in the old app.

**Comment by Unknown78** [comment]
Ah, I didn't notice it.
Why introduce setting changes without any indicator in a new update?
Like, "hey this eye icon is the new `Hide the Magisk app`" ?
At least it should've been listed in the changelog, instead of being abstracted hugely with the word of 'UI overhaul'.

I've just tested it with the new UI and it works even when it's set with `Prompt`.

This works on my device, but I'm not sure on the others.
Could you guys please also verify? @madzul @cebtenzzre @SalvatoreNoschese @0xwolkx0

**Comment by osm0sis** [comment]
Well it's been a week, let's call it for now. If something similar resurfaces we'll want fresh logs from the new app, etc. anyway, so best just to start a new issue. Thanks all!
