### ISSUE TITLE
Zygisk module is not work on google play system update 2024/08/01

### ISSUE THREAD

**Issue by chesskuo** [topjohnwu/Magisk#8374]
Device: Pixel 5
Android version: 14
Magisk version name: 8e2113b
Magisk version code: 27007

---

In this morning, I found the update about the system google play.
And I updated to the 2024 August version.
And then I found Zygisk module all down and the Zygisk show False in the manager Magisk field.
So, I thought this bug is cause by the google play system update.
I don't know if this situation does only impact me.

Please help me.
Thanks

---

<details>
  <summary>log</summary>

```
---Detected Device Info---

isAB=true
isSAR=true
ramdisk=true
kernel=Linux aarch64 4.19.278-g7b0944645172-ab10812814 #1 SMP PREEMPT Thu Sep 7 05:43:03 UTC 2023


---Magisk Logs---
8e82113b (27007)

12-25 02:56:53.419  1012  1012 I : �Magisk 8e82113b(27007) daemon started
12-25 02:56:53.422  1012  1012 I : �* Device API level: 34
12-25 02:56:53.431  1012  1014 I : �** post-fs-data mode running
12-25 02:56:53.474  1012  1014 I : �* Initializing Magisk environment
12-25 02:56:53.490  1012  1014 I : �* Running post-fs-data.d scripts
12-25 02:56:53.492  1012  1014 I : �* Setup internal mounts
12-25 02:56:53.494  1012  1014 I : �Upgrade / New module: playintegrityfix
12-25 02:56:53.495  1012  1014 I : �* Running module post-fs-data scripts
12-25 02:56:53.496  1021  1021 I : �playintegrityfix: exec [post-fs-data.sh]
12-25 02:56:53.536  1021  1021 I : �zygisk_lsposed: exec [post-fs-data.sh]
12-25 02:56:53.546  1021  1021 I : �zygisk_shamiko: exec [post-fs-data.sh]
12-25 02:56:53.562  1012  1014 I : �* Loading modules
12-25 02:56:53.562  1012  1014 I : �hosts: loading mount files
09-07 09:55:57.314  1012  1025 I : �** late_start service mode running
09-07 09:55:57.314  1012  1025 I : �* Running service.d scripts
09-07 09:55:57.316  1012  1025 I : �service.d: exec [vanced.sh]
09-07 09:55:57.331  1012  1025 I : �service.d: exec [music.sh]
09-07 09:55:57.338  1012  1025 I : �service.d: exec [com.google.android.apps.youtube.music.sh]
09-07 09:55:57.343  1012  1025 I : �service.d: exec [com.google.android.youtube.sh]
09-07 09:55:57.360  1012  1025 I : �* Running module service scripts
09-07 09:55:57.361  1012  1025 I : �playintegrityfix: exec [service.sh]
09-07 09:55:57.379  1012  1025 I : �zygisk_lsposed: exec [service.sh]
09-07 09:55:57.393  1012  1025 I : �zygisk_shamiko: exec [service.sh]
09-07 09:55:57.934  1012  1014 I : �denylist: initializing internal data structures
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.android.vending/com.android.vending]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.android.vending/com.android.vending:background]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.android.vending/com.android.vending:instant_app_installer]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.android.vending/com.android.vending:quick_launch]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.android.vending/com.android.vending:recovery_mode]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.chinatrust.mobilebank/com.chinatrust.mobilebank]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.chinatrust.mobilebank/com.chinatrust.mobilebank:BeaconService]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.chinatrust.mobilebank/com.chinatrust.mobilebank:playcore_missing_splits_activity]
09-07 09:55:57.934  1012  1014 I : �denylist add: [isolated/com.chinatrust.mobilebank:qs.᫂]
09-07 09:55:57.934  1012  1014 I : �denylist add: [isolated/tw.com.taishinbank.richart:ky.pr]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.chinatrust.mobilebank/com.chinatrust.mobilebank_zygote]
09-07 09:55:57.934  1012  1014 I : �denylist add: [isolated/tw.com.taishinbank.richart:ky.jX]
09-07 09:55:57.934  1012  1014 I : �denylist add: [isolated/tw.com.taishinbank.richart:ky.EV]
09-07 09:55:57.934  1012  1014 I : �denylist add: [isolated/tw.com.taishinbank.richart:ky.nV]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.nextbank.ncbportal/com.nextbank.ncbportal]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.nextbank.ncbportal/com.nextbank.ncbportal_zygote]
09-07 09:55:57.934  1012  1014 I : �denylist add: [isolated/jp.naver.line.android:com.linecorp.mobile.payg.FguardService]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.cathaybk.mymobibank.android/com.cathaybk.mymobibank.android]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.cathaybk.mymobibank.android/com.cathaybk.mymobibank.android_zygote]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.cathaybk.mymobibank.android/com.cathaybk.mymobibank.android:playcore_missing_splits_activity]
09-07 09:55:57.934  1012  1014 I : �denylist add: [tw.gov.post.mpost/tw.gov.post.mpost]
09-07 09:55:57.934  1012  1014 I : �denylist add: [io.github.vvb2060.mahoshojo/io.github.vvb2060.mahoshojo]
09-07 09:55:57.934  1012  1014 I : �denylist add: [isolated/io.github.vvb2060.mahoshojo:io.github.vvb2060.mahoshojo.maho.MahoService2]
09-07 09:55:57.934  1012  1014 I : �denylist add: [io.github.vvb2060.mahoshojo/io.github.vvb2060.mahoshojo_zygote]
09-07 09:55:57.934  1012  1014 I : �denylist add: [tw.com.taishinbank.richart/tw.com.taishinbank.richart_zygote]
09-07 09:55:57.934  1012  1014 I : �denylist add: [tw.com.taishinbank.richart/tw.com.taishinbank.richart]
09-07 09:55:57.934  1012  1014 I : �denylist add: [isolated/com.android.vending:com.google.android.finsky.verifier.apkanalysis.service.ApkContentsScanService]
09-07 09:55:57.934  1012  1014 I : �denylist add: [jp.naver.line.android/jp.naver.line.android]
09-07 09:55:57.934  1012  1014 I : �denylist add: [isolated/jp.naver.line.android:vkey:vkey.android.vos.MgService]
09-07 09:55:57.934  1012  1014 I : �denylist add: [jp.naver.line.android/jp.naver.line.android:remote]
09-07 09:55:57.934  1012  1014 I : �denylist add: [jp.naver.line.android/jp.naver.line.android:crash_error_activity]
09-07 09:55:57.934  1012  1014 I : �denylist add: [jp.naver.line.android/jp.naver.line.android:transcoding]
09-07 09:55:57.934  1012  1014 I : �denylist add: [jp.naver.line.android/jp.naver.line.android:voom_camera_transcoding]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.jkos.app/com.jkos.app]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.jkos.app/com.jkos.app_zygote]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.esunbank/com.esunbank]
09-07 09:55:57.934  1012  1014 I : �denylist add: [com.YostarJP.BlueArchive/com.YostarJP.BlueArchive]
09-07 09:55:57.934  1012  1014 I : �denylist add: [tw.com.taishinbank.mobile/tw.com.taishinbank.mobile]
09-07 09:55:57.934  1012  1014 I : �denylist add: [tw.com.taishinbank.mobile/tw.com.taishinbank.mobile_zygote]
09-07 09:55:59.440  1012  1014 I : �** zygote restarted
09-07 09:56:02.605  1012  1025 I : �** zygote restarted
09-07 09:56:07.533  1012  1025 I : �** zygote restarted
09-07 09:56:12.463  1012  2732 I : �** zygote restarted
09-07 09:56:12.469  1012  2732 W : �zygote crashes too many times, rolling-back
09-07 09:56:26.192  1012  1014 I : �** boot-complete triggered

---Manager Logs---
8e82113b (27007)

--------- beginning of system
09-07 09:56:46.924  6572  6572 W LocaleConfig: The resource file pointed to by the given resource ID isn't found.
--------- beginning of main
09-07 09:57:48.175  6572  6572 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-07 09:57:48.175  6572  6572 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-07 09:57:48.216  6572  6693 E OpenGLRenderer: Unable to match the desired swap behavior.
09-07 09:57:48.777  6572  6647 W n1      : a.SY: Use JsonReader.setLenient(true) to accept malformed JSON at path $
09-07 09:57:48.777  6572  6647 W n1      : 	at a.QZ.sc(SourceFile:27)
09-07 09:57:48.777  6572  6647 W n1      : 	at a.Gt.qm(SourceFile:3)
09-07 09:57:48.777  6572  6647 W n1      : 	at a.Gt.EU(SourceFile:554)
09-07 09:57:48.777  6572  6647 W n1      : 	at a.Gt.uJ(SourceFile:5)
09-07 09:57:48.777  6572  6647 W n1      : 	at a.Dg.r(SourceFile:1)
09-07 09:57:48.777  6572  6647 W n1      : 	at a.Wx.z(SourceFile:32)
09-07 09:57:48.777  6572  6647 W n1      : 	at a.BW.P(SourceFile:56)
09-07 09:57:48.777  6572  6647 W n1      : 	at a.Q2.m(SourceFile:9)
09-07 09:57:48.777  6572  6647 W n1      : 	at a.Ux.run(SourceFile:57)
09-07 09:57:48.777  6572  6647 W n1      : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-07 09:57:48.777  6572  6647 W n1      : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-07 09:57:48.777  6572  6647 W n1      : 	at java.lang.Thread.run(Thread.java:1012)
09-07 09:57:49.095  6572  6647 W n1      : java.io.IOException: a.o9: HTTP 522 
09-07 09:57:49.095  6572  6647 W n1      : 	at a.z1.p(SourceFile:69)
09-07 09:57:49.095  6572  6647 W n1      : 	at a.sz.k(SourceFile:13)
09-07 09:57:49.095  6572  6647 W n1      : 	at a.Eq.K(SourceFile:6)
09-07 09:57:49.095  6572  6647 W n1      : 	at a.TU.run(SourceFile:104)
09-07 09:57:49.095  6572  6647 W n1      : 	at a.Tc.run(SourceFile:23)
09-07 09:57:49.095  6572  6647 W n1      : 	at a.BO.run(SourceFile:3)
09-07 09:57:49.095  6572  6647 W n1      : 	at a.BK.run(SourceFile:92)
09-07 09:57:49.095  6572  6647 W n1      : Caused by: a.o9: HTTP 522 
09-07 09:57:49.095  6572  6647 W n1      : 	at a.BH.p(SourceFile:145)
09-07 09:57:49.095  6572  6647 W n1      : 	at a.Q2.m(SourceFile:13)
09-07 09:57:49.095  6572  6647 W n1      : 	at a.Ux.run(SourceFile:57)
09-07 09:57:49.095  6572  6647 W n1      : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-07 09:57:49.095  6572  6647 W n1      : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-07 09:57:49.095  6572  6647 W n1      : 	at java.lang.Thread.run(Thread.java:1012)
09-07 09:58:06.820  6572  6572 I ImeTracker: o.opevkewbt:8b47e288: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
09-07 09:58:07.277  6572  6572 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-07 09:58:07.277  6572  6572 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-07 09:59:13.571  6572  6572 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-07 09:59:13.571  6572  6572 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-07 09:59:13.588  6572  6693 E OpenGLRenderer: Unable to match the desired swap behavior.
09-07 09:59:18.463  6572  6572 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-07 09:59:18.463  6572  6572 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
```
</details>

**Comment by chesskuo** [comment]
I found the issue cause by LSPosed module (1.9.2). It would cause Zygisk crash, so I will close this issue.
If you have same problem, wishing this issue can help you.

solution: using [this update about LPosed](https://github.com/mywalkb/LSPosed_mod) can solve this problem.

ref: https://xdaforums.com/t/zygisk-not-work-solved.4668984/
