### ISSUE TITLE
Play Store fails to open after new update

### ISSUE THREAD

**Issue by rpgwaiter** [topjohnwu/Magisk#8390]
Device: Pixel 4 AVD (x86_64) running through Android Studio emulator
Android version: Android 11 (API 30)
Magisk version name: 27.0
Magisk version code: Magisk (8e82113b) (27007)

Play Store version: 42.3.27-29 [0] [PR] 663053801

---

I have no modules installed, and this issue occurs with and without zygisk enabled. After a hot patch, the Play Store refuses to open and the device has a constant "Play Store keeps crashing" popup. 

Here's an adb logcat of when it happens, seems like it's trying to call a function within zygote that fails.

```
09-11 17:04:07.015  7228  7228 D AndroidRuntime: Shutting down VM
09-11 17:04:07.015  7228  7228 E AndroidRuntime: FATAL EXCEPTION: main
09-11 17:04:07.015  7228  7228 E AndroidRuntime: Process: com.android.vending, PID: 7228
09-11 17:04:07.015  7228  7228 E AndroidRuntime: java.lang.ExceptionInInitializerError
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.i(PG:6)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.h(PG:2)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.F(PG:4)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.p(PG:13)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at argr.L(PG:3)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at baqs.c(PG:22)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebz.d(PG:22)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at beby.iw(PG:13)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebw.iw(PG:3)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at baqu.c(PG:9)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebz.d(PG:22)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at beby.iw(PG:13)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebw.iw(PG:3)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at lqj.c(PG:7)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebz.d(PG:22)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at beby.iw(PG:13)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebw.iw(PG:3)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at lqn.c(PG:15)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebz.d(PG:22)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at beby.iw(PG:13)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebw.iw(PG:3)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at lqv.i(PG:577)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at lqv.onCreate(PG:23)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int auoc.size()' on a null object reference
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auny.<init>(PG:1)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.<clinit>(PG:6)
09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	... 33 more
```

I'm hoping this is within Magisk's purview to fix. If i replace the modified `ramdisk.img` with a stock one the app launches just fine. Also worth noting that I had no problem launching the Play Store before this update with Magisk running.

I don't see anything really interesting in the Magisk logs but I can post it if it would help.

**Comment by mostfaxd** [comment]
> Device: Pixel 4 AVD (x86_64) running through Android Studio emulator Android version: Android 11 (API 30) Magisk version name: 27.0 Magisk version code: Magisk ([8e82113](https://github.com/topjohnwu/Magisk/commit/8e82113bce1486c0dce7d8d1fdc08a1372ab26a6)) (27007)
> 
> Play Store version: 42.3.27-29 [0] [PR] 663053801
> 
> I have no modules installed, and this issue occurs with and without zygisk enabled. After a hot patch, the Play Store refuses to open and the device has a constant "Play Store keeps crashing" popup.
> 
> Here's an adb logcat of when it happens, seems like it's trying to call a function within zygote that fails.
> 
> ```
> 09-11 17:04:07.015  7228  7228 D AndroidRuntime: Shutting down VM
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: FATAL EXCEPTION: main
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: Process: com.android.vending, PID: 7228
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: java.lang.ExceptionInInitializerError
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.i(PG:6)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.h(PG:2)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.F(PG:4)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.p(PG:13)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at argr.L(PG:3)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at baqs.c(PG:22)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebz.d(PG:22)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at beby.iw(PG:13)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebw.iw(PG:3)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at baqu.c(PG:9)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebz.d(PG:22)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at beby.iw(PG:13)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebw.iw(PG:3)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at lqj.c(PG:7)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebz.d(PG:22)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at beby.iw(PG:13)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebw.iw(PG:3)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at lqn.c(PG:15)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebz.d(PG:22)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at beby.iw(PG:13)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at bebw.iw(PG:3)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at lqv.i(PG:577)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at lqv.onCreate(PG:23)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int auoc.size()' on a null object reference
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auny.<init>(PG:1)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	at auoc.<clinit>(PG:6)
> 09-11 17:04:07.015  7228  7228 E AndroidRuntime: 	... 33 more
> ```
> 
> I'm hoping this is within Magisk's purview to fix. If i replace the modified `ramdisk.img` with a stock one the app launches just fine. Also worth noting that I had no problem launching the Play Store before this update with Magisk running.
> 
> I don't see anything really interesting in the Magisk logs but I can post it if it would help.

**Comment by osm0sis** [comment]
Is Play Store on your DenyList? If so, try removing it, if not, try adding it.
