### ISSUE TITLE
 RCA Voyager III -- Magisk crashes installing an module

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [topjohnwu/Magisk#8452]
Trying to install any module causes Magisk to crash on "Copying zip to temporary directory". Magisk was installed via patching boot.img and flashing the patched img with Fastboot. Device is on SDK 24 (Android 7.0).

Attached txt is the logcat when trying to install a module.
[logcat.txt](https://github.com/user-attachments/files/17339354/logcat.txt)

Device: RCA Voyager III
Android version: 7.0
Magisk version name: v28.0
Magisk version code: 28001

**Comment by Lost-Entrepreneur439** [comment]
I decided to test, and have also verified this issue isn't present in 27.0, I can install modules fine in 27.

**Comment by Traviscott990** [comment]
Yes, I also faced the same problem with the latest version of Magisk 28
as the Magisk application closes immediately when trying to install any module... and the only way to install the module is to flash it through twrp.!

**Comment by aviraxp** [comment]
Post FULL LOG with DEBUG version magisk

**Comment by aviraxp** [comment]
```
java.lang.NoSuchMethodError: No virtual method getLastAccessTime()Ljava/nio/file/attribute/FileTime; in class Lorg/apache/commons/compress/archivers/zip/ZipArchiveEntry; or its super classes (declaration of 'org.apache.commons.compress.archivers.zip.ZipArchiveEntry' appears in /data/app/com.topjohnwu.magisk-1/base.apk:classes16.dex)
	at org.apache.commons.compress.archivers.zip.ZipArchiveEntry$$ExternalSyntheticAPIConversion1.m(D8$$SyntheticClass:0)
	at org.apache.commons.compress.archivers.zip.ZipArchiveEntry.requiresExtraTimeFields(ZipArchiveEntry.java:1158)
	at org.apache.commons.compress.archivers.zip.ZipArchiveEntry.setExtraTimeFields(ZipArchiveEntry.java:1309)
	at org.apache.commons.compress.archivers.zip.ZipArchiveEntry.setTime(ZipArchiveEntry.java:1472)
	at org.apache.commons.compress.archivers.zip.ZipFile.readCentralDirectoryEntry(ZipFile.java:1430)
	at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:1286)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:865)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:89)
	at org.apache.commons.compress.archivers.zip.ZipFile$Builder.get(ZipFile.java:163)
	at com.topjohnwu.magisk.core.utils.ZipUtilsKt.unzip(ZipUtils.kt:13)
	at com.topjohnwu.magisk.core.tasks.FlashZip.flash(FlashZip.kt:51)
	at com.topjohnwu.magisk.core.tasks.FlashZip.access$flash(FlashZip.kt:19)
	at com.topjohnwu.magisk.core.tasks.FlashZip$exec$2.invokeSuspend(FlashZip.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ba20a5d, Dispatchers.Main.immediate]

```

**Comment by fds39** [comment]
> Yes, I also faced the same problem with the latest version of Magisk 28 as the Magisk application closes immediately when trying to install any module... and the only way to install the module is to flash it through twrp.!

I didn't know how to install a module with twrp.
I managed to do it for 3 modules (Magisk 28.1)
2 unfortunately only work in uninstalling mode ViPER4Android, Greenify4Magisk
On the way to Magisk 28.2
