### ISSUE TITLE
Infinite recursion after desugaring on debug build

### ISSUE THREAD

**Issue by aviraxp** [topjohnwu/Magisk#8529]
Device: Oneplus Ace 2 Pro
Android version: 14
Magisk version name: 28.0
Magisk version code: 28001

```
11-03 00:34:51.763 21342 21342 E AppContext: java.lang.StackOverflowError: stack size 1039KB
11-03 00:34:51.763 21342 21342 E AppContext: 	at com.topjohnwu.magisk.core.utils.Desugar.getLastAccessTime(Desugar.java:19)
11-03 00:34:51.763 21342 21342 E AppContext: 	at com.topjohnwu.magisk.core.utils.Desugar.getLastAccessTime(Desugar.java:19)
11-03 00:34:51.763 21342 21342 E AppContext: 	at com.topjohnwu.magisk.core.utils.Desugar.getLastAccessTime(Desugar.java:19)
11-03 00:34:51.763 21342 21342 E AppContext: 	at com.topjohnwu.magisk.core.utils.Desugar.getLastAccessTime(Desugar.java:19)
11-03 00:34:51.763 21342 21342 E AppContext: 	at com.topjohnwu.magisk.core.utils.Desugar.getLastAccessTime(Desugar.java:19)
11-03 00:34:51.763 21342 21342 E AppContext: 	at com.topjohnwu.magisk.core.utils.Desugar.getLastAccessTime(Desugar.java:19)
```

**Comment by aviraxp** [comment]
Decompiled code: 
```
public static FileTime getDesugaredLastModifiedTime(ZipEntry entry) {
    if (Build.VERSION.SDK_INT >= 26) {
        return getLastModifiedTime(entry);
    } else {
        return FileTime.fromMillis(entry.getTime());
    }
}
```
