### ISSUE TITLE
Magisk Manager keeps force stopping after update from 17.1 to 18

### ISSUE THREAD

**Issue by galapogos** [topjohnwu/Magisk#856]
Hi,

I just updated my Magisk Manager from within the app from v17.1 to v18, and now it keeps force stopping when I set my WiFi proxy to a non-existent proxy (i.e. no internet connection). Logcat output when it crashes is as follows:

```
12-11 13:41:05.720 21419 21484 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
12-11 13:41:05.720 21419 21484 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 21419
12-11 13:41:05.720 21419 21484 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int a.zi.c' on a null object reference
12-11 13:41:05.720 21419 21484 E AndroidRuntime:        at a.uv.a(Unknown Source)
12-11 13:41:05.720 21419 21484 E AndroidRuntime:        at a.uv.b(Unknown Source)
12-11 13:41:05.720 21419 21484 E AndroidRuntime:        at a.uv.lambda$ZFQE15Y-O-EDUdsm62tZ8CmB2-A(Unknown Source)
12-11 13:41:05.720 21419 21484 E AndroidRuntime:        at a.-$$Lambda$uv$ZFQE15Y-O-EDUdsm62tZ8CmB2-A.run(lambda)
12-11 13:41:05.720 21419 21484 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-11 13:41:05.720 21419 21484 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-11 13:41:05.720 21419 21484 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
12-11 13:41:05.723   881  3514 W ActivityManager:   Force finishing activity com.topjohnwu.magisk/a.b
```
My device is a Nexus 5X running Android 6.0.1.

I haven't actually tested on Airplane mode to see if it's a problem with internet connection, or just a non-existent proxy.

**Comment by topjohnwu** [comment]
Already fixed fd4a27dbf2851806741a3789423e9ec32b7d4f63
It's a network issue of your phone
