### ISSUE TITLE
Crash when patching a AP tar file

### ISSUE THREAD

**Issue by r3pek** [topjohnwu/Magisk#8587]
Device: Samsung A13 5G
Android version: 14
Magisk version name: -
Magisk version code: 28002

Just installed the latest version of the Magisk apk and when patching an AP file to install later, the app crashes with this error:
```
12-02 10:39:30.077 14575 14575 E AppContext: java.lang.VerifyError: Verifier rejected class org.apache.commons.compress.archivers.tar.TarArchiveOutputStream: void org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.addPaxHeadersForBigNumbers(java.util.Map, org.apache.commons.compress.archivers.tar.TarArchiveEntry) failed to verify: void org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.addPaxHeadersForBigNumbers(java.util.Map, org.apache.commons.compress.archivers.tar.TarArchiveEntry): [0x1C] register v9 has type Reference: org.apache.commons.compress.archivers.tar.TarArchiveEntry but expected Reference: java.util.zip.ZipEntry
12-02 10:39:30.077 14575 14575 E AppContext:  void org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(org.apache.commons.compress.archivers.tar.TarArchiveEntry) failed to verify: void org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(org.apache.commons.compress.archivers.tar.TarArchiveEntry): [0x1C] register v14 has type Reference: org.apache.commons.compress.archivers.tar.TarArchiveEntry but expected Reference: java.util.zip.ZipEntry
12-02 10:39:30.077 14575 14575 E AppContext:  void org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.transferModTime(org.apache.commons.compress.archivers.tar.TarArchiveEntry, org.apache.commons.compress.archivers.tar.TarArchiveEntry) failed to verify: void org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.transferModTime(org.apache.commons.compress.archivers.tar.TarArchiveEntry, org.apache.commons.compress.archivers.tar.TarArchiveEntry): [0x0] register v5 has type Reference: org.apache.commons.compress.archivers.tar.TarArchiveEntry but expected Reference: java.util.zip.ZipEntry (declaration of 'org.apache.commons.compress.archivers.tar.TarArchiveOutputStream' appears in /data/app/~~jGntEyo-hAxHdKWiB6m3tg==/com.topjohnwu.magisk-uyNef2hOnxmVgKVaRXVOCQ==/base.apk!classes16.dex)
12-02 10:39:30.077 14575 14575 E AppContext:    at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.processFile(MagiskInstaller.kt:446)
12-02 10:39:30.077 14575 14575 E AppContext:    at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchFile(MagiskInstaller.kt:575)
12-02 10:39:30.077 14575 14575 E AppContext:    at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:639)
12-02 10:39:30.077 14575 14575 E AppContext:    at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:595)
12-02 10:39:30.077 14575 14575 E AppContext:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-02 10:39:30.077 14575 14575 E AppContext:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
12-02 10:39:30.077 14575 14575 E AppContext:    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
12-02 10:39:30.077 14575 14575 E AppContext:    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
12-02 10:39:30.077 14575 14575 E AppContext:    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
12-02 10:39:30.077 14575 14575 E AppContext:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
12-02 10:39:30.077 14575 14575 E AppContext:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
12-02 10:39:30.077 14575 14575 E AppContext:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
12-02 10:39:30.077 14575 14575 E AppContext:    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ab6cb6b, Dispatchers.Main.immediate]
12-02 10:39:30.082 14575 14575 I opjohnwu.magisk: System.exit called, status: 1
```

(It works fine with 28001)

**Comment by User10987654321** [comment]
I see you are using android 14. Do you have zygisk working? If so, is this because you have rolled back from Android 15 or another reason?
