### ISSUE TITLE
Magisk is not installed after patching boot image in Motorola FOGONA_G

### ISSUE THREAD

**Issue by rostikblade** [topjohnwu/Magisk#8597]
[boot.zip](https://github.com/user-attachments/files/18015907/boot.zip)
[magisk_patched-28003_dbCoz.zip](https://github.com/user-attachments/files/18015908/magisk_patched-28003_dbCoz.zip)

Magisk is not installed after patching boot image in Motorola FOGONA_G, tested in 4 similar devices

Device: Motorola XT2413-2
Android version: 14
Magisk version name:28003
Magisk version code:28003

**Comment by rostikblade** [comment]
@vvb2060 could you please check this issue??? I dont know what else to do about it, thanks a lot in advance

**Comment by rostikblade** [comment]
This issue is still happening with V 28.1

**Comment by duvjones** [comment]
If I am to make a guess, when writing to the Boot cancel partition.... do you see this`(bootloader) Preflash validation failed`?

**Comment by rostikblade** [comment]
> If I am to make a guess, when writing to the Boot cancel partition.... do you see this`(bootloader) Preflash validation failed`?

Hey, thanks for the reply, nothing about that:

fastboot flash boot .\magisk_patched-28100_ivKQW.img                                                        Sending 'boot_a' (98304 KB)                        OKAY [  2.156s]
Writing 'boot_a'                                   OKAY [  1.713s]
Finished. Total time: 3.881s

I know exactly what you are saying, it happens with another Motorola model, flashing boot showed and error in the second stage of the process that indicated a validation failed, that was fixed, booting the boot image without flashing and installing Magisk after.

**Comment by rostikblade** [comment]
the only clue I have so far is this:

12-07 10:55:32.857 13646 13646 I opjohnwu.magisk: Using CollectorTypeCMC GC.
12-07 10:55:32.863 13646 13646 E opjohnwu.magisk: Not starting debugger since process cannot load the jdwp agent.

**Comment by rostikblade** [comment]
also get this from Logcat:

13:37:08.424 12501-12552 GoogleApiManager     com.topjohnwu.magisk              E  Failed to get service from broker. 
                                                                                   java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
                                                                                   	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                   	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                   	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                   	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                   	at anrz.a(:com.google.android.gms@244631029@24.46.31 (190400-699197446):36)
                                                                                   	at anqg.z(:com.google.android.gms@244631029@24.46.31 (190400-699197446):143)
                                                                                   	at amxn.run(:com.google.android.gms@244631029@24.46.31 (190400-699197446):54)
                                                                                   	at android.os.Handler.handleCallback(Handler.java:1000)
                                                                                   	at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                   	at btul.mA(:com.google.android.gms@244631029@24.46.31 (190400-699197446):1)
                                                                                   	at btul.dispatchMessage(:com.google.android.gms@244631029@24.46.31 (190400-699197446):5)
                                                                                   	at android.os.Looper.loopOnce(Looper.java:242)
                                                                                   	at android.os.Looper.loop(Looper.java:362)
                                                                                   	at android.os.HandlerThread.run(HandlerThread.java:85)

**Comment by rostikblade** [comment]
The solution is to use version 27 of Magisk (most). Version 28.1 generates a corrupted file when the init_boot is patched ([this post](https://github.com/topjohnwu/Magisk/issues/8389): https://github.com/topjohnwu/Magisk/issues/8389 was and eye opening). So, the workaround is to stick with version 27 for the entire process and then update to version 28.1 afterward.

**Comment by pndwal** [comment]
So seems you were patch/flashing boot.img, and now init_boot.img... Assuming you restored both to stock before attempting to flash 28.1, it would be good to re-open this issue so that the outstanding issue of '28.1 generating a corrupted file' can be addressed and fixed also. 👍

**Comment by ljmf00** [comment]
On Oneplus 11 also happens this, used to patch `init_boot.img` and upgrading from Magisk 28.1, it shows as not installed but on 27.0 it works. I can help providing logs if necessary.

**Comment by Heat84** [comment]
> The solution is to use version 27 of Magisk (most). Version 28.1 generates a corrupted file when the init_boot is patched ([this post](https://github.com/topjohnwu/Magisk/issues/8389): #8389 was and eye opening). So, the workaround is to stick with version 27 for the entire process and then update to version 28.1 afterward.

The problem with 28 doesn't occur again the next time you flash a patched boot.img?

**Comment by froilanmangeles570-lgtm** [comment]
Installation

Failed!

a

Device platform: arm64-v8a

R6687BB53suu-kitsune (27001) Installing:

Processing zip file

! No boot image found

! Process error

! Installation failed
