### ISSUE TITLE
open Magisk Manager v6.1.0 crash  after use TWRP install Magisk-v18.0.zip

### ISSUE THREAD

**Issue by jiyewushen** [topjohnwu/Magisk#887]
phone info: Moto G 2014 LTE,
 system info: LineageOS 15.1  android 8.1.0
erro info:
 ```java
1970-01-01 17:49:14.261 3280-3375/? D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8226.so from current namespace instead of sphal namespace.
    
    --------- beginning of crash
1970-01-01 17:49:14.277 3280-3361/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.topjohnwu.magisk, PID: 3280
    java.lang.NullPointerException: Attempt to read from field 'int a.zi.c' on a null object reference
        at a.uv.a(Unknown Source:103)
        at a.uv.b(Unknown Source:23)
        at a.uv.lambda$ZFQE15Y-O-EDUdsm62tZ8CmB2-A(Unknown Source:0)
        at a.-$$Lambda$uv$ZFQE15Y-O-EDUdsm62tZ8CmB2-A.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
1970-01-01 17:49:14.292 552-567/? W/ActivityManager:   Force finishing activity com.topjohnwu.magisk/a.b
 ```

**Comment by malnvenshorn** [comment]
Can confirm this issue on Samsung S5 Mini with LinageOS 14.1 (Android 7.1.2).
Last working version 6.0.1
