### ISSUE TITLE
zipsigner - issue with special chars in filenames inside the zip

### ISSUE THREAD

**Issue by ale5000-git** [topjohnwu/Magisk#954]
Including in the zip a file named: `·.txt`

Give this:
```
Exception in thread "main" java.lang.IllegalArgumentException: MALFORMED
        at java.util.zip.ZipCoder.toString(Unknown Source)
        at java.util.zip.ZipFile.getZipEntry(Unknown Source)
        at java.util.zip.ZipFile.access$900(Unknown Source)
        at java.util.zip.ZipFile$ZipEntryIterator.next(Unknown Source)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(Unknown Source)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(Unknown Source)
        at java.util.jar.JarFile$JarEntryIterator.next(Unknown Source)
        at java.util.jar.JarFile$JarEntryIterator.nextElement(Unknown Source)
        at java.util.jar.JarFile$JarEntryIterator.nextElement(Unknown Source)
        at com.topjohnwu.utils.SignAPK.addDigestsToManifest(SignAPK.java:211)
        at com.topjohnwu.utils.SignAPK.sign(SignAPK.java:137)
        at com.topjohnwu.utils.SignAPK.sign(SignAPK.java:102)
        at com.topjohnwu.utils.SignAPK.sign(SignAPK.java:82)
        at com.topjohnwu.utils.SignAPK.sign(SignAPK.java:74)
        at com.topjohnwu.utils.ZipSigner.main(ZipSigner.java:28)
```

**Comment by topjohnwu** [comment]
I do not plan to support this since I use the zip implementation in the Java standard library
